Repository OriginTrail/ot-node, pull requests merged in 2018-09, with the labels that each got.

#519 NODE_WALLET as an ENV variable
  testnet/register-node.js
Labels: bug

#521 Fix fingerprint double response
  modules/EventEmitter.js
  package-lock.json
  package.json
Labels: bug

#522 Stable v1.3.24
  modules/EventEmitter.js
  package-lock.json
  package.json
Labels: enhancement

#523 v1.3.24
  .env.example
  importers/xml_examples/Retail/03_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail/04_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail/05_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail/06_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_Zk/04_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail_with_Zk/05_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail_with_Zk/06_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail_with_Zk/07_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_aggregation/01_Green_packing.xml
  importers/xml_examples/Retail_with_aggregation/02_Green_to_pink_shipment.xml
  importers/xml_examples/Retail_with_aggregation/03_Green_to_pink_receipt.xml
  importers/xml_examples/Retail_with_aggregation/04_Pink_to_orange_shipment.xml
  importers/xml_examples/Retail_with_aggregation/05_Pink_to_orange_receipt.xml
  importers/xml_examples/Retail_with_aggregation/06_Orange_unpacking.xml
  importers/xml_examples/Retail_with_aggregation/07_Orange_unpacking_all.xml
  migrations/20180407120531-create-data-info.js
  models/data_info.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/Transactions.js
  modules/Blockchain/Ethereum/contracts/Escrow.sol
  modules/Blockchain/Ethereum/contracts/OTFingerprintStore.sol
  modules/Blockchain/Ethereum/escrow-contract/abi.json
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/ot-contract/abi.json
  modules/Blockchain/Ethereum/signing.js
  modules/Blockchain/Ethereum/test/bidding.test.js
  modules/DHService.js
  modules/EventEmitter.js
  modules/GS1Importer.js
  modules/GS1Utilities.js
  modules/ImportUtilities.js
  modules/Network.js
  modules/Utilities.js
  modules/WOTImporter.js
  modules/command/command-executor.js
  modules/command/dc/dc-offer-key-verification-command.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/command/dh/dh-offer-bid-add-command.js
  modules/command/dh/dh-offer-handle-import-command.js
  modules/controller/dc-controller.js
  modules/errors/index.js
  modules/errors/network-request-ignored-error.js
  modules/importer.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407124949-node-config.js
  seeders/20180407223548-blockchain_data.js
  test/api/zkGetTrail.test.js
  test/modules/gs1-importer.test.js
  test/modules/utilities.test.js
  test/modules/wot-importer.test.js
  test/protocol/protocol.test.js
  testnet/register-node.js
Labels: chore

#524 Peer cache cleanup [Delivers #159887837]
  modules/Network.js
  modules/kademlia/peer-cache.js
  test/modules/peercache.test.js
Labels: bug

#510 Improving output of two log lines
  modules/EventEmitter.js
  modules/ProfileService.js
Labels: minor

#428 Add getRootHash() check to protocol test suite
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  test/protocol/protocol.test.js
Labels: chore

#525 Disable failing test case getRootHash
  test/protocol/protocol.test.js
Labels: minor

#526 Environment variables override .env file
  testnet/register-node.js
Labels: bug

#528 Update postman collection with api/import_info route [Related to #160051672]
  postman/OriginTrail.postman_collection.json
  postman/ot-env.postman_environment.json
Labels: enhancement

#531 Use new auto-updater (#159887620)
  check-updates.js
  config/runtimeConfig.json
  package-lock.json
  package.json
Labels: internal process

#527 Adding unit tests for normalizeHex()
  test/modules/utilities.test.js
Labels: minor

#532 Unit test for DCOfferCreateDatabaseCommand [#160251234]
  package.json
  test/modules/command/dc/dc-offer-create-database-command.test.js
Labels: enhancement

#536 Suppress deprecated String based operators warning
  config/config.json
Labels: minor

#533 Update grenrc tool to ignore internal process label
  .grenrc.js
Labels: minor

#534 Network resilience [#159888909]
  modules/Challenger.js
  modules/DHService.js
  modules/DVService.js
  modules/DataReplication.js
  modules/EventEmitter.js
  modules/RemoteControl.js
  modules/Utilities.js
  modules/command/dc/dc-escrow-cancel-command.js
  modules/command/dc/dc-escrow-verify-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-key-verification-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-offer-handle-import-command.js
  modules/command/dh/dh-offer-replication-parameters-save-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-location-response-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/command/dv/dv-handle-network-query-responses-command.js
  modules/command/dv/dv-query-network-command.js
  modules/kademlia/KademliaUtils.js
  modules/network/kademlia/kademlia-utils.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/peer-cache.js
  modules/network/kademlia/workers/challenger.js
  modules/network/kademlia/workers/identity.js
  modules/network/kademlia/workers/solver.js
  modules/network/transport.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407124949-node-config.js
  test/modules/gs1-importer.test.js
  test/modules/peercache.test.js
  test/modules/transport.test.js
Labels: enhancement

#541 Multiple fixes
  .env.example
  modules/Blockchain/Ethereum/Transactions.js
  testnet/register-node.js
Labels: bug

#544 Command transactions removal
  modules/command/common/cleaner-command.js
  modules/command/dc/dc-offer-create-database-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-ready-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-bid-added-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-offer-replication-parameters-save-command.js
  modules/command/dh/dh-read-data-location-request-command.js
Labels: bug

#545 Skip third party log
  modules/Utilities.js
  ot-node.js
Labels: chore

#549 Extra logs
  modules/Utilities.js
  modules/command/dc/dc-offer-key-verification-command.js
  modules/command/dh/dh-offer-replication-parameters-command.js
  package-lock.json
  package.json
Labels: chore

#548 Skip third party log
  modules/Utilities.js
Labels: minor

#550 Kadence version bump
  package-lock.json
  package.json
Labels: enhancement

#546 HTTP network prototype, transport abstraction fixes
  modules/Challenger.js
  modules/EventEmitter.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  ot-node.js
  package-lock.json
  package.json
Labels: enhancement

#547 Unit test for dc-offer-create-blockchain-command.js [#160251227]
  test/modules/command/dc/dc-offer-create-blockchain-command.test.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
Labels: enhancement

#551 Add unit test for findVertexWithMaxVersion() [#157553357]
  test/modules/arangojs.test.js
Labels: chore, enhancement

#555 Align offer.message with offer.status -es [#159820541]
  modules/command/dc/dc-offer-cancel-command.js
  modules/command/dc/dc-offer-create-blockchain-command.js
  modules/command/dc/dc-offer-ready-command.js
  modules/command/dc/dc-offer-root-hash-command.js
Labels: chore

#557 Fix distribution root hash error
  modules/command/dc/dc-offer-key-verification-command.js
  modules/command/dh/dh-offer-replication-parameters-command.js
Labels: bug

#556 Network retry fix [#160648605]
  modules/EventEmitter.js
  modules/command/command-executor.js
  modules/command/dh/dh-offer-handle-command.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/peer-cache.js
  modules/network/transport.js
  test/modules/peercache.test.js
  test/modules/transport.test.js
Labels: bug

#553 Validate search network query [#160170783]
  .gitignore
  modules/DHService.js
  modules/Database/Arangojs.js
  modules/EventEmitter.js
  modules/Product.js
  modules/validator/object-validator.js
  modules/validator/rest-api-validator.js
  ot-node.js
  package-lock.json
  package.json
Labels: enhancement

#558 Fix data location read request
  modules/controller/dh-controller.js
Labels: bug

#475 Config refactor (#157397545)
  .env.travis
  .origintrail-noderc.travis
  .travis.yml
  check-updates.js
  config/config.json
  config/runtimeConfig.json
  config/sequelizeConfig.js
  migrations/20180407124904-create-node-config.js
  models/blockchain_data.js
  models/graph_database.js
  models/index.js
  models/node_config.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/Config.js
  modules/Control.js
  modules/DataReplication.js
  modules/Database/GraphStorage.js
  modules/EventEmitter.js
  modules/GS1Importer.js
  modules/RemoteControl.js
  modules/Utilities.js
  modules/WOTImporter.js
  modules/command/dh/dh-offer-handle-command.js
  modules/network/kademlia/kademlia-utils.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/workers/identity.js
  ot-node.js
  package-lock.json
  package.json
  scripts/setup.js
  seeders/.gitkeep
  seeders/20180407121512-graph-database.js
  seeders/20180407124949-node-config.js
  seeders/20180407223548-blockchain_data.js
  test/api/zkGetTrail.test.js
  test/modules/arangojs.test.js
  test/modules/command/dc/dc-offer-create-blockchain-command.test.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/gs1-importer.test.js
  test/modules/transport.test.js
  test/modules/utilities.test.js
  test/modules/wot-importer.test.js
  test/protocol/protocol.test.js
  testnet/register-node.js
Labels: bug, enhancement, internal process

#559 Fix Kadence config
  data/.gitkeep
  modules/network/kademlia/kademlia.js
Labels: bug

#562 Docker fix
  .dockerignore
  Dockerfile
  Dockerfile.development
  Dockerfile.stable
  Dockerfile.staging
  testnet/register-node.js
  testnet/supervisord.conf
Labels: bug, enhancement

#563 Do not check for devDependencies in production env (#160721383)
  modules/Utilities.js
Labels: bug

#565 Read data validation [#160723643]
  modules/command/dv/dv-data-read-response-free-command.js
Labels: bug

#566 Use 'production' env instead 'testnet'
  ot-node.js
Labels: bug

#569 Use solidity SHA3 (#160750745)
  modules/Utilities.js
Labels: bug

#570 Missing contact patch
  modules/EventEmitter.js
  modules/command/command-executor.js
  modules/command/dc/dc-offer-cancel-command.js
  modules/command/dc/dc-offer-create-blockchain-command.js
  modules/command/dc/dc-offer-key-verification-command.js
  modules/command/dc/dc-offer-ready-command.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-offer-replication-parameters-command.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/peer-cache.js
  modules/network/transport.js
  package-lock.json
  package.json
  test/modules/arangojs.test.js
  test/modules/command/dc/dc-offer-create-blockchain-command.test.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/peercache.test.js
  test/modules/transport.test.js
Labels: bug, hotfix

#572 Read fix
  modules/EventEmitter.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/controller/dh-controller.js
  package-lock.json
  package.json
Labels: bug, hotfix

#571 Missing contact fix (stable)
  modules/Challenger.js
  modules/EventEmitter.js
  modules/Utilities.js
  modules/command/command-executor.js
  modules/command/dc/dc-offer-cancel-command.js
  modules/command/dc/dc-offer-create-blockchain-command.js
  modules/command/dc/dc-offer-key-verification-command.js
  modules/command/dc/dc-offer-ready-command.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-offer-replication-parameters-command.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/peer-cache.js
  modules/network/transport.js
  ot-node.js
  package-lock.json
  package.json
  test/modules/arangojs.test.js
  test/modules/command/dc/dc-offer-create-blockchain-command.test.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/peercache.test.js
  test/modules/transport.test.js
Labels: bug, hotfix

#578 Version update 1.3.37
  modules/Blockchain/Ethereum/contracts/Escrow.sol
  modules/Blockchain/Ethereum/escrow-contract/abi.json
  modules/Utilities.js
  package-lock.json
  package.json
Labels: bug, hotfix

#580 Network fixes
  modules/network/kademlia/kademlia.js
  package-lock.json
  package.json
Labels: bug

#581 Remove Spartacus private key
  modules/network/kademlia/kademlia.js
Labels: bug

#583 Contract update
  modules/Blockchain/Ethereum/contracts/Escrow.sol
  modules/Blockchain/Ethereum/escrow-contract/abi.json
Labels: bug

#585 Fix sqlbusy during location read
  modules/command/dv/dv-data-location-response-command.js
Labels: bug, hotfix

#575 Handle AssertionError in modules/EventEmitter.js:428 [#160786344]
  modules/EventEmitter.js
Labels: bug

#591 Testnet catchup + Spartacus
  config/runtimeConfig.json
  modules/DataReplication.js
  modules/Database/Arangojs.js
  modules/EventEmitter.js
  modules/command/dh/dh-offer-handle-import-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/controller/dc-controller.js
  modules/controller/dh-controller.js
  modules/network/kademlia/kademlia.js
Labels: bug, hotfix

#592 Disable Spartacus
  modules/network/kademlia/kademlia.js
Labels: bug, hotfix

#584 Remove litigation interval from Escrow smart contract
  modules/Blockchain/Ethereum/contracts/Escrow.sol
  modules/Blockchain/Ethereum/escrow-contract/abi.json
Labels: minor

#573 Fix for this.logger is not a function [#160789301]
  modules/command/dv/dv-handle-network-query-responses-command.js
Labels: bug, minor

#594 Remove openssl log
  modules/Utilities.js
  package-lock.json
  package.json
Labels: hotfix

#593 Bump stable network version
  config/runtimeConfig.json
  modules/Utilities.js
  package-lock.json
  package.json
Labels: enhancement
