Repository OriginTrail/ot-node, pull requests merged in 2018-08, with the labels that each got.

#419 Catching up with eslint errors in project
  newrelic.js
  package-lock.json
  package.json
  testnet/register-node.js
Labels: minor

#415 Introduce timestamps on stdout [Delivers #159411464]
  modules/Utilities.js
Labels: chore

#418 Add filtering contacts based on IP address and network ID
  .env.example
  .env.travis
  modules/Network.js
  package.json
  seeders/20180407124949-node-config.js
  test/modules/utilities.test.js
Labels: enhancement

#417 Hide some logs
  modules/kademlia/KademliaUtils.js
Labels: chore

#422 Remove NewRelic
  CHANGELOG.md
  newrelic.js
  package-lock.json
  package.json
Labels: minor

#424 Feature/read command sourcing
  modules/DHService.js
  modules/DVService.js
  modules/DataReplication.js
  modules/EventEmitter.js
  modules/Network.js
  modules/command/command-executor.js
  modules/command/command.js
  modules/command/dc/dc-offer-cancel-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-location-response-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-handle-network-query-responses-command.js
  modules/command/dv/dv-query-network-command.js
  modules/controller/dh-controller.js
  modules/controller/dv-controller.js
Labels: enhancement

#426 Fix unhandled Promise rejection this.restartNode is not a function
  check-updates.js
  package.json
Labels: bug

#423 Improving config for github release notes package
  .grenrc.js
  package.json
Labels: minor

#429 incremented node version to 1.3.1 and deployed new contracts
  package.json
  seeders/20180407223548-blockchain_data.js
Labels: enhancement

#430 Update fingerprint smart contract address in rinkeby migration log
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
Labels: minor

#432 added new bootstrap node address
  .env.example
  testnet/register-node.js
Labels: enhancement

#433 Support bug tracking with bugsnag
  config/config.json
  ot-node.js
  package-lock.json
  package.json
Labels: chore, enhancement

#431 Disable NAT by default
  .env.example
  .env.travis
  testnet/register-node.js
Labels: enhancement

#435 Ignore only development environment when reporting
  ot-node.js
  seeders/20180407223548-blockchain_data.js
  test/modules/utilities.test.js
Labels: bug, chore

#442 Fix fetching code in docker
  Dockerfile
  testnet/start.sh
Labels: bug

#443 Bump
  Dockerfile
Labels: minor

#439 Fix using IS_BOOTSTRAP_NODE variable
  seeders/20180407124949-node-config.js
Labels: bug

#440 Fix docker image update
  package.json
Labels: minor

#445 Introduce tags for logs
  modules/Utilities.js
Labels: enhancement

#447 Remove sensitive data
  ot-node.js
Labels: bug

#446 Introduce tag for bugsnag
  modules/Utilities.js
  ot-node.js
Labels: enhancement

#450 Manual merge develop into master
  .env.example
  Dockerfile
  modules/Utilities.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407124949-node-config.js
  testnet/register-node.js
Labels: enhancement

#449 Manual merge with develop
  modules/Utilities.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407124949-node-config.js
Labels: enhancement

#452 Notify bugsnag about handled errors
  modules/Challenger.js
  modules/DHService.js
  modules/DVService.js
  modules/EventEmitter.js
  modules/Network.js
  modules/NetworkUtilities.js
  modules/RemoteControl.js
  modules/command/command-executor.js
  modules/command/dc/dc-offer-cancel-command.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/importer.js
  ot-node.js
  test/modules/challenge.test.js
  test/modules/gs1-importer.test.js
  test/protocol/protocol.test.js
Labels: enhancement

#454 Version updated to 1.3.5
  package-lock.json
  package.json
Labels: chore

#459 Introduce Postman api endpoints collection
  postman/OriginTrail.postman_collection.json
  postman/ot-env.postman_environment.json
Labels: enhancement

#461 Enable free of charge purchasing
  modules/EventEmitter.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/controller/dh-controller.js
  modules/controller/dv-controller.js
  modules/importer.js
  ot-node.js
Labels: bug, enhancement

#464 Version updated to 1.3.6
  package-lock.json
  package.json
Labels: minor

#458 Get rid of [object][object] in api endpoints logs
  modules/EventEmitter.js
Labels: minor

#467 Prevent sorting with _dc_key during DH replication
  modules/command/dh/dh-offer-replication-parameters-command.js
Labels: bug

#469 fix use of escrow cancel
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/command/dc/dc-escrow-cancel-command.js
Labels: bug

#470 Fix listening in local network
  ot-node.js
Labels: bug

#471 Version 1.3.8
  modules/Blockchain.js
  modules/Blockchain/Ethereum/Transactions.js
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/command/dc/dc-escrow-cancel-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-replication-parameters-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/controller/dh-controller.js
  modules/controller/dv-controller.js
  modules/importer.js
  ot-node.js
  package-lock.json
  package.json
  postman/OriginTrail.postman_collection.json
  postman/ot-env.postman_environment.json
Labels: chore

#477 Notify bugsnag about distribution hash problem
  modules/command/dc/dc-offer-key-verification-command.js
  ot-node.js
  package-lock.json
Labels: chore, enhancement

#479 Update web3 to 1.0.0-beta35
  package-lock.json
  package.json
Labels: enhancement

#482 Fix ip address retrieval
  package-lock.json
  package.json
  testnet/register-node.js
Labels: bug

#481 Add filtering of network requests
  modules/Network.js
  modules/errors/index.js
  modules/errors/network-request-ignored-error.js
Labels: bug, enhancement

#483 Add transaction hash to imports
  migrations/20180407120531-create-data-info.js
  models/data_info.js
  modules/EventEmitter.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/controller/dc-controller.js
  ot-node.js
  package-lock.json
  package.json
Labels: enhancement

#484 New API routes
  .env.example
  Dockerfile
  migrations/20180407120531-create-data-info.js
  models/data_info.js
  modules/EventEmitter.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/controller/dc-controller.js
  ot-node.js
  package-lock.json
  package.json
  test/modules/gs1-importer.test.js
  test/protocol/protocol.test.js
  testnet/register-node.js
Labels: enhancement

#485 Kadence contact hostname
  modules/Network.js
  modules/Utilities.js
  testnet/register-node.js
Labels: bug

#488 develop catchup
  migrations/20180407120531-create-data-info.js
  models/data_info.js
  modules/EventEmitter.js
  modules/Network.js
  modules/Utilities.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/controller/dc-controller.js
  modules/errors/index.js
  modules/errors/network-request-ignored-error.js
  ot-node.js
  package-lock.json
  package.json
  test/modules/gs1-importer.test.js
  test/protocol/protocol.test.js
  testnet/register-node.js
Labels: enhancement

#480 Add sender to verify encryption key request
  modules/EventEmitter.js
Labels: enhancement

#487 Fix wallets in XML examples
  importers/xml_examples/Retail/03_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail/04_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail/05_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail/06_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_Zk/04_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail_with_Zk/05_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail_with_Zk/06_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail_with_Zk/07_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_aggregation/01_Green_packing.xml
  importers/xml_examples/Retail_with_aggregation/02_Green_to_pink_shipment.xml
  importers/xml_examples/Retail_with_aggregation/03_Green_to_pink_receipt.xml
  importers/xml_examples/Retail_with_aggregation/04_Pink_to_orange_shipment.xml
  importers/xml_examples/Retail_with_aggregation/05_Pink_to_orange_receipt.xml
  importers/xml_examples/Retail_with_aggregation/06_Orange_unpacking.xml
  importers/xml_examples/Retail_with_aggregation/07_Orange_unpacking_all.xml
Labels: chore

#489 Support SSL for API routes
  ot-node.js
  seeders/20180407124949-node-config.js
  test/modules/utilities.test.js
Labels: enhancement

#490 Import content fix
  modules/EventEmitter.js
  modules/GS1Importer.js
  modules/Utilities.js
  modules/WOTImporter.js
  modules/command/dc/dc-offer-root-hash-command.js
  ot-node.js
  test/api/zkGetTrail.test.js
  test/modules/gs1-importer.test.js
  test/modules/wot-importer.test.js
Labels: bug

#491 Add route for dumping routing table
  ot-node.js
Labels: chore, enhancement

#492 Suppress bugsnag info messages
  ot-node.js
Labels: chore

#493 Decrease parallelism for command executor
  modules/Blockchain/Ethereum/Transactions.js
  modules/command/command-executor.js
Labels: bug

#497 Add bidding fallback
  modules/command/command-executor.js
  modules/command/dh/dh-offer-handle-command.js
  ot-node.js
Labels: bug, enhancement

#495 process.exit(3) instead of process.kill(3)
  testnet/register-node.js
Labels: minor

#496 Calculate import data hash and write it to blockchain
  migrations/20180407120531-create-data-info.js
  models/data_info.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/contracts/OTFingerprintStore.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/ot-contract/abi.json
  modules/Blockchain/Ethereum/signing.js
  modules/DHService.js
  modules/EventEmitter.js
  modules/GS1Utilities.js
  modules/ImportUtilities.js
  modules/Utilities.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/importer.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407223548-blockchain_data.js
  test/modules/gs1-importer.test.js
  test/protocol/protocol.test.js
Labels: enhancement

#498 Fix DH import data
  modules/command/dh/dh-offer-handle-import-command.js
Labels: bug

#499 Add import hash to response
  modules/EventEmitter.js
Labels: chore

#500 Import info route implementation
  modules/DHService.js
  modules/EventEmitter.js
  ot-node.js
Labels: bug

#501 Feature/staging v1.3.16
  migrations/20180407120531-create-data-info.js
  models/data_info.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/contracts/OTFingerprintStore.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/ot-contract/abi.json
  modules/Blockchain/Ethereum/signing.js
  modules/DHService.js
  modules/EventEmitter.js
  modules/GS1Utilities.js
  modules/ImportUtilities.js
  modules/Utilities.js
  modules/command/command-executor.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-offer-handle-import-command.js
  modules/importer.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407223548-blockchain_data.js
  test/modules/gs1-importer.test.js
  test/protocol/protocol.test.js
  testnet/register-node.js
Labels: chore

#373 Variable litigation interval
  modules/Blockchain/Ethereum/contracts/Escrow.sol
  modules/Blockchain/Ethereum/escrow-contract/abi.json
Labels: enhancement

#460 Improve reading smart contract test coverage
  modules/Blockchain/Ethereum/test/bidding.test.js
Labels: chore

#503 Fix logs related to import (root_hash, import_hash)
  modules/importer.js
Labels: chore

#502 Handle recover for adding bid
  modules/command/command-executor.js
  modules/command/dh/dh-offer-bid-add-command.js
  modules/command/dh/dh-offer-handle-command.js
Labels: bug

#504 Write import_hash to blockchain
  modules/EventEmitter.js
  modules/controller/dc-controller.js
Labels: bug

#505 Fix formatting of fingerprint route
  modules/EventEmitter.js
  modules/Utilities.js
Labels: bug

#506 Route import_info fix
  modules/EventEmitter.js
Labels: chore

#507 Stable v1.3.17
  importers/xml_examples/Retail/03_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail/04_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail/05_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail/06_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_Zk/04_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail_with_Zk/05_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail_with_Zk/06_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail_with_Zk/07_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_aggregation/01_Green_packing.xml
  importers/xml_examples/Retail_with_aggregation/02_Green_to_pink_shipment.xml
  importers/xml_examples/Retail_with_aggregation/03_Green_to_pink_receipt.xml
  importers/xml_examples/Retail_with_aggregation/04_Pink_to_orange_shipment.xml
  importers/xml_examples/Retail_with_aggregation/05_Pink_to_orange_receipt.xml
  importers/xml_examples/Retail_with_aggregation/06_Orange_unpacking.xml
  importers/xml_examples/Retail_with_aggregation/07_Orange_unpacking_all.xml
  migrations/20180407120531-create-data-info.js
  models/data_info.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/Transactions.js
  modules/Blockchain/Ethereum/contracts/Escrow.sol
  modules/Blockchain/Ethereum/contracts/OTFingerprintStore.sol
  modules/Blockchain/Ethereum/escrow-contract/abi.json
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/ot-contract/abi.json
  modules/Blockchain/Ethereum/signing.js
  modules/Blockchain/Ethereum/test/bidding.test.js
  modules/DHService.js
  modules/EventEmitter.js
  modules/GS1Importer.js
  modules/GS1Utilities.js
  modules/ImportUtilities.js
  modules/Network.js
  modules/Utilities.js
  modules/WOTImporter.js
  modules/command/command-executor.js
  modules/command/dc/dc-offer-root-hash-command.js
  modules/command/dh/dh-offer-bid-add-command.js
  modules/command/dh/dh-offer-handle-import-command.js
  modules/controller/dc-controller.js
  modules/errors/index.js
  modules/errors/network-request-ignored-error.js
  modules/importer.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407124949-node-config.js
  seeders/20180407223548-blockchain_data.js
  test/api/zkGetTrail.test.js
  test/modules/gs1-importer.test.js
  test/modules/utilities.test.js
  test/modules/wot-importer.test.js
  test/protocol/protocol.test.js
  testnet/register-node.js
Labels: chore

#508 CORS headers
  ot-node.js
Labels: bug

#509 Stable v1.3.18
  ot-node.js
  package-lock.json
  package.json
Labels: chore

#511 Add imports_info route
  modules/EventEmitter.js
  ot-node.js
Labels: enhancement

#512 Implement basic auth token
  .env.example
  modules/Utilities.js
  ot-node.js
  seeders/20180407124949-node-config.js
  test/modules/utilities.test.js
Labels: enhancement

#513 Stable version update to 1.3.20
  .env.example
  modules/EventEmitter.js
  modules/Utilities.js
  ot-node.js
  package-lock.json
  package.json
  seeders/20180407124949-node-config.js
  test/modules/utilities.test.js
Labels: chore

#517 Stable version v1.3.21
  package-lock.json
  package.json
Labels: chore
