Repository OriginTrail/ot-node, pull requests merged in 2018-11, with the labels that each got.

#660 Hub smart contract cleanup
  modules/Blockchain/Ethereum/abi/holding-storage.json
  modules/Blockchain/Ethereum/abi/hub.json
  modules/Blockchain/Ethereum/abi/profile-storage.json
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/contracts/Hub.sol
  modules/Blockchain/Ethereum/contracts/ProfileStorage.sol
Labels: internal process

#663 Withdrawal fix
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/command/common/token-withdrawal-command.js
  modules/service/dh-service.js
Labels: bug

#662 Remove cleanup temporarily
  modules/service/replication-service.js
Labels: bug

#667 Node info route
  modules/EventEmitter.js
  ot-node.js
Labels: enhancement

#666 Use more difficulty in Identities and network communication
  config/config.json
  modules/network/kademlia/kademlia-utils.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/workers/identity.js
  modules/network/kademlia/workers/solver.js
  scripts/identity-cli.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/utilities.test.js
Labels: enhancement

#669 Payout on offer complete
  migrations/20180420095258-create-bids.js
  models/bids.js
  modules/command/common/pay-out-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/service/dh-service.js
  modules/service/profile-service.js
  ot-node.js
Labels: bug, enhancement

#668 Hasten truffle tests
  modules/Blockchain/Ethereum/contracts/Hub.sol
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/test/profile.test.js
Labels: internal process

#671 Handle non existing replications
  modules/command/dc/dc-replication-request-command.js
Labels: bug

#673 Deposit tokens fix
  config/config.json
  modules/service/dh-service.js
Labels: bug

#672 Fix checking for signature during read
  modules/Utilities.js
Labels: bug

#677 Adding bdd scenario for token withdrawal endpoint
  modules/command/common/token-withdrawal-command.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: enhancement

#678 Fix encryption
  modules/Encryption.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
Labels: bug

#679 Reconnect join
  modules/network/kademlia/kademlia.js
Labels: bug

#680 Resolves "Failed to create edge with non-existent vertex" [#160128043]
  importers/xml_examples/Retail_with_aggregation/02_Green_to_pink_shipment.xml
  importers/xml_examples/Retail_with_aggregation/03_Green_to_pink_receipt.xml
  package.json
Labels: bug

#683 Bugfix/api data
  modules/Database/Arangojs.js
  modules/Database/graph-converter.js
  modules/ImportUtilities.js
  modules/Product.js
  modules/service/dh-service.js
Labels: bug

#685 Enable bugsnag in command executor
  modules/command/command-executor.js
Labels: chore

#687 Deposit API route
  modules/command/common/deposit-tokens-command.js
  modules/command/common/profile-approval-increase-command.js
  modules/service/profile-service.js
Labels: bug

#686 Polish identity script
  package.json
  scripts/identity-cli.js
Labels: enhancement

#684 Do not call faucet anymore
  testnet/register-node.js
Labels: enhancement

#688 Pirot catchup
  package.json
  scripts/identity-cli.js
  testnet/register-node.js
Labels: chore

#689 New contracts
  config/config.json
Labels: chore

#690 Fix wallet validation
  testnet/register-node.js
Labels: bug

#691 Update prices
  config/config.json
Labels: chore

#692 Info log level
  modules/Utilities.js
Labels: chore

#695 Retry deposit command
  modules/command/common/deposit-tokens-command.js
Labels: bug

#699 Read/purchase fixes and tests
  modules/EventEmitter.js
  modules/command/dv/dv-data-location-response-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/service/dh-service.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: bug, chore, internal process

#702 Adding bdd scenario for /api/deposit endpoint
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: enhancement

#701 Fix command deadlines
  modules/command/common/token-withdrawal-start-command.js
  modules/command/dh/dh-replication-import-command.js
Labels: bug

#704 Check for funds (deposit)
  modules/service/dh-service.js
Labels: chore

#705 Transaction hash
  migrations/20180407120531-create-data-info.js
  migrations/20180407123625-create-holding-data.js
  migrations/20180420094832-create-offers.js
  migrations/201807132331112-create-purchased-data.js
  models/data_info.js
  models/holding_data.js
  models/offers.js
  models/purchased_data.js
  modules/DVService.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-replication-request-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  test/bdd/steps/network.js
Labels: bug

#700 Update default Arango pass in prod environment
  config/config.json
Labels: bug

#706 Add realistic gas price in config file
  config/config.json
Labels: minor

#711 Refactoring bdd scenario "Smoke check data-layer basic endpoints"
  modules/EventEmitter.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/network.js
Labels: enhancement

#712 Fix excluded DHs
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
Labels: bug

#710 New environment
  Dockerfile.mariner
  config/config.json
  modules/Blockchain/Ethereum/index.js
  ot-node.js
  scripts/setup.js
  testnet/register-node.js
Labels: chore, internal process

#715 Fix DC/DH db query
  modules/command/dh/dh-data-read-request-free-command.js
Labels: bug

#717 Logger refactor
  .dockerignore
  check-updates.js
  modules/Blockchain/Ethereum/Transactions.js
  modules/Blockchain/Ethereum/signing.js
  modules/Challenge.js
  modules/Update.js
  modules/Utilities.js
  modules/logger.js
  ot-node.js
  package-lock.json
  package.json
  test/api/zkGetTrail.test.js
  test/modules/command/dc/dc-offer-create-blockchain-command.test.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/gs1-importer.test.js
  test/modules/neo4j.test.js
  test/modules/peercache.test.js
  test/modules/transport.test.js
  test/modules/wot-importer.test.js
  test/protocol/protocol.test.js
  testnet/papertrail.yml
Labels: chore, enhancement

#716 Fix/remove duplicate endpoint & impl BDD DV direct purchase from DC
  modules/EventEmitter.js
  ot-node.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: chore

#720 Fix Awilix container
  ot-node.js
Labels: bug

#719 Update Postman collection for OT v2 API endpoints [Delivers #161744642]
  postman/OriginTrail.postman_collection.json
  postman/ot-env.postman_environment.json
Labels: chore

#722 Fix whitelisting
  modules/utility/api-utilities.js
  package-lock.json
  package.json
  test/bdd/steps/network.js
Labels: bug

#723 Increase hashcash complexity to 20 for non-devevelopment environment
  config/config.json
Labels: chore

#721 Environment cleanup
  config/config.json
  modules/network/kademlia/kademlia.js
  package-lock.json
  scripts/identity-cli.js
Labels: bug, chore

#724 Use Kadence v4.4.0
  package-lock.json
  package.json
Labels: chore

#727 Use Hascash for replication request and extend window time
  config/config.json
  modules/network/kademlia/kademlia.js
Labels: bug, chore

#731 Network identification update (part of #161808122 and #159885778)
  config/config.json
  modules/Utilities.js
  modules/network/kademlia/kademlia-utils.js
  modules/network/kademlia/kademlia.js
  package-lock.json
  package.json
  test/modules/utilities.test.js
  testnet/register-node.js
Labels: bug, enhancement

#733 Fix for autoupdate (#161948658)
  check-updates.js
Labels: bug

#734 Reduce prices for staging env
  config/config.json
Labels: chore

#736 Change app name to origintrail_node
  .dockerignore
  .origintrail_noderc.travis
  .travis.yml
  Dockerfile
  Dockerfile.development
  Dockerfile.mariner
  Dockerfile.stable
  Dockerfile.staging
  package-lock.json
  package.json
Labels: breaking change, bug, chore

#732 Scenario for two purchases: 1st DV from DC, then 2nd DV from 1st DV
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/steps/network.js
Labels: enhancement

#735 Kademlia response reuse
  modules/EventEmitter.js
  modules/command/dc/dc-replication-request-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  modules/service/dh-service.js
Labels: enhancement

#737 Do not persist config data
  ot-node.js
  scripts/setup.js
  testnet/register-node.js
Labels: chore

#740 Fix replication handling
  modules/command/dh/dh-offer-handle-command.js
Labels: bug

#739 API authorization
  modules/EventEmitter.js
  modules/controller/dc-controller.js
  modules/controller/import-controller.js
  modules/utility/api-utilities.js
  ot-node.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: bug, chore

#743 Fix logging levels
  modules/logger.js
Labels: bug, chore

#748 Import whitelist fix for docker
  package-lock.json
  package.json
  testnet/register-node.js
Labels: bug, hotfix

#749 Import whitelist fix
  package-lock.json
  package.json
  testnet/register-node.js
Labels: bug

#750 Fix potential crash during registration
  testnet/register-node.js
Labels: bug

#753 Suppress invalid output and validate wallet
  testnet/register-node.js
Labels: bug, hotfix

#752 Fix arangodb default password issue (#162153884)
  Dockerfile
  Dockerfile.development
  Dockerfile.mariner
  Dockerfile.stable
  Dockerfile.staging
  config/config.json
Labels: bug, hotfix

#754 Pin truffle version to 5.0.0-beta.1
  .travis.yml
Labels: bug, internal process, minor

#746 Minor cleanup of incorrect statements and files
  .env.example
  README.md
  install-aws.sh
  install.sh
  isStartHealthy.js
Labels: internal process, minor

#758 Update stable environment
  config/config.json
Labels: chore

#756 Test/identifiers test
  modules/EventEmitter.js
  modules/GS1Importer.js
  modules/errors/importer-error.js
  modules/errors/index.js
  modules/importer.js
  test/modules/gs1-importer.test.js
  test/modules/test_xml/DoubleEventId.xml
  test/modules/test_xml/MultipleIdentifiers.xml
Labels: internal process

#759 Data layer robustness test cases: Scenario I and II (#162083739)
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/network.feature
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
Labels: enhancement

#760 Fix potential error when creating profile and identity is provided (#162238556)
  modules/service/profile-service.js
  test/bdd/features/erc725profile.feature
  test/bdd/steps/erc725identity.js
  test/bdd/steps/hooks.js
  test/bdd/steps/lib/local-blockchain.js
Labels: bug, chore

#742 Setup S3 artifact upload for TravisCI (#161173220)
  .travis.yml
  test/bdd/steps/hooks.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: internal process

#747 Add npm script for instancing ganache with tenderly
  modules/Blockchain/Ethereum/contracts/Profile.sol
  package.json
Labels: enhancement

#761 Data layer robustness scenarios III and X (#162083739)
  test/bdd/features/datalayer.feature
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
Labels: enhancement
