Repository OriginTrail/ot-node, pull requests merged in 2018-12, with the labels that each got.

#766 Handle publish errors (#162268768)
  .travis.yml
  modules/GS1Importer.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/network/kademlia/kademlia.js
  package.json
  test/bdd/features/protocol-issues.feature
  test/bdd/steps/hooks.js
  test/bdd/steps/network.js
Labels: bug, hotfix

#768 Change DC holding time param
  config/config.json
Labels: chore

#767 Scenario VII - private data (#162083739)
  test/bdd/features/datalayer.feature
  test/bdd/steps/datalayer.js
  test/modules/test_xml/GraphExample_1.xml
Labels: enhancement

#770 Split running BDD tests. Workaround for #162378577
  .travis.yml
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/erc725profile.feature
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/features/protocol-issues.feature
Labels: enhancement, internal process

#773 Bootstrap basic API
  modules/EventEmitter.js
  modules/RemoteControl.js
  modules/network/kademlia/kademlia.js
  modules/service/rest-api-service.js
  ot-node.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/network.js
Labels: chore, enhancement

#772 Scenario XI and Scenario IV (#162083739)
  .travis.yml
  importers/xml_examples/Basic/01_Green_to_pink_shipment_modified_event_timestamp.xml
  test/bdd/features/datalayer.feature
  test/bdd/features/endpoints.feature
  test/bdd/features/network.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
Labels: enhancement

#776 Remove unnecessary logs
  modules/command/dh/dh-data-read-request-free-command.js
Labels: chore

#780 Fix data read query
  modules/Database/Arangojs.js
Labels: bug

#782 Remove funds check for free read
  modules/EventEmitter.js
Labels: bug

#774 Minor: Run BDD tests also on cron job trigger
  .travis.yml
Labels: internal process

#775 Minor: Remove not maintained changelog.md file
  CHANGELOG.md
Labels: internal process

#781 Try to reach the whole routing table when using PUBLISH (#162268768, #162444372)
  modules/network/kademlia/kademlia.js
Labels: bug, hotfix

#783 Fix root hashes [#162263397]
  modules/DVService.js
  modules/GS1Importer.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/importer.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/network.js
Labels: bug

#779 Bugfix/data layer fixes
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/GS1Importer.js
  ot-node.js
  test/api/zkGetTrail.test.js
Labels: bug

#778 Feature/zk private setup
  modules/ZK.js
  test/bdd/steps/datalayer.js
Labels: enhancement

#784 Disable Hashcash for PUBLISH/SUBSCRIBE. Collect responses after publish.
  config/config.json
  modules/EventEmitter.js
  modules/command/dv/dv-query-network-command.js
  modules/network/kademlia/kademlia.js
Labels: bug, hotfix

#786 Corrupted class vertices [#162471354]
  modules/Database/Arangojs.js
  modules/Database/graph-converter.js
  modules/importer.js
Labels: bug

#785 Profile contract cleanup
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/Ethereum/test/profile.test.js
Labels: bug, internal process, minor

#777 Require nodeID and enable nodeID change
  modules/Blockchain/Ethereum/abi/profile.json
  modules/Blockchain/Ethereum/contracts/Profile.sol
Labels: enhancement, minor

#788 Handle failed finalize offer
  modules/command/dc/dc-offer-finalize-command.js
Labels: bug

#791 develop-master sync
  modules/Blockchain/Ethereum/abi/profile.json
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/Ethereum/test/profile.test.js
  modules/Database/Arangojs.js
  modules/GS1Importer.js
  modules/command/dc/dc-offer-finalize-command.js
  package-lock.json
  package.json
Labels: bug, enhancement, internal process

#792 develop-mariner sync
  modules/Blockchain/Ethereum/abi/profile.json
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/Ethereum/test/profile.test.js
  modules/Database/Arangojs.js
  modules/GS1Importer.js
  modules/command/dc/dc-offer-finalize-command.js
  package-lock.json
  package.json
Labels: bug, hotfix

#793 Update config
  config/config.json
Labels: hotfix

#794 Bump version
  package-lock.json
  package.json
Labels: chore

#795 develop-master sync
  config/config.json
  package-lock.json
  package.json
Labels: chore

#796 Update config
  config/config.json
  package-lock.json
  package.json
Labels: chore

#797 develop-master sync
  config/config.json
  package-lock.json
  package.json
Labels: hotfix

#798 Scenario 12- Remote event connection on DV side (#162083739)
  test/bdd/features/datalayer.feature
  test/bdd/features/network.feature
  test/bdd/features/protocol-issues.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
Labels: enhancement

#800 Scenario 8 and 9 (#162083739)
  test/bdd/features/datalayer.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
Labels: chore, enhancement

#787 Adding /api/info endpoint to Postman collection
  postman/OriginTrail.postman_collection.json
Labels: chore

#799 Fix delay for big numbers [#162540108]
  modules/command/command-executor.js
Labels: bug

#802 Added /api/balance, deposit-on-demand, turned off, cleaner set to 4 days
  config/config.json
  modules/Utilities.js
  modules/command/common/cleaner-command.js
  modules/service/rest-api-service.js
Labels: bug, hotfix

#806 One time payout migration
  modules/migration/m1-payout-all-migration.js
  ot-node.js
Labels: hotfix

#807 Disable deposit and withdrawal
  config/config.json
  modules/Blockchain/Ethereum/test/profile.test.js
  modules/DVService.js
  modules/EventEmitter.js
  modules/command/common/deposit-tokens-command.js
  modules/command/common/profile-approval-increase-command.js
  modules/command/common/token-withdrawal-command.js
  modules/command/common/token-withdrawal-start-command.js
  modules/command/common/token-withdrawal-wait-started-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/profile-service.js
  modules/service/rest-api-service.js
  test/bdd/features/endpoints.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/network.js
  test/protocol/protocol.test.js
Labels: hotfix

#808 Funds-check cleanup
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  ot-node.js
Labels: bug, enhancement

#809 Update ERC725 identity to support management wallet
  config/config.json
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/profile.json
  modules/Blockchain/Ethereum/contracts/ByteArr.sol
  modules/Blockchain/Ethereum/contracts/Identity.sol
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/Ethereum/test/profile.test.js
  modules/DVService.js
  modules/EventEmitter.js
  modules/command/common/deposit-tokens-command.js
  modules/command/common/profile-approval-increase-command.js
  modules/command/common/token-withdrawal-command.js
  modules/command/common/token-withdrawal-start-command.js
  modules/command/common/token-withdrawal-wait-started-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/migration/m1-payout-all-migration.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/profile-service.js
  modules/service/rest-api-service.js
  ot-node.js
  test/bdd/features/endpoints.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/network.js
  test/protocol/protocol.test.js
Labels: breaking change, enhancement, hotfix

#811 Identity update
  modules/Blockchain/Ethereum/abi/erc725.json
  modules/Blockchain/Ethereum/contracts/ERC725.sol
  modules/Blockchain/Ethereum/contracts/Identity.sol
  modules/Blockchain/Ethereum/index.js
  modules/service/dc-service.js
Labels: hotfix

#813 Cover reputation and withdrawals in transferProfile function
  modules/Blockchain/Ethereum/contracts/Profile.sol
Labels: enhancement, hotfix

#814 Run payout
  modules/migration/m1-payout-all-migration.js
  ot-node.js
Labels: hotfix

#816 Require management wallet
  modules/Blockchain/Ethereum/contracts/Profile.sol
  ot-node.js
  test/bdd/steps/erc725identity.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/network.js
  testnet/supervisord.conf
Labels: chore

#818 Multiple payOut function
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/test/offer.test.js
Labels: enhancement

#819 Change log message
  modules/migration/m1-payout-all-migration.js
Labels: chore

#820 Update ABI files
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/abi/profile.json
  modules/Blockchain/Ethereum/index.js
Labels: hotfix, internal process

#821 Change gas amount in truffle tests
  modules/Blockchain/Ethereum/test/offer.test.js
Labels: chore, minor

#823 Migration batches
  modules/migration/m1-payout-all-migration.js
Labels: bug

#824 Fix lint in truffle tests
  modules/Blockchain/Ethereum/test/offer.test.js
Labels: internal process, minor

#822 Exit from docker in case of common errors
  modules/service/profile-service.js
  testnet/supervisord.conf
Labels: bug, chore

#825 Enable withdraw while completing new offers
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/test/profile.test.js
  modules/Blockchain/Ethereum/truffle.js
Labels: enhancement

#826 Do not check for permissions for management wallet
  modules/service/profile-service.js
Labels: chore

#827 Add management key in profile transfer
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/profile.json
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/index.js
  modules/service/profile-service.js
Labels: chore, internal process

#828 Add PaidOut event to holding contract
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/contracts/Holding.sol
Labels: internal process, minor

#830 Change supervisor exit code
  modules/command/command-executor.js
  testnet/supervisord.conf
Labels: bug

#833 Impl BDD scenario for dh-pay-out scenario (#162658522)
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: enhancement

#805 Basic automated integration test for docker images (#162263163)
  .origintrail_noderc.image
  .travis.yml
  package.json
  test/docker/check_image.sh
  test/docker/cleanup_image.sh
  test/docker/getHubAddress.js
Labels: enhancement

#834 Enable entire balance withdrawal
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/test/profile.test.js
Labels: bug, hotfix
