Repository OriginTrail/ot-node, pull requests merged in 2018-10, with the labels that each got.

#595 Fix for TypeError in /ot-node/modules/Challenger.js:165 [#160790789]
  modules/Challenger.js
Labels: minor

#596 Refactor npm test scripts and add test debug scripts
  package.json
Labels: minor

#597 Master catchup
  modules/Blockchain/Ethereum/escrow-contract/abi.json
  modules/DataReplication.js
  modules/Database/Arangojs.js
  modules/EventEmitter.js
  modules/GS1Utilities.js
  modules/Utilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-offer-handle-import-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-location-response-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/controller/dc-controller.js
  modules/controller/dh-controller.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  package-lock.json
  package.json
Labels: chore

#600 Trim edge imports
  modules/DHService.js
  modules/EventEmitter.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/importer.js
Labels: bug, hotfix

#598 Trim edge imports [#160916532]
  modules/DHService.js
  modules/EventEmitter.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/importer.js
Labels: bug

#601 Master catchup
  modules/Utilities.js
  package-lock.json
  package.json
Labels: chore

#602 Removing some obsolete code
  .travis.yml
  package.json
  switchDatabase.js
Labels: minor

#564 Proof of work [#160646831]
  modules/Miner.js
  test/modules/miner.test.js
Labels: enhancement

#588 Feature/message signing [#160815848]
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/truffle.js
  modules/Encryption.js
  package-lock.json
  package.json
Labels: enhancement

#604 adding more xmls to be checked
  test/modules/gs1-importer.test.js
Labels: minor

#605 Smart contracts for Pirot protocol [#160894245]
  modules/Blockchain/Ethereum/contracts/ByteArr.sol
  modules/Blockchain/Ethereum/contracts/ERC725.sol
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/contracts/Hub.sol
  modules/Blockchain/Ethereum/contracts/Identity.sol
  modules/Blockchain/Ethereum/contracts/Migrations.sol
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/contracts/ProfileStorage.sol
  modules/Blockchain/Ethereum/contracts/Reading.sol
  modules/Blockchain/Ethereum/contracts/SafeMath.sol
  modules/Blockchain/Ethereum/contracts/TestingUtilities.sol
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/test/bidding.test.js
  modules/Blockchain/Ethereum/test/deployment.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/Ethereum/truffle.js
  package.json
Labels: enhancement

#607 Relates to #161048915: Double check Mandatory/Optional tags in xmls
  importers/xml_examples/Retail/01_Green_to_pink_shipment.xml
  importers/xml_examples/Retail/02_Green_to_Pink_receipt.xml
  importers/xml_examples/Retail/03_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail/04_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail/05_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail/06_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_Zk/01_Green_to_pink_shipment.xml
  importers/xml_examples/Retail_with_Zk/02_Green_to_Pink_receipt.xml
  importers/xml_examples/Retail_with_Zk/03_Pink_ZKN_Transform.xml
  importers/xml_examples/Retail_with_Zk/04_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail_with_Zk/05_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail_with_Zk/06_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail_with_Zk/07_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_aggregation/01_Green_packing.xml
  importers/xml_examples/Retail_with_aggregation/02_Green_to_pink_shipment.xml
  importers/xml_examples/Retail_with_aggregation/03_Green_to_pink_receipt.xml
  importers/xml_examples/Retail_with_aggregation/04_Pink_to_orange_shipment.xml
  importers/xml_examples/Retail_with_aggregation/05_Pink_to_orange_receipt.xml
  importers/xml_examples/Retail_with_aggregation/06_Orange_unpacking.xml
  importers/xml_examples/Retail_with_aggregation/07_Orange_unpacking_all.xml
  test/modules/test_xml/GraphExample_1.xml
  test/modules/test_xml/GraphExample_2.xml
  test/modules/test_xml/GraphExample_3.xml
  test/modules/test_xml/GraphExample_4.xml
  test/modules/test_xml/Transformation.xml
  test/modules/test_xml/ZKExample.xml
Labels: chore

#610 Bugfix/pow solution
  modules/miner.js
  test/modules/miner.test.js
Labels: bug

#612 Base for BDD tests (#157395052)
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  modules/Utilities.js
  package-lock.json
  package.json
  scripts/identity-cli.js
  test/bdd/features/network.feature
  test/bdd/steps/blockchain.js
  test/bdd/steps/hooks.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: internal process

#614 Expand bdd steps after() hook [Relates to #157395052]
  test/bdd/steps/hooks.js
Labels: internal process, minor

#613 Adding bdd test for "Import hash should remain constant despite additional adjacent imports" [#160987910]
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: enhancement

#620 Simple replications cache [#161343567]
  modules/command/common/deposit-tokens-command.js
  modules/command/common/profile-approval-increase-command.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dc/dc-replication-request-command.js
  modules/service/replication-service.js
Labels: enhancement

#623 SC/OT-node padding issue [#161407626]
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/Utilities.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/service/dh-service.js
  modules/service/profile-service.js
Labels: bug

#619 Move checking balances to blockchain layer
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/service/profile-service.js
  ot-node.js
Labels: enhancement

#624 Fix network's 'Timed out waiting for response'
  config/runtimeConfig.json
  modules/EventEmitter.js
  modules/Utilities.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/logger.js
  modules/network/transport.js
  ot-node.js
  package-lock.json
  package.json
  setup_arangodb.sh
Labels: enhancement

#626 New bootstrap
  config/config.json
Labels: enhancement

#628 Enable pirot smart contract deployment on rinkeby
  package.json
Labels: minor

#627 Fix for network timed outs
  modules/EventEmitter.js
  modules/Utilities.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/logger.js
  modules/network/transport.js
  ot-node.js
  package-lock.json
  package.json
  setup_arangodb.sh
Labels: bug

#625 Enable bdd setup and 1st Scenario with Pirot
  config/config.json
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/network/kademlia/kademlia.js
  package.json
  test/bdd/features/network.feature
  test/bdd/steps/blockchain.js
  test/bdd/steps/hooks.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/network.js
  test/modules/utilities.test.js
Labels: enhancement

#633 Basic Hyperledger fingerprinting
  config/config.json
  modules/Blockchain.js
  modules/Blockchain/plugin/abstract-plugin.js
  modules/Blockchain/plugin/blockchain-plugin-service.js
  modules/Blockchain/plugin/hyperledger/hyperledger-fingerprint-plugin.js
  modules/command/dc/dc-offer-create-bc-command.js
  ot-node.js
  package.json
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/utilities.test.js
Labels: enhancement

#635 Data layer 2.0
  modules/Blockchain/Ethereum/Transactions.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/Database/graph-converter.js
  modules/EventEmitter.js
  modules/GS1Importer.js
  modules/GS1Utilities.js
  modules/ImportUtilities.js
  modules/Product.js
  modules/ZK.js
  modules/command/dh/dh-replication-import-command.js
  modules/importer.js
  modules/service/dh-service.js
  test/protocol/protocol.test.js
Labels: enhancement

#638 Pirot API fixes
  modules/EventEmitter.js
  modules/controller/import-controller.js
Labels: bug

#637 Fix race condition on OT-node start [#161506501]
  modules/Blockchain/Ethereum/index.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  modules/service/profile-service.js
  ot-node.js
Labels: bug

#640 Handle invalid datasets ids input in scope of replication
  modules/EventEmitter.js
  modules/controller/dc-controller.js
Labels: bug

#642 Feature/bdd replication
  modules/EventEmitter.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-offer-finalized-command.js
  test/bdd/features/network.feature
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: chore

#645 Prevent using null contact in communication
  modules/network/kademlia/kademlia.js
Labels: bug

#646 Token deposit API fix [#161546684]
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/service/profile-service.js
Labels: bug

#648 Fix getting replicated data
  modules/EventEmitter.js
  modules/service/dh-service.js
Labels: bug

#647 Fix replication/offer IDs [#161544500]
  modules/EventEmitter.js
  ot-node.js
  test/bdd/steps/network.js
Labels: bug

#654 Profile creation [#161624891]
  modules/Blockchain.js
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/service/profile-service.js
Labels: bug

#655 Deposit approval
  modules/service/profile-service.js
Labels: bug

#656 Enable changing minimalStake and withdrawalTime in Profile SC
  modules/Blockchain/Ethereum/contracts/Profile.sol
Labels: minor

#621 Feature/pirot contract test
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/test/holding.storage.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/Ethereum/test/profile.storage.test.js
  modules/Blockchain/Ethereum/test/profile.test.js
Labels: enhancement
