Repository OriginTrail/ot-node, pull requests merged in 2018-07, with the labels that each got.

#404 Removing .only()
  test/modules/utilities.test.js
Labels: minor

#403 Base for protocol testing
  modules/Blockchain/Ethereum/index.js
  modules/DCService.js
  package.json
  test/protocol/protocol.test.js
Labels: enhancement

#405 Feed exception and crash logs to PaperTrail
  testnet/papertrail.yml
  testnet/supervisord.conf
Labels: enhancement

#397 Improve createOffer() log
  modules/Blockchain/Ethereum/index.js
Labels: minor

#406 Deposit and withdraw
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/ProfileService.js
  modules/RemoteControl.js
  ot-node.js
Labels: enhancement

#407 Feed exception and crash-like logs to Loggly
  modules/Blockchain/Ethereum/index.js
  ot-node.js
Labels: enhancement

#408 Latest staging changes
  .env.example
  .env.travis
  migrations/20180407120531-create-data-info.js
  migrations/20180411095437-create-data-challenges.js
  migrations/20180713230500-add-columns.js
  modules/Network.js
  modules/kademlia/KademliaUtils.js
  ot-node.js
  seeders/20180407124949-node-config.js
  test/modules/utilities.test.js
  testnet/register-node.js
Labels: minor

#409 Invalid XML event prefixes
  importers/xml_examples/Retail/02_Green_to_Pink_receipt.xml
  importers/xml_examples/Retail/03_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail/04_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail/05_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail/06_Pink_to_Red_receipt.xml
  importers/xml_examples/Retail_with_Zk/02_Green_to_Pink_receipt.xml
  importers/xml_examples/Retail_with_Zk/04_Pink_to_Orange_shipment.xml
  importers/xml_examples/Retail_with_Zk/05_Pink_to_Orange_receipt.xml
  importers/xml_examples/Retail_with_Zk/06_Pink_to_Red_shipment.xml
  importers/xml_examples/Retail_with_Zk/07_Pink_to_Red_receipt.xml
Labels: bug

#410 Reverse tunnel strategy configuration
  modules/Network.js
Labels: chore

#412 Add protocol tests only command [Delivers #158797047]
  package.json
Labels: minor
