Repository OriginTrail/ot-node, pull requests merged in 2019-07, with the labels that each got.

#945 Optimize event connection query
  modules/Database/Arangojs.js
  package-lock.json
  package.json
Labels: bug, minor, release

#946 2.0.57
  modules/Database/Arangojs.js
  package-lock.json
  package.json
Labels: bug, minor, release

#949 2.0.58
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  modules/service/dh-service.js
  ot-node.js
  package-lock.json
  package.json
Labels: enhancement, release

#950 2.0.58
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  modules/service/dh-service.js
  ot-node.js
  package-lock.json
  package.json
Labels: minor, release

#951 Reduce blockchain requests
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  modules/service/dh-service.js
  ot-node.js
  package-lock.json
  package.json
Labels: hotfix

#953 Testnet Prerelease 3.0.8
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  modules/command/dh/dh-replacement-handle-command.js
  modules/service/dh-service.js
  ot-node.js
  package-lock.json
  package.json
  setup_arangodb.sh
  test/bdd/features/litigation.feature
  testnet/install-arango.sh
Labels: hotfix, release
