Repository OriginTrail/ot-node, pull requests merged in 2019-09, with the labels that each got.

#967 Non blocking import
  modules/EventEmitter.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/service/rest-api-v2.js
Labels: enhancement

#968 Bugfix/gs1 import
  modules/importer/ot-json-importer.js
  modules/service/rest-api-controller.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  ot-node.js
Labels: bug

#962 Graph storage DL2
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/importer/wot-importer.js
  test/modules/graphstorage.test.js
  test/modules/wot-importer.test.js
Labels: enhancement

#970 Implement dynamic gas price calculation
  config/config.json
  migrations/201909241420156-offer-add-urgent.js
  models/offers.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/import-controller.js
  modules/service/axios-service.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/gas-price-service.js
  modules/service/profile-service.js
  ot-node.js
  package-lock.json
  package.json
  test/modules/service/gas-price-service-test.js
  test/modules/utilities.test.js
Labels: enhancement, hotfix
