Repository OriginTrail/ot-node, pull requests merged in 2019-12, with the labels that each got.

#1039 [BugFix] Trail Validation
  modules/service/import-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
Labels: bug

#1040 Feature/add new node configuration params
  config/config.json
  migrations/201911291255243-offer-add-urgent.js
  models/offers.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/gas-station-service.js
  modules/service/pricing-service.js
  modules/service/profile-service.js
  modules/service/rest-api-v2.js
  modules/service/trac-price-service.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/service/pricing-service-test.js
  test/modules/utilities.test.js
Labels: enhancement

#1041 Add migration for node update
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/old-holding.json
  modules/Blockchain/Ethereum/index.js
  modules/migration/m1-payout-all-migration.js
  ot-node.js
Labels: internal process, minor

#1042 Better logging messages for unanswered challenges and initiating litigation
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-litigation-initiate-command.js
Labels: chore, minor

#1043 Fixed setNodeId identity hex
  ot-node.js
Labels: bug

#1037 Validate DL2 Acceptance Criteria
  importers/use_cases/OBE/CARTONDATA.xml
  importers/use_cases/OBE/ORDER100678.xml
  importers/use_cases/OBE/ORDER100679.xml
  importers/use_cases/ZK/03_Pink_ZKN_Transform.xml
  importers/use_cases/certs/0FID_company-red_company-red.xml
  importers/use_cases/certs/halal.jpg
  modules/Database/Arangojs.js
  modules/service/challenge-service.js
  modules/service/rest-api-controller.js
  test/bdd/features/datalayer.feature
  test/bdd/features/endpoints.feature
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/features/protocol-issues.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
Labels: chore, enhancement

#1044 Feature/Trail & Kademlia Validation
  modules/Database/Arangojs.js
  modules/network/kademlia/kademlia.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  test/api/zkGetTrail.test.js
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
Labels: enhancement

#1046 Zero Knowledge Validation
  test/bdd/features/endpoints.feature
  test/bdd/steps/datalayer.js
  test/modules/test_xml/Transformation.xml
Labels: enhancement

#1049 Trail proof validation refactor
  modules/Merkle.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/utilities.js
Labels: minor

#1051 Standardize migrations
  modules/migration/m3-network-identity-migration.js
  modules/migration/m4-arango-migration.js
  ot-node.js
Labels: enhancement

#1055 Updated configuration to use only development/mainnet/testnet env var…
  Dockerfile.mainnet
  Dockerfile.mariner
  Dockerfile.stable
  Dockerfile.testnet
  config/config.json
  config/sequelizeConfig.js
  models/index.js
  modules/Utilities.js
  modules/service/pricing-service.js
  modules/service/trac-price-service.js
  ot-node.js
  scripts/backup.js
  scripts/restore.js
  scripts/setup.js
  test/modules/service/pricing-service-test.js
  test/modules/utilities.test.js
Labels: chore

#1063 Convert gasLimit to hex for payOutMutiple
  modules/Blockchain/Ethereum/index.js
Labels: minor

#1066 Changed logging for network query
  modules/controller/dv-controller.js
  modules/service/rest-api-v2.js
Labels: chore

#1057 hotfix/export-request
  modules/service/rest-api-v2.js
Labels: bug

#1059 Issuer Identity BDD Test
  test/bdd/features/importer.feature
Labels: hotfix, minor

#1067 Updated price factor calculation - added new configuration params
  config/config.json
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  test/modules/service/pricing-service-test.js
  test/modules/utilities.test.js
Labels: bug

#1058 Standardize migrations for update
  modules/Blockchain/Ethereum/contracts/OldHub.sol
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/truffle.js
Labels: internal process

#1069 BugFix Graph Import
  modules/command/dc/dc-convert-to-ot-json-command.js
Labels: bug

#1070 BugFix Connectors Check
  modules/Database/GraphStorage.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/service/import-service.js
  package.json
Labels: bug

#1071 BugFix - Import File
  modules/ImportUtilities.js
  modules/worker/graph-converter-worker.js
  modules/worker/import-worker-controller.js
  modules/worker/otjson-converter-worker.js
  test/bdd/steps/lib/utilities.js
Labels: bug, minor

#1075 Dataset info wallet
  modules/service/rest-api-v2.js
Labels: internal process

#1076 BugFix Import File
  modules/command/dc/dc-convert-to-ot-json-command.js
Labels: bug

#1074 Feature Heap Size Fix
  package.json
  testnet/supervisord.conf
Labels: hotfix, internal process

#1081 Fix missing properties in for connector relations
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  package-lock.json
  package.json
Labels: bug

#1082 Bugfix: Parse Kademlia contact
  modules/network/kademlia/kademlia.js
Labels: bug

#1083 Add bugfixes for connectors and kademlia
  modules/network/kademlia/kademlia.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  package-lock.json
  package.json
Labels: bug

#1084 auth_token moved to request header
  modules/api-utilities.js
Labels: chore, minor

#1096 Add challenge retry and delay on failed send
  config/config.json
  modules/RemoteControl.js
  modules/command/command-executor.js
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-challenges-command.js
  modules/command/dh/dh-challenge-command.js
  modules/service/dh-service.js
  test/modules/utilities.test.js
Labels: internal process

#1095 Pricing bug fix and version update to 4.0.0
  config/config.json
  modules/RemoteControl.js
  modules/command/command-executor.js
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-challenges-command.js
  modules/command/dh/dh-challenge-command.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  package.json
  test/modules/utilities.test.js
Labels: bug, chore

#1098 Freedom-Gemini v4.0.0
  config/config.json
  modules/RemoteControl.js
  modules/command/command-executor.js
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-challenges-command.js
  modules/command/dh/dh-challenge-command.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  package.json
  test/modules/utilities.test.js
Labels: release

#1100 Fix migrating persistant old identity file
  modules/migration/m3-network-identity-migration.js
  ot-node.js
Labels: bug

#1113 bugfix/remove-churn-filter-test
  modules/network/kademlia/kademlia.js
  package.json
Labels: internal process

#1112 Improved logging of price calculation.
  modules/logger.js
  modules/service/pricing-service.js
  modules/service/trac-price-service.js
Labels: internal process, minor

#1111 Resolved bug when reseting node causes updating of houston password
  config/config.json
  ot-node.js
  test/modules/utilities.test.js
Labels: bug
