Repository OriginTrail/ot-node, pull requests merged in 2019-04, with the labels that each got.

#910 V3 support for Houston (RFC - Mariner)
  .gitignore
  Dockerfile
  Dockerfile.development
  Dockerfile.mariner
  Dockerfile.stable
  Dockerfile.staging
  check-updates.js
  config/config.json
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/RemoteControl.js
  modules/Utilities.js
  modules/command/command-executor.js
  modules/command/common/autoupdater-command.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/service/dh-service.js
  ot-node.js
  package-lock.json
  package.json
  test/docker/check_image.sh
  test/modules/command/common/autoupdater-command.test.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/utilities.test.js
  testnet/prepare-update.js
  testnet/register-node.js
  testnet/start.sh
  testnet/supervisor-event-listener.py
  testnet/supervisord.conf
Labels: enhancement

#913 Increase autoupdate command period [OT-I499]
  modules/command/common/autoupdater-command.js
Labels: chore

#914 Increase autoupdate command period [OT-I499] - Mariner
  modules/command/common/autoupdater-command.js
Labels: chore

#916 New Kadence & update for Hash-cash
  modules/network/kademlia/kademlia.js
  package-lock.json
  package.json
Labels: bug, enhancement

#919 Handle rpc_server_url param in process env
  testnet/register-node.js
Labels: bug

#918 Mariner release v2.0.53
  modules/command/common/autoupdater-command.js
  package-lock.json
  package.json
  testnet/register-node.js
  testnet/supervisor-event-listener.py
Labels: internal process

#924 Fix event listener import
  testnet/supervisor-event-listener.py
Labels: bug, hotfix

#925 Mariner release 2.0.54
  package-lock.json
  package.json
  testnet/supervisor-event-listener.py
Labels: internal process

#926 Testnet Release 3.0.6
  package-lock.json
  package.json
  testnet/supervisor-event-listener.py
Labels: internal process

#931 Update staging contracts
  config/config.json
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/truffle.js
Labels: enhancement

#928 Prevent remote control to crash finalize command
  modules/RemoteControl.js
Labels: bug
