Repository OriginTrail/ot-node, pull requests merged in 2019-02, with the labels that each got.

#837 BDD scenario for management wallet (#162787864)
  test/bdd/features/network.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
Labels: enhancement

#845 Check for transaction prices (#163821652)
  modules/Blockchain/Ethereum/Transactions.js
  test/modules/transactions.test.js
Labels: bug

#846 Litigation tests (#163053659)
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/test/litigation.test.js
  package.json
Labels: chore

#847 Litigation basic BDD test fix (#163907706)
  modules/command/dh/dh-litigation-answer-command.js
  test/bdd/features/litigation.feature
  test/bdd/steps/hooks.js
  test/bdd/steps/litigation.js
Labels: bug, chore

#849 Increase gas
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
Labels: bug

#852 Litigation test case (#163859410)
  .travis.yml
  modules/Blockchain/Ethereum/abi/holding-storage.json
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/abi/hub.json
  modules/Blockchain/Ethereum/abi/litigation-storage.json
  modules/Blockchain/Ethereum/abi/litigation.json
  modules/Blockchain/Ethereum/abi/profile-storage.json
  modules/service/dh-service.js
  package.json
  test/bdd/features/litigation.feature
  test/bdd/steps/litigation.js
Labels: internal process

#851 Reschedule payout command on fail (##163977932)
  modules/EventEmitter.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/service/profile-service.js
Labels: chore, enhancement

#850 Litigation BDD test (#163951020)
  test/bdd/features/litigation.feature
  test/bdd/steps/hooks.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/litigation.js
Labels: chore

#854 Limit log size (#164205277)
  modules/logger.js
  test/bdd/features/litigation.feature
  test/bdd/steps/network.js
Labels: chore

#855 Replace 3 new DHs when DC completes
  modules/Blockchain/Ethereum/test/litigation.test.js
Labels: internal process

#859 Update log in dc-offer-choose-command
  modules/command/dc/dc-offer-choose-command.js
Labels: chore

#856 Change Sequelize table name (#164213345)
  check-updates.js
  modules/migration/m2-sequelize-meta-migration.js
  ot-node.js
Labels: bug
