Repository OriginTrail/ot-node, pull requests merged in 2019-11, with the labels that each got.

#1019 Serialization error fixed, now we are passing only error message when…
  modules/command/dc/dc-convert-to-graph-command.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/worker/import-worker-controller.js
Labels: bug

#1020 Added get dataset info route
  migrations/201910231115243-update-data-info-add-data-hash.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/command/dh/dh-replication-import-command.js
  modules/service/rest-api-v2.js
Labels: chore, enhancement

#1017 Feature/Connectors Validation
  importers/xml_examples/Retail/01_Green_to_pink_shipment.xml
  importers/xml_examples/Retail/02_Green_to_Pink_receipt.xml
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/importer/ot-json-importer.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/worker/graph-converter-worker.js
  test/modules/gs1-importer.test.js
Labels: bug, internal process

#1021 Add API route for connection types
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  ot-node.js
Labels: enhancement, minor

#1024 BugFix/Challenges Sort
  modules/ImportUtilities.js
  modules/command/dh/dh-challenge-command.js
  modules/importer/ot-json-importer.js
  modules/service/challenge-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
Labels: bug

#1022 Implement Trail API route
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/ImportUtilities.js
  modules/Merkle.js
  modules/command/dh/dh-replacement-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/importer/ot-json-importer.js
  modules/mtree.js
  modules/service/challenge-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  test/bdd/features/importer.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/utilities.js
  test/modules/graphstorage.test.js
  test/modules/mtree.test.js
  test/modules/test_data/arangodb-data.js
Labels: enhancement

#1025 Version bump
  package-lock.json
  package.json
Labels: internal process, minor

#1029 Challenge Tests
  test/bdd/features/datalayer.feature
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/challenge.test.js
Labels: chore

#1023 Removed ot-json-importer, import-controller, rest-api-v1
  modules/EventEmitter.js
  modules/command/dc/dc-convert-to-graph-command.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dh/dh-challenge-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/controller/import-controller.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/service/rest-api-controller.js
  modules/service/rest-api-v1.js
  modules/service/rest-api-v2.js
  modules/validator/schema-validator.js
  modules/worker/import-worker-controller.js
  ot-node.js
  test/api/zkGetTrail.test.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/network.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/otjson-importer.test.js
Labels: internal process

#1030 Connectors Test
  importers/use_cases/connectors/01_Green_to_pink_shipment.xml
  importers/use_cases/connectors/02_Green_to_Pink_receipt.xml
  test/bdd/features/importer.feature
Labels: enhancement

#1031 Entity Identifiers Test
  test/bdd/features/importer.feature
  test/bdd/steps/endpoints.js
Labels: enhancement

#1027 Node backup & restore script
  package.json
  scripts/backup.js
  scripts/restore.js
Labels: enhancement

#1032 Added bugsnag reporting if challenges failed
  modules/command/dc/dc-challenge-check-command.js
Labels: internal process, minor

#1033 Network Layer Refactor - Kadence upgrade
  modules/Control.js
  modules/network/kademlia/kademlia-utils.js
  modules/network/kademlia/kademlia.js
  modules/network/kademlia/peer-cache.js
  modules/network/kademlia/workers/challenger.js
  modules/network/kademlia/workers/identity.js
  modules/network/kademlia/workers/solver.js
  package.json
  scripts/identity-cli.js
  test/bdd/steps/network.js
  test/modules/peercache.test.js
Labels: breaking change, chore

#1034 Update get_merkle_proofs API
  modules/ImportUtilities.js
  modules/service/challenge-service.js
  modules/service/import-service.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/network.js
  test/modules/challenge.test.js
Labels: enhancement, minor

#1038 Feature/Litigation Refactor
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/litigation-storage.json
  modules/Blockchain/Ethereum/abi/litigation.json
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/contracts/LitigationStorage.sol
  modules/Blockchain/Ethereum/contracts/MockLitigation.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/test/litigation.test.js
  modules/Blockchain/Ethereum/updateAbi.js
  modules/Merkle.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-litigation-answered-command.js
  modules/command/dc/dc-litigation-complete-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/command/dh/dh-challenge-command.js
  modules/command/dh/dh-litigation-answer-command.js
  modules/command/dh/dh-litigation-initiated-command.js
  modules/service/challenge-service.js
  modules/service/dh-service.js
  test/bdd/features/importer.feature
  test/bdd/features/litigation.feature
  test/bdd/steps/litigation.js
  test/modules/challenge.test.js
  test/modules/mtree.test.js
Labels: chore, enhancement

#1036 Network read/query refactor
  migrations/201911271001123-update-network-query-responses.js
  migrations/201911291043123-update-data-info-remove-data-size.js
  models/data_info.js
  models/network_query_responses.js
  modules/DVService.js
  modules/EventEmitter.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-location-response-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/command/dv/dv-handle-network-query-responses-command.js
  modules/command/dv/dv-query-network-command.js
  modules/controller/dv-controller.js
  modules/service/dh-service.js
  modules/service/rest-api-v2.js
  modules/worker/import-worker-controller.js
  ot-node.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
Labels: enhancement, minor
