Repository OriginTrail/ot-node, pull requests merged in 2019-03, with the labels that each got.

#863 Offer global_status seed [#164240579]
  migrations/201807132344667-seed-offer-global-status.js
Labels: bug

#862 Fix logger in BDD tests [#164301375]
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-offer-replace-command.js
  modules/command/dc/dc-offer-task-command.js
  test/bdd/steps/hooks.js
Labels: bug

#867 Fix for litigation when DH only answer to BC event
  modules/command/dc/dc-litigation-completed-command.js
  test/bdd/features/litigation.feature
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/litigation.js
  test/bdd/steps/network.js
Labels: bug, internal process

#868 Fix holder update [#164363428]
  modules/command/dc/dc-challenges-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-replacement-completed-command.js
Labels: bug

#869 Filter duplicate commands [#164363485]
  modules/command/command-executor.js
Labels: bug

#870 Add migration to rinkeby
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
Labels: internal process

#872 Missing offer_id parameter [#164363428]
  modules/command/dc/dc-offer-replacement-completed-command.js
  modules/service/dc-service.js
Labels: bug

#871 Check replacement parameters [#164205697]
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/command/dc/dc-offer-replacement-completed-command.js
  modules/command/dh/dh-replacement-started-command.js
  modules/service/dh-service.js
Labels: bug

#873 Fix challenges and bids [#164430135, #164430591]
  modules/command/dc/dc-challenges-command.js
  modules/command/dh/dh-replacement-started-command.js
  modules/service/dh-service.js
Labels: bug

#874 Prevent including models and p-iterarion (#164400863)
  migrations/201807132344667-seed-offer-global-status.js
Labels: bug

#879 Patch auto-update to be blocking (#164460840)
  check-updates.js
  ot-node.js
Labels: bug, enhancement

#878 Refactor Hub contract to use dictionary
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/holding-storage.json
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/abi/hub.json
  modules/Blockchain/Ethereum/abi/litigation-storage.json
  modules/Blockchain/Ethereum/abi/profile-storage.json
  modules/Blockchain/Ethereum/abi/profile.json
  modules/Blockchain/Ethereum/abi/replacement.json
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/Hub.sol
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/contracts/MockLitigation.sol
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/contracts/Replacement.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/test/deployment.test.js
  modules/Blockchain/Ethereum/test/holding.storage.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/Ethereum/test/profile.storage.test.js
  modules/Blockchain/Ethereum/test/profile.test.js
  modules/migration/m1-payout-all-migration.js
  ot-node.js
  test/bdd/steps/lib/local-blockchain.js
Labels: enhancement

#875 Do not use global Infura URL as RPC host for all nodes (#163390065)
  .origintrail_noderc.image
  config/config.json
  ot-node.js
  test/bdd/steps/network.js
  test/modules/utilities.test.js
  testnet/register-node.js
Labels: breaking change, enhancement

#881 Add npm scripts for smart contract deployment on rinkeby and ganache
  package.json
Labels: internal process, minor

#883 Autoupdate patch
  check-updates.js
  modules/migration/m2-sequelize-meta-migration.js
  ot-node.js
Labels: enhancement

#882 Use own RPC host
  config/config.json
  ot-node.js
  test/bdd/steps/network.js
  test/modules/utilities.test.js
  testnet/register-node.js
Labels: breaking change, enhancement

#887 SC miner distribution fix [#164568935]
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/TestingUtilities.sol
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/miner.js
  modules/service/miner-service.js
  test/modules/miner.test.js
Labels: bug, enhancement, hotfix

#885 Check for transaction prices (#163821652) (#845)
  modules/Blockchain/Ethereum/Transactions.js
  test/modules/transactions.test.js
Labels: bug, hotfix

#889 Add paid amount requirement in Holding contract [#163859760]
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/test/offer.test.js
Labels: bug

#890 Fix downloading NaN [#164628113]
  check-updates.js
  modules/Update.js
Labels: bug, chore

#888 Fix DH replacement started command [#164609005]
  modules/command/dh/dh-replacement-started-command.js
Labels: bug

#884 Release v2.0.50
  .travis.yml
  check-updates.js
  config/config.json
  modules/Blockchain/Ethereum/Transactions.js
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/TestingUtilities.sol
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Update.js
  modules/migration/m2-sequelize-meta-migration.js
  modules/miner.js
  modules/service/miner-service.js
  ot-node.js
  package-lock.json
  package.json
  setup_arangodb.sh
  test/bdd/steps/network.js
  test/modules/arangojs.test.js
  test/modules/challenge.test.js
  test/modules/miner.test.js
  test/modules/transactions.test.js
  test/modules/utilities.test.js
  testnet/register-node.js
Labels: breaking change, enhancement, hotfix

#893 Merkle tree hashing fixes [#164668880]
  modules/Merkle.js
Labels: bug

#898 Command executor verbose logging
  .origintrail_noderc.travis
  config/config.json
  modules/command/command-executor.js
  test/modules/utilities.test.js
Labels: chore

#899 Command executor verbose logging
  .origintrail_noderc.travis
  config/config.json
  modules/command/command-executor.js
  package-lock.json
  package.json
  test/modules/utilities.test.js
Labels: chore, enhancement

#897 Add replacement holder variable assertions to truffle test [#163938103]
  .travis.yml
  modules/Blockchain/Ethereum/test/litigation.test.js
Labels: enhancement, internal process

#902 Update contract hub for develop env
  config/config.json
Labels: enhancement

#905 Traversal query [OT-I432]
  modules/Database/Arangojs.js
  package-lock.json
  package.json
Labels: bug, hotfix

#903 Increase timeout in bdd test
  test/bdd/steps/network.js
Labels: bug

#904 Challenge response time fix
  modules/command/dc/dc-challenge-command.js
  modules/constants.js
  test/bdd/features/litigation.feature
  test/bdd/steps/hooks.js
  test/bdd/steps/network.js
Labels: bug

#906 Listen old holding contract
  modules/Blockchain/Ethereum/index.js
  ot-node.js
Labels: bug

#907 Drop using Docker volumes
  Dockerfile
  Dockerfile.development
  Dockerfile.mariner
  Dockerfile.stable
  Dockerfile.staging
Labels: bug
