Repository OriginTrail/ot-node, pull requests merged in 2020-09, with the labels that each got.

#1335 OriginTrail Prerelease v4.1.9
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/marketplace.json
  modules/Blockchain/Ethereum/contracts/Marketplace.sol
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-purchase-take-payment-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-dispute-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/permissioned-data-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/service/permissioned-data-service-test.js
Labels: release

#1336 OriginTrail Release v4.1.9
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/marketplace.json
  modules/Blockchain/Ethereum/contracts/Marketplace.sol
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-purchase-take-payment-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-dispute-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/permissioned-data-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/service/permissioned-data-service-test.js
Labels: release

#1334 Resolved bug with permissioned data hash
  modules/service/permissioned-data-service.js
Labels: bug

#1337 Add validating contact network id
  modules/network/kademlia/kademlia.js
Labels: bug

#1339 Remove unnecessary network identity generating
  package.json
  testnet/register-node.js
Labels: bug

#1342 Improve node filtering based on network id
  modules/network/kademlia/kademlia.js
Labels: bug

#1344 Improve network validation formatting
  modules/network/kademlia/kademlia.js
Labels: minor

#1345 OriginTrail Testnet Release v4.1.10
  modules/network/kademlia/kademlia.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  package.json
  testnet/register-node.js
Labels: release

#1347 OriginTrail Release v4.1.10
  modules/network/kademlia/kademlia.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  package.json
  testnet/register-node.js
Labels: release

#1348 Update data sellers table after purchase
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/controller/dv-controller.js
  package.json
Labels: bug

#1349 Added support for utf8 encoding
  modules/service/permissioned-data-service.js
  package.json
Labels: bug
