Repository OriginTrail/ot-node, pull requests merged in 2020-07, with the labels that each got.

#1298 Fix OT-Json 1.1 sort issue
  importers/use_cases/otjson_1.1/sort1.json
  importers/use_cases/otjson_1.1/sort2.json
  modules/OtJsonUtilities.js
  test/bdd/features/importer.feature
  test/bdd/steps/network.js
Labels: bug

#1300 Fix sorting issue in OT-JSON 1.1
  importers/use_cases/otjson_1.1/sort1.json
  importers/use_cases/otjson_1.1/sort2.json
  modules/OtJsonUtilities.js
  package.json
  test/bdd/features/importer.feature
  test/bdd/steps/network.js
Labels: hotfix

#1295 Preserve handler_id for a delayed offer
  modules/command/common/handler_ids_cleaner_command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/service/dc-service.js
  modules/service/rest-api-v2.js
Labels: bug

#1301 Added support for OT-Json version 1.2
  importers/use_cases/otjson_1.1/sort1.json
  importers/use_cases/otjson_1.1/sort2.json
  importers/use_cases/otjson_1.2/sort1.json
  importers/use_cases/otjson_1.2/sort2.json
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/service/dh-service.js
  modules/service/import-service.js
  package.json
  test/bdd/features/importer.feature
  test/bdd/steps/network.js
Labels: enhancement

#1302 OriginTrail Testnet Prerelease v4.1.7
  importers/use_cases/otjson_1.1/sort1.json
  importers/use_cases/otjson_1.1/sort2.json
  importers/use_cases/otjson_1.2/sort1.json
  importers/use_cases/otjson_1.2/sort2.json
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/common/handler_ids_cleaner_command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  package.json
  test/bdd/features/importer.feature
  test/bdd/steps/network.js
Labels: release

#1303 OriginTrail Testnet Release v4.1.7
  importers/use_cases/otjson_1.1/sort1.json
  importers/use_cases/otjson_1.1/sort2.json
  importers/use_cases/otjson_1.2/sort1.json
  importers/use_cases/otjson_1.2/sort2.json
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/common/handler_ids_cleaner_command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/command/dv/dv-query-network-command.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  package.json
  test/bdd/features/importer.feature
  test/bdd/steps/network.js
Labels: release

#1305 Added a 30 minute period to existing payOut commands
  migrations/202010181032127-update-commands-add-payout-period.js
  modules/command/dh/dh-offer-finalized-command.js
Labels: bug

#1307 OriginTrail Testnet Release v4.1.7 Hotfix
  migrations/202010181032127-update-commands-add-payout-period.js
  modules/command/dh/dh-offer-finalized-command.js
Labels: release

#1309 Better handling of GS1-EPCIS or WOT export after OT-JSON import
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
Labels: bug

#1313 Enabled OT-JSON version 1.2
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
Labels: enhancement

#1304 Added script for backup and upload data to AWS S3 instance
  modules/service/aws-service.js
  package.json
  scripts/backup-upload-aws.js
Labels: enhancement

#1314 Added fetching smart contracts when they are changed on the Hub smart contracts
  modules/Blockchain/Ethereum/index.js
  ot-node.js
  test/bdd/features/blockchain.feature
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/steps/blockchain.js
  test/bdd/steps/erc725identity.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/network.js
Labels: internal process

#1312 Implement trail reach parameter with extended and narrow option
  .travis.yml
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/constants.js
  modules/controller/dh-controller.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  test/api/zkGetTrail.test.js
  test/bdd/features/trail.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/http-api-helper.js
Labels: enhancement

#1316 Remove trail body log
  modules/controller/dh-controller.js
Labels: internal process, minor

#1317 Bump version to 4.1.8
  package.json
Labels: minor

#1319 Add reading arango password if password file exists
  scripts/backup.js
  scripts/restore.js
Labels: bug

#1315 Added BDD test for routing messages via proxy nodes
  test/bdd/features/datalayer.feature
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: enhancement

#1322 OriginTrail Prerelease v4.1.8
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/constants.js
  modules/controller/dh-controller.js
  modules/service/aws-service.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  ot-node.js
  package.json
  scripts/backup-upload-aws.js
  test/api/zkGetTrail.test.js
  test/bdd/features/blockchain.feature
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/features/trail.feature
  test/bdd/steps/blockchain.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/erc725identity.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/network.js
Labels: release

#1324 OriginTrail Release v4.1.8
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/constants.js
  modules/controller/dh-controller.js
  modules/service/aws-service.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  ot-node.js
  package.json
  scripts/backup-upload-aws.js
  test/api/zkGetTrail.test.js
  test/bdd/features/blockchain.feature
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/features/trail.feature
  test/bdd/steps/blockchain.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/erc725identity.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/network.js
Labels: release
