Repository OriginTrail/ot-node, pull requests merged in 2020-12, with the labels that each got.

#1392 Added blockchain_id parameter to replication and payout api
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/controller/dc-controller.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/import-service.js
  modules/service/profile-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/validator/schema-validator.js
  modules/worker/import-worker-controller.js
  test/api/zkGetTrail.test.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/wot-otjson-transpiler.test.js
Labels: enhancement

#1393 Show all blockchain implementations in /info and /balance routes
  modules/controller/info-controller.js
  modules/service/rest-api-v2.js
  test/bdd/features/blockchain.feature
  test/bdd/features/network.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
Labels: enhancement

#1400 Use the default trac price for testnet environment
  modules/service/trac-price-service.js
  package.json
Labels: minor

#1398 Revert smart contract changes
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/test/holding.storage.test.js
Labels: chore

#1405 Update local query API route
  modules/controller/dc-controller.js
Labels: bug, internal process

#1401 Use the default trac price for testnet environment
  modules/service/trac-price-service.js
  package.json
Labels: internal process, minor

#1397 Updated the dataset signature format
  migrations/202011261221123-update-offers-add-blockchain-id.js
  migrations/202011261243123-update-bids-add-blockchain-id.js
  migrations/202011261416123-update-data-info-extend-data-provider-wallet.js
  models/bids.js
  models/data_info.js
  models/offers.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/common/export-command.js
  modules/command/common/export-worker-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dc/dc-offer-cleanup-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replacement-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/controller/dv-controller.js
  modules/controller/export-controller.js
  modules/controller/info-controller.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/validator/schema-validator.js
  modules/worker/export-worker.js
  modules/worker/graph-converter-worker.js
  modules/worker/import-worker-controller.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/network.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/import-utilities.test.js
  test/protocol/protocol.test.js
Labels: enhancement

#1399 Enable network read with multiple blockchain implementations
  modules/Blockchain.js
  modules/DVService.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/controller/dv-controller.js
Labels: enhancement

#1403 Enable permissioned data purchase on multiple blockchains
  migrations/202011301208123-update-data-sellers-add-blockchain-id.js
  migrations/202011301210123-update-data-trades-add-blockchain-id.js
  models/data_sellers.js
  models/data_trades.js
  modules/DVService.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-purchase-take-payment-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/command/dv/dv-purchase-dispute-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/controller/dc-controller.js
  modules/controller/dh-controller.js
  modules/controller/dv-controller.js
  modules/service/permissioned-data-service.js
  modules/service/replication-service.js
  test/protocol/protocol.test.js
Labels: enhancement

#1404 Update API for multiple blockchains
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/controller/dv-controller.js
  modules/controller/info-controller.js
  modules/service/rest-api-v2.js
Labels: enhancement

#1410 Moved start replication as part of the child process
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/controller/dc-controller.js
  modules/service/challenge-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/worker/create-replication-data-worker.js
  modules/worker/validate-received-replication-worker.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
Labels: enhancement

#1411 OriginTrail Testnet Prerelease v4.1.15
  importers/json_examples/local-query1.json
  importers/json_examples/local-query2.json
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/test/holding.storage.test.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/EventEmitter.js
  modules/Product.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/controller/dc-controller.js
  modules/service/challenge-service.js
  modules/service/import-service.js
  modules/service/permissioned-data-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/service/trac-price-service.js
  modules/validator/object-validator.js
  modules/worker/create-replication-data-worker.js
  modules/worker/validate-received-replication-worker.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/importer.feature
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
Labels: release

#1413 Improve ArangoDB query performance for local query and remove permissioned data API routes
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/controller/dc-controller.js
  modules/service/permissioned-data-service.js
  modules/worker/create-replication-data-worker.js
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
Labels: internal process

#1416 Added support for HA node
  Dockerfile.psql.development
  Dockerfile.psql.mainnet
  Dockerfile.psql.testnet
  config/config.json
  config/sequelizeConfig.js
  migrations/202010171600125-update-handler-ids-add-timestamp.js
  migrations/202010181032128-create-node-status.js
  migrations/202010181032129-update-all-tables-set-timestamp.js
  models/challenges.js
  models/commands.js
  models/event.js
  models/handler_ids.js
  models/node_status.js
  models/replicated_data.js
  models/reputation_data.js
  modules/Blockchain/Ethereum/index.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/Database/arango-client.js
  modules/Utilities.js
  modules/command/common/autoupdater-command.js
  modules/command/dc/dc-litigation-answered-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/command/dc/dc-litigation-replacement-started-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-replacement-completed-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-litigation-answered-command.js
  modules/command/dh/dh-litigation-initiated-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-replacement-completed-command.js
  modules/command/dh/dh-replacement-started-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/constants.js
  modules/controller/info-controller.js
  modules/logger.js
  modules/migration/m6-operational-db-migration.js
  modules/network/kademlia/kademlia-utils.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  modules/service/high-availability-service.js
  modules/service/ot-node-client.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  package-lock.json
  package.json
  scripts/setup.js
  test/modules/arangojs.test.js
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/utilities.test.js
  testnet/install-arango.sh
  testnet/install-postgres.sh
  testnet/register-node.js
Labels: enhancement

#1418 Bug fixed when dataset info route returns wrong offer information
  modules/controller/info-controller.js
Labels: bug

#1419 Refactor trail feature to support multiple entry points
  importers/use_cases/trail/milk.xml
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/command/common/trail-cleaner-command.js
  modules/command/dh/dh-find-trail-command.js
  modules/constants.js
  modules/controller/dh-controller.js
  modules/service/rest-api-v2.js
  modules/service/trail-service.js
  test/bdd/features/trail.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
Labels: enhancement

#1422 Typo error fixed
  modules/service/high-availability-service.js
Labels: bug
