Repository OriginTrail/ot-node, pull requests merged in 2020-03, with the labels that each got.

#1184 Update code owners
  .github/CODEOWNERS
Labels: minor

#1189 Resolved bug with dhLitigationInitiatedCommand
  modules/command/dh/dh-litigation-initiated-command.js
  package.json
  test/bdd/features/litigation.feature
Labels: bug

#1188 Increase default litigation interval
  config/config.json
Labels: internal process

#1192 OriginTrail Testnet Release v4.0.7
  .github/CODEOWNERS
  README.md
  config/config.json
  importers/use_cases/OBE/ORDER100678.xml
  importers/use_cases/OBE/ORDER100679.xml
  modules/command/dh/dh-litigation-initiated-command.js
  package.json
  test/bdd/features/importer.feature
  test/bdd/features/litigation.feature
Labels: release

#1194 OriginTrail Mainnet Prerelease v4.0.7
  .github/CODEOWNERS
  README.md
  config/config.json
  importers/use_cases/OBE/ORDER100678.xml
  importers/use_cases/OBE/ORDER100679.xml
  modules/command/dh/dh-litigation-initiated-command.js
  package.json
  test/bdd/features/importer.feature
  test/bdd/features/litigation.feature
Labels: release

#1195 OriginTrail Mainnet Release v4.0.7
  .github/CODEOWNERS
  README.md
  config/config.json
  importers/use_cases/OBE/ORDER100678.xml
  importers/use_cases/OBE/ORDER100679.xml
  modules/command/dh/dh-litigation-initiated-command.js
  package.json
  test/bdd/features/importer.feature
  test/bdd/features/litigation.feature
Labels: release

#1193 Improved the Kademlia direct message routing
  config/config.json
  modules/EventEmitter.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/network/kademlia/kademlia.js
  modules/service/dh-service.js
  package-lock.json
  package.json
  test/modules/utilities.test.js
Labels: enhancement

#1196 OriginTrail Testnet Prerelease v4.0.8
  config/config.json
  modules/EventEmitter.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/network/kademlia/kademlia.js
  modules/service/dh-service.js
  package-lock.json
  package.json
  test/modules/utilities.test.js
Labels: release

#1199 Add backward compatibilty for replication
  modules/EventEmitter.js
Labels: hotfix, minor

#1200 Fix object parsing error
  modules/EventEmitter.js
Labels: hotfix, minor

#1203 Added routes handling if node is bootstrap
  modules/network/kademlia/kademlia.js
Labels: hotfix

#1202 Private data object refactoring
  importers/use_cases/marketplace/marketplace_multiple_claims_single_object.json
  importers/use_cases/marketplace/marketplace_use_case.json
  modules/Database/Arangojs.js
  modules/ImportUtilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/constants.js
  modules/service/dc-service.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  modules/worker/graph-converter-worker.js
Labels: chore, minor

#1204 Increase waiting time for challenge respnse to 5 min
  modules/constants.js
Labels: hotfix

#1197 OriginTrail Testnet Release v4.0.8
  config/config.json
  modules/EventEmitter.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/constants.js
  modules/network/kademlia/kademlia.js
  modules/service/dh-service.js
  package-lock.json
  package.json
  test/modules/utilities.test.js
Labels: release

#1208 OriginTrail Release v4.0.8
  config/config.json
  modules/EventEmitter.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/constants.js
  modules/network/kademlia/kademlia.js
  modules/service/dh-service.js
  package-lock.json
  package.json
  test/modules/utilities.test.js
Labels: release

#1201 Cleaning challenges from db when offer is no longer active
  migrations/202003051105123-update-replicated-data-add-litigation-timestamp.js
  models/replicated_data.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-challenges-command.js
  modules/command/dc/dc-litigation-answered-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/command/dc/dc-offer-cleanup-command.js
Labels: bug, minor

#1209 Add bash script for restoring node from backup
  scripts/restore.sh
Labels: enhancement

#1207 Refactor export route to be non blocking api call
  config/config.json
  migrations/202001171600123-update-offers-add-replication-data.js
  migrations/202003121026123-update-handler-ids-add-timestamp.js
  models/handler_ids.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/common/export-cleaner-command.js
  modules/command/common/export-command.js
  modules/command/common/handler_ids_cleaner_command.js
  modules/constants.js
  modules/controller/export-controller.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  modules/worker/export-worker.js
  test/bdd/features/network.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
Labels: enhancement

#1210 Update available configuration parameters
  config/config.json
  test/modules/utilities.test.js
  testnet/register-node.js
Labels: internal process

#1211 Read and export API route
  modules/command/common/export-cleaner-command.js
  modules/command/common/export-data-command.js
  modules/command/common/export-worker-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dv-controller.js
  modules/controller/export-controller.js
  modules/service/rest-api-v2.js
  modules/worker/export-worker.js
  test/bdd/features/datalayer.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/network.js
Labels: enhancement

#1217 Reverted migration rename - prerelease bug fix
  migrations/202010171600123-update-offers-add-replication-data.js
  migrations/202010171600124-update-replicated-data-add-litigation-timestamp.js
  migrations/202010171600125-update-handler-ids-add-timestamp.js
Labels: hotfix

#1218 Prerelease bug fix
  migrations/202010171600123-update-offers-add-replication-data.js
  migrations/202010171600124-update-replicated-data-add-litigation-timestamp.js
  migrations/202010171600125-update-handler-ids-add-timestamp.js
Labels: hotfix

#1216 OriginTrail Testnet Release v4.0.9
  config/config.json
  migrations/202010171600124-update-replicated-data-add-litigation-timestamp.js
  migrations/202010171600125-update-handler-ids-add-timestamp.js
  models/handler_ids.js
  models/replicated_data.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/common/export-cleaner-command.js
  modules/command/common/export-command.js
  modules/command/common/export-data-command.js
  modules/command/common/export-worker-command.js
  modules/command/common/handler_ids_cleaner_command.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-challenges-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dc/dc-litigation-answered-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/command/dc/dc-offer-cleanup-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dv-controller.js
  modules/controller/export-controller.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  modules/worker/export-worker.js
  package.json
  scripts/restore.sh
  test/bdd/features/datalayer.feature
  test/bdd/features/litigation.feature
  test/bdd/features/network.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/litigation.js
  test/bdd/steps/network.js
  test/modules/utilities.test.js
  testnet/register-node.js
Labels: release

#1221 Optimize export dataset query in the graph database
  modules/Database/Arangojs.js
  modules/service/import-service.js
  package.json
Labels: enhancement

#1220 Refactor truffle wallet provider access key usage
  modules/Blockchain/Ethereum/truffle.js
Labels: internal process

#1219 Refactor permissioned data structure and naming
  importers/use_cases/marketplace/marketplace_use_case.json
  modules/Database/Arangojs.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  modules/service/import-service.js
  modules/service/permissioned-data-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/worker/graph-converter-worker.js
  test/bdd/features/datalayer.feature
  test/bdd/features/network.feature
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/service/permissioned-data-service-test.js
  test/modules/test_data/otjson-graph.js
  test/modules/utilities.test.js
Labels: enhancement
