Repository OriginTrail/ot-node, pull requests merged in 2020-06, with the labels that each got.

#1265 Enable OT-JSON Version 1.1
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  test/modules/epcis-otjson-transpiler.test.js
Labels: enhancement

#1266 Generate unique graph database password as default
  config/config.json
  modules/migration/m5-arango-password-migration.js
  ot-node.js
  scripts/backup.js
  scripts/setup.js
  scripts/update-arango-password.sh
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/utilities.test.js
  testnet/install-arango.sh
  testnet/supervisord.conf
Labels: enhancement

#1267 Added update price factor script
  scripts/update_price_factor.sh
Labels: enhancement

#1269 Resolved unhandled exception: Timed out waiting for response
  config/config.json
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  package.json
Labels: bug

#1270 Added new parameters to node info route
  modules/controller/info-controller.js
  modules/service/rest-api-controller.js
  modules/service/rest-api-v2.js
Labels: minor

#1271 OriginTrail Testnet Prerelease v4.1.3
  config/config.json
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/controller/info-controller.js
  modules/migration/m5-arango-password-migration.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  modules/service/rest-api-controller.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  ot-node.js
  package.json
  scripts/backup.js
  scripts/setup.js
  scripts/update-arango-password.sh
  scripts/update_price_factor.sh
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/utilities.test.js
  testnet/install-arango.sh
  testnet/supervisord.conf
Labels: release

#1272 Resolved bug with contact fetching from itterative find result
  modules/network/kademlia/kademlia.js
Labels: bug

#1273 Bugfix, resolved bug with contact fetching from iterative find result
  modules/network/kademlia/kademlia.js
Labels: bug

#1274 OriginTrail Testnet Release v4.1.3
  config/config.json
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/controller/info-controller.js
  modules/migration/m5-arango-password-migration.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  modules/service/rest-api-controller.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  ot-node.js
  package.json
  scripts/backup.js
  scripts/setup.js
  scripts/update-arango-password.sh
  scripts/update_price_factor.sh
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/utilities.test.js
  testnet/install-arango.sh
  testnet/supervisord.conf
Labels: release

#1276 Update backup and restore script
  scripts/backup.js
  scripts/restore.js
Labels: hotfix

#1275 Resolved issue with too many infura calls
  modules/command/dh/dh-offer-finalized-command.js
  modules/service/dh-service.js
Labels: hotfix

#1278 OriginTrail Mainnet Prerelease v4.1.3
  config/config.json
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/controller/info-controller.js
  modules/migration/m5-arango-password-migration.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  modules/service/dh-service.js
  modules/service/rest-api-controller.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  ot-node.js
  package.json
  scripts/backup.js
  scripts/restore.js
  scripts/setup.js
  scripts/update-arango-password.sh
  scripts/update_price_factor.sh
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/utilities.test.js
  testnet/install-arango.sh
  testnet/supervisord.conf
Labels: release

#1279 OriginTrail Mainnet Release v4.1.3
  config/config.json
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/controller/info-controller.js
  modules/migration/m5-arango-password-migration.js
  modules/network/kademlia/kademlia.js
  modules/network/transport.js
  modules/service/dh-service.js
  modules/service/rest-api-controller.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  ot-node.js
  package.json
  scripts/backup.js
  scripts/restore.js
  scripts/setup.js
  scripts/update-arango-password.sh
  scripts/update_price_factor.sh
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/utilities.test.js
  testnet/install-arango.sh
  testnet/supervisord.conf
Labels: release

#1280 Update get_dataset_info route to return offer details
  modules/controller/info-controller.js
  modules/service/rest-api-v2.js
Labels: chore

#1281 Reduce gas cost for offers
  modules/Blockchain.js
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/test/holding.storage.test.js
  modules/Blockchain/Ethereum/test/litigation.test.js
  modules/Blockchain/Ethereum/test/metrics.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  test/bdd/features/litigation.feature
Labels: internal process

#1277 Raise the minimum token stake to 3000TRAC
  modules/Blockchain/Ethereum/contracts/Profile.sol
Labels: enhancement

#1283 Update OT-JSON sort method
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  package.json
Labels: bug, hotfix

#1285 Update OT-JSON sort method
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  package.json
Labels: bug, hotfix

#1286 Fix OT-JSON v1.1 export signature sort issue
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  package-lock.json
  package.json
Labels: bug

#1288 OriginTrail Testnet Release v4.1.5
  modules/Blockchain.js
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/test/holding.storage.test.js
  modules/Blockchain/Ethereum/test/litigation.test.js
  modules/Blockchain/Ethereum/test/metrics.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/controller/info-controller.js
  modules/service/rest-api-v2.js
  package-lock.json
  package.json
  test/bdd/features/litigation.feature
Labels: release

#1290 OriginTrail Release v4.1.5
  modules/Blockchain.js
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/contracts/Profile.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/test/holding.storage.test.js
  modules/Blockchain/Ethereum/test/litigation.test.js
  modules/Blockchain/Ethereum/test/metrics.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/controller/info-controller.js
  modules/service/rest-api-v2.js
  package-lock.json
  package.json
  test/bdd/features/litigation.feature
Labels: release

#1291 Sort routing messages in data integrity validation process
  modules/Utilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/command/dv/dv-query-network-command.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/service/dh-service.js
Labels: bug

#1292 OriginTrail Testnet Prerelease v4.1.6
  modules/Utilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/command/dv/dv-query-network-command.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/service/dh-service.js
Labels: release
