Repository OriginTrail/ot-node, pull requests merged in 2020-04, with the labels that each got.

#1225 Added whitelist viewer API route
  modules/Database/Arangojs.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/controller/dh-controller.js
  modules/service/rest-api-v2.js
  test/bdd/features/datalayer.feature
  test/bdd/features/permissioned_data.feature
Labels: enhancement

#1228 Added new EC encryption class
  modules/DVService.js
  modules/ECEncryption.js
  modules/Graph.js
  modules/ImportUtilities.js
  modules/RSAEncryption.js
  modules/command/dc/dc-replication-completed-command.js
  modules/command/dh/dh-replacement-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/permissioned-data-service.js
  modules/service/replication-service.js
  package-lock.json
  package.json
  test/modules/ECencryption.test.js
  test/modules/RSAencryption.test.js
  test/modules/graph.test.js
  test/modules/import-utilities.test.js
Labels: enhancement

#1231 Added table in database for storing public keys
  migrations/202010171600126-create-public-keys.js
  models/public_keys.js
  modules/Blockchain/Ethereum/test/creditor.handler.test.js
  modules/Blockchain/Ethereum/test/litigation.test.js
Labels: minor

#1230 Adding Kademlia routes for public key fetch
  modules/EventEmitter.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/network-service.js
  modules/service/permissioned-data-service.js
  ot-node.js
Labels: minor

#1227 Refactor fingerprint API route
  modules/EventEmitter.js
  modules/command/dh/dh-replication-import-command.js
  modules/controller/dv-controller.js
  modules/service/rest-api-v2.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  package.json
  test/bdd/steps/lib/http-api-helper.js
Labels: internal process

#1232 Add BDD test for whitelist_viewer API
  importers/sample_files/DC1_02-sample_product_shipping.xml
  importers/sample_files/DC2_01-sample_product_receiving.xml
  importers/sample_files/DC2_03-sample_batch_shipping.xml
  importers/sample_files/DC3_01-sample_batch_receiving.xml
  importers/use_cases/connectors/01_Green_to_pink_shipment.xml
  importers/use_cases/connectors/02_Green_to_Pink_receipt.xml
  importers/use_cases/marketplace/permissioned_data_simple_sample.json
  modules/ImportUtilities.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/controller/dh-controller.js
  modules/service/permissioned-data-service.js
  package-lock.json
  test/bdd/features/permissioned_data.feature
  test/bdd/features/trail.feature
  test/bdd/steps/blockchain.js
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/network.js
Labels: internal process

#1233 Added signature check in kademlia on received message
  modules/EventEmitter.js
  package-lock.json
  test/bdd/features/litigation.feature
Labels: minor

#1234 Root hash not showing on explorer
  modules/command/common/export-data-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  test/bdd/steps/network.js
Labels: bug

#1236 Added migration files to backup and restore procedure
  scripts/backup.js
  scripts/restore.sh
Labels: bug

#1235 Key fetching & Message encryption
  modules/constants.js
  modules/network/kademlia/kademlia.js
  modules/service/network-service.js
  package-lock.json
  package.json
Labels: enhancement

#1245 Refactored bugsnag usage
  modules/DVService.js
  modules/Database/GraphStorage.js
  modules/EventEmitter.js
  modules/RemoteControl.js
  modules/command/command-executor.js
  modules/command/common/autoupdater-command.js
  modules/command/common/export-command.js
  modules/command/common/export-data-command.js
  modules/command/common/export-worker-command.js
  modules/command/dc/dc-challenge-check-command.js
  modules/command/dc/dc-challenge-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dc/dc-litigation-answered-command.js
  modules/command/dc/dc-litigation-complete-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-challenge-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-litigation-answer-command.js
  modules/command/dh/dh-litigation-answered-command.js
  modules/command/dh/dh-litigation-initiated-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/migration/m1-payout-all-migration.js
  modules/network/kademlia/kademlia-utils.js
  modules/network/kademlia/kademlia.js
  modules/service/dh-service.js
  modules/service/error-notification-service.js
  ot-node.js
  package-lock.json
  package.json
  test/api/zkGetTrail.test.js
  test/modules/command/common/autoupdater-command.test.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/service/permissioned-data-service-test.js
  test/protocol/protocol.test.js
Labels: internal process
