Repository OriginTrail/ot-node, pull requests merged in 2020-10, with the labels that each got.

#1354 Replication request optimization
  modules/network/kademlia/kademlia.js
  modules/service/replication-service.js
  package.json
Labels: enhancement

#1355 OriginTrail Testnet Prerelease v4.1.11
  README.md
  modules/network/kademlia/kademlia.js
  modules/service/replication-service.js
  package.json
Labels: release

#1356 OriginTrail Testnet Release v4.1.11
  README.md
  modules/network/kademlia/kademlia.js
  modules/service/replication-service.js
  package.json
Labels: release

#1352 Identity creation updated to support multiple chain implementation
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/RemoteControl.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dc/dc-litigation-complete-command.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-litigation-replacement-started-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-replace-command.js
  modules/command/dc/dc-offer-replacement-completed-command.js
  modules/command/dc/dc-replication-completed-command.js
  modules/command/dh/dh-litigation-answer-command.js
  modules/command/dh/dh-litigation-initiated-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-replacement-completed-command.js
  modules/command/dh/dh-replacement-handle-command.js
  modules/command/dh/dh-replacement-started-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/controller/dc-controller.js
  modules/controller/dh-controller.js
  modules/controller/dv-controller.js
  modules/controller/info-controller.js
  modules/migration/m1-payout-all-migration.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/error-notification-service.js
  modules/service/network-service.js
  modules/service/profile-service.js
  modules/service/replication-service.js
  ot-node.js
  scripts/backup.js
  scripts/restore.js
Labels: enhancement

#1357 Change testnet to use a fixed gas price
  modules/service/pricing-service.js
  package.json
Labels: enhancement, minor

#1360 OriginTrail Mainnet Prerelease v4.1.12
  README.md
  modules/network/kademlia/kademlia.js
  modules/service/pricing-service.js
  modules/service/replication-service.js
  package.json
Labels: release

#1361 OriginTrail Mainnet Release v4.1.12
  README.md
  modules/network/kademlia/kademlia.js
  modules/service/pricing-service.js
  modules/service/replication-service.js
  package.json
Labels: release
