Repository OriginTrail/ot-node, pull requests merged in 2020-05, with the labels that each got.

#1249 Update GS1-EPCIS transpiler to store key-value pairs in the same array
  modules/transpiler/epcis/epcis-otjson-transpiler.js
Labels: bug

#1248 Added success check to node backup script
  scripts/backup.js
Labels: enhancement

#1247 Added support for routing encrypted messages on the network layer
  modules/network/kademlia/kademlia.js
  modules/service/network-service.js
Labels: enhancement

#1251 Added OT-JSON Utilities for more consistent dataset sorting
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/service/challenge-service.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/validator/schema-validator.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  ot-node.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/network.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
Labels: enhancement

#1257 Add support for sorting OTJSON version 1.1
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/otjson-utilities.test.js
Labels: enhancement

#1260 Enabled the Kademlia encryption routing protocol
  modules/network/kademlia/kademlia.js
Labels: enhancement

#1259 Handle network query issues
  modules/command/dh/dh-read-data-location-request-command.js
  modules/controller/dv-controller.js
  test/bdd/features/datalayer.feature
  test/bdd/steps/network.js
Labels: enhancement, internal process

#1258 Added support for permissioned data in gs1 epcis transpiler
  importers/use_cases/marketplace/permissioned_data_simple_sample.xml
  modules/constants.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  package.json
  test/modules/epcis-otjson-transpiler.test.js
Labels: enhancement

#1261 OriginTrail Testnet Prerelease v4.1.2
  importers/use_cases/marketplace/permissioned_data_simple_sample.xml
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/otjson-utilities.test.js
Labels: release

#1262 OriginTrail Testnet Release v4.1.2
  importers/use_cases/marketplace/permissioned_data_simple_sample.xml
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/otjson-utilities.test.js
Labels: release

#1263 OriginTrail Mainnet Prerelease v4.1.2
  importers/use_cases/marketplace/permissioned_data_simple_sample.xml
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/otjson-utilities.test.js
Labels: release

#1264 OriginTrail Mainnet Release v4.1.2
  importers/use_cases/marketplace/permissioned_data_simple_sample.xml
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/Utilities.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/lib/utilities.js
  test/bdd/steps/network.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/otjson-utilities.test.js
Labels: release
