Repository OriginTrail/ot-node, pull requests merged in 2020-11, with the labels that each got.

#1366 Kadence library version updated
  package-lock.json
  package.json
Labels: bug

#1368 Hotfix - Kadence library version updated (#1366)
  package-lock.json
  package.json
Labels: hotfix

#1369 Hotfix - Kadence library version updated (#1366)
  package-lock.json
  package.json
Labels: hotfix

#1370 Hotfix - Kadence library version updated (#1366)
  package-lock.json
  package.json
Labels: hotfix

#1371 Hotfix - Kadence library version updated (#1366)
  package-lock.json
  package.json
Labels: hotfix

#1367 Make replication communication asycnhronous
  modules/EventEmitter.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dh/dh-replication-timeout-command.js
  modules/controller/dh-controller.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  package.json
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: bug, enhancement

#1375 Set synchronous replication communication as default
  modules/EventEmitter.js
  modules/command/dh/dh-offer-handle-command.js
  modules/controller/dh-controller.js
Labels: bug

#1376 OriginTrail Testnet Prerelease v4.1.13
  modules/EventEmitter.js
  modules/command/dh/dh-offer-handle-command.js
  modules/controller/dh-controller.js
Labels: release

#1377 OriginTrail Testnet Release v4.1.13
  modules/EventEmitter.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dh/dh-replication-timeout-command.js
  modules/controller/dh-controller.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  package.json
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: release

#1379 OriginTrail Mainnet Prerelease v4.1.13
  modules/EventEmitter.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dh/dh-replication-timeout-command.js
  modules/controller/dh-controller.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  package.json
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: release

#1380 OriginTrail Mainnet Release v4.1.13
  modules/EventEmitter.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dh/dh-replication-timeout-command.js
  modules/controller/dh-controller.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  package.json
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: release

#1381 Enabling async communication for replication.
  modules/command/dh/dh-offer-handle-command.js
  modules/service/miner-service.js
  package.json
Labels: bug, enhancement

#1373 Update extended trail response
  modules/controller/dh-controller.js
Labels: bug

#1382 OriginTrail Testnet Prerelease v4.1.14
  modules/command/dh/dh-offer-handle-command.js
  modules/controller/dh-controller.js
  modules/service/miner-service.js
  package.json
Labels: release

#1383 OriginTrail Testnet Release v4.1.14
  modules/command/dh/dh-offer-handle-command.js
  modules/controller/dh-controller.js
  modules/service/miner-service.js
  package.json
Labels: release

#1384 OriginTrail Mainnet Prerelease v4.1.14
  modules/command/dh/dh-offer-handle-command.js
  modules/controller/dh-controller.js
  modules/service/miner-service.js
  package.json
Labels: release

#1385 OriginTrail Mainnet Release v4.1.14
  modules/command/dh/dh-offer-handle-command.js
  modules/controller/dh-controller.js
  modules/service/miner-service.js
  package.json
Labels: release

#1363 Adapt node wallet-based signing and refactor unit and BDD tests for multiple blockchain implementations
  .origintrail_noderc.image
  config/config.json
  importers/json_examples/kakaxi.wot
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/BytesUtilities.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/RemoteControl.js
  modules/Utilities.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/command/dv/dv-query-network-command.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/controller/info-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/data-integrity/data-integrity-resolver.js
  modules/service/data-integrity/data-integrity-service.js
  modules/service/data-integrity/elliptic-data-integrity-service.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/error-notification-service.js
  modules/service/pricing-service.js
  modules/service/profile-service.js
  modules/service/rest-api-v2.js
  modules/service/trac-price-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/import-worker-controller.js
  modules/worker/otjson-converter-worker.js
  ot-node.js
  package-lock.json
  package.json
  test/api/zkGetTrail.test.js
  test/bdd/steps/blockchain.js
  test/bdd/steps/erc725identity.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/litigation.js
  test/bdd/steps/network.js
  test/modules/data-integrity-service.test.js
  test/modules/epcis-otjson-transpiler.test.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/service/pricing-service-test.js
  test/modules/utilities.test.js
  test/modules/wot-otjson-transpiler.test.js
  test/protocol/protocol.test.js
  testnet/register-node.js
Labels: enhancement

#1390 Remove unnecessary usage of web3 module functions
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/DVService.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/RSAEncryption.js
  modules/RemoteControl.js
  modules/Utilities.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replacement-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-location-response-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-handle-network-query-responses-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/command/dv/dv-query-network-command.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/import-service.js
  modules/service/pricing-service.js
  modules/service/profile-service.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/export-worker.js
  modules/worker/import-worker-controller.js
  ot-node.js
  test/bdd/steps/network.js
  test/modules/gs1-importer.test.js
  test/modules/import-utilities.test.js
  test/modules/utilities.test.js
Labels: enhancement

#1391 Fixed the default blockchain configuration being overriden
  modules/Blockchain.js
  ot-node.js
  test/modules/service/pricing-service-test.js
Labels: bug

#1396 Resolved bug when node is unavailable to fetch all events from blockchain
  modules/Blockchain/Ethereum/index.js
Labels: bug

#1394 Refactor query local API route
  importers/json_examples/local-query1.json
  importers/json_examples/local-query2.json
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/EventEmitter.js
  modules/Product.js
  modules/controller/dc-controller.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  modules/validator/object-validator.js
  test/bdd/features/datalayer.feature
  test/bdd/features/importer.feature
  test/bdd/steps/endpoints.js
Labels: enhancement

#1395 Add remove permissioned data API route
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/controller/dc-controller.js
  modules/service/permissioned-data-service.js
  modules/service/rest-api-v2.js
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
Labels: enhancement
