Repository OriginTrail/ot-node, pull requests merged in 2020-01, with the labels that each got.

#1119 Removed knex and sequalize-cli dependencies
  package-lock.json
  package.json
Labels: chore

#1122 Feature/update replication status response
  migrations/202010171600123-update-offers-add-replication-data.js
  models/offers.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/controller/dc-controller.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  modules/service/rest-api-v2.js
  test/modules/service/pricing-service-test.js
Labels: enhancement

#1124 Improved answerLitigation success rate by adding retries and increasing gas price
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/command/command-executor.js
  modules/command/command.js
  modules/command/dc/dc-litigation-complete-command.js
  modules/command/dh/dh-litigation-answer-command.js
  modules/constants.js
  modules/service/dh-service.js
Labels: bug, hotfix

#1123 Feature/update replication status if replication fails
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/network/kademlia/kademlia.js
  modules/service/rest-api-v2.js
  package.json
Labels: bug

#1128 OriginTrail Gemini release v4.0.2
  migrations/202010171600123-update-offers-add-replication-data.js
  models/offers.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/index.js
  modules/command/command-executor.js
  modules/command/command.js
  modules/command/dc/dc-litigation-complete-command.js
  modules/command/dc/dc-offer-choose-command.js
  modules/command/dc/dc-offer-create-bc-command.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-finalize-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-mining-completed-command.js
  modules/command/dc/dc-offer-mining-status-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dh/dh-litigation-answer-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  modules/service/rest-api-v2.js
  package-lock.json
  package.json
  test/modules/service/pricing-service-test.js
Labels: release

#1127 Added bdd test for failing replication
  test/bdd/features/network.feature
  test/bdd/steps/network.js
Labels: internal process

#1130 Added more verbose error logs for Import worker
  modules/worker/graph-converter-worker.js
  modules/worker/otjson-converter-worker.js
Labels: internal process, minor

#1133 Standardized OT-JSON object format
  modules/service/import-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/graph-converter-worker.js
Labels: internal process

#1131 Add creating a cache file during import and replication
  modules/ImportUtilities.js
  modules/command/dc/dc-convert-to-graph-command.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/worker/graph-converter-worker.js
  modules/worker/import-worker-controller.js
  modules/worker/otjson-converter-worker.js
  package-lock.json
  package.json
  test/bdd/steps/datalayer.js
Labels: internal process

#1134 Litigation logging fixed
  modules/command/dc/dc-challenges-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/constants.js
  test/bdd/features/litigation.feature
Labels: enhancement, minor

#1132 feature/api-route-challenges
  modules/command/dc/dc-challenges-command.js
  modules/service/rest-api-v2.js
Labels: enhancement

#1137 Implement release drafter tool
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: internal process

#1139 OriginTrail Testnet release v4.0.3
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  modules/ImportUtilities.js
  modules/command/dc/dc-challenges-command.js
  modules/command/dc/dc-convert-to-graph-command.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/graph-converter-worker.js
  modules/worker/import-worker-controller.js
  modules/worker/otjson-converter-worker.js
  package-lock.json
  package.json
  test/bdd/features/litigation.feature
  test/bdd/steps/datalayer.js
Labels: release

#1144 OriginTrail Release v4.0.3
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  modules/ImportUtilities.js
  modules/command/dc/dc-challenges-command.js
  modules/command/dc/dc-convert-to-graph-command.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/command/dc/dc-finalize-import-command.js
  modules/command/dc/dc-litigation-completed-command.js
  modules/command/dc/dc-litigation-initiate-command.js
  modules/command/dc/dc-litigation-initiated-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dc/dc-write-import-to-graph-db-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  modules/transpiler/wot/wot-otjson-transpiler.js
  modules/worker/graph-converter-worker.js
  modules/worker/import-worker-controller.js
  modules/worker/otjson-converter-worker.js
  package-lock.json
  package.json
  test/bdd/features/litigation.feature
  test/bdd/features/network.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/network.js
Labels: release
