Repository OriginTrail/ot-node, pull requests merged in 2020-08, with the labels that each got.

#1323 Added marketplace purchase features
  migrations/202001171600123-update-offers-add-replication-data.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-purchase-take-payment-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/permissioned-data-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  test/bdd/features/datalayer.feature
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/modules/service/permissioned-data-service-test.js
Labels: enhancement

#1327 Bugfix for payout command
  modules/command/dh/dh-pay-out-command.js
Labels: bug

#1326 Purchase complete broadcast
  modules/EventEmitter.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
Labels: enhancement

#1328 Add trading types to DV controller
  modules/controller/dv-controller.js
  modules/service/rest-api-v2.js
Labels: bug

#1329 OriginTrail Testnet Prerelease v4.1.9
  migrations/202001171600123-update-offers-add-replication-data.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/marketplace.json
  modules/Blockchain/Ethereum/contracts/Marketplace.sol
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-purchase-take-payment-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-dispute-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/permissioned-data-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/service/permissioned-data-service-test.js
Labels: release

#1331 Hotfix: Renamed migration (#1330)
  migrations/202010171600123-update-offers-add-replication-data.js
Labels: hotfix

#1332 OriginTrail Testnet Release v4.1.9
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/marketplace.json
  modules/Blockchain/Ethereum/contracts/Marketplace.sol
  modules/Blockchain/Ethereum/index.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-purchase-take-payment-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/command/dv/dv-purchase-dispute-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/permissioned-data-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/service/permissioned-data-service-test.js
Labels: release

#1333 Update relation types and properties structure in WOT transpiler
  modules/transpiler/wot/wot-otjson-transpiler.js
Labels: bug
