Repository OriginTrail/ot-node, pull requests merged in 2020-02, with the labels that each got.

#1146 Improved trail query
  importers/sample_files/DC1_01-sample_product_packing.xml
  importers/sample_files/DC1_02-sample_product_shipping.xml
  importers/sample_files/DC2_01-sample_product_receiving.xml
  importers/sample_files/DC2_02-sample_transformation_event.xml
  importers/sample_files/DC2_03-sample_batch_shipping.xml
  importers/sample_files/DC3_01-sample_batch_receiving.xml
  importers/sample_files/DC3_02-sample_batch_selling.xml
  modules/Database/Arangojs.js
  modules/service/rest-api-v2.js
  test/bdd/features/importer.feature
  test/bdd/features/trail.feature
  test/bdd/steps/datalayer.js
  test/bdd/steps/network.js
Labels: bug

#1148 Added removing of old node versions
  testnet/register-node.js
Labels: chore, internal process

#1135 Added calling dhLitigationAnswerCommand directly when litigation is detected
  modules/command/dh/dh-litigation-answer-command.js
  modules/command/dh/dh-litigation-initiated-command.js
  modules/service/dh-service.js
  test/bdd/steps/blockchain.js
  test/bdd/steps/litigation.js
  test/bdd/steps/network.js
Labels: internal process

#1147 Feature/update key length used for replication
  modules/service/replication-service.js
  test/bdd/features/importer.feature
  test/bdd/features/trail.feature
Labels: minor

#1160 Fix Release Drafter setup
  .github/release-drafter-template.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter-config.yml
Labels: internal process

#1161 Make challenge logs more verbose on DC side
  modules/command/dc/dc-challenge-check-command.js
Labels: internal process

#1159 Feature/marketplace/add purchase network private read api route
  importers/use_cases/marketplace/marketplace_multiple_claims_single_object.json
  migrations/202002110729550-create-private-data-permission.js
  models/data_permission.js
  models/private_data_permissions.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/EventEmitter.js
  modules/ImportUtilities.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-data-read-request-free-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-read-data-location-request-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-request-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/network/http/http-network.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  modules/service/import-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/worker/graph-converter-worker.js
  test/modules/import-utilities.test.js
Labels: internal process

#1163 Added pre commit hook
  .githooks/pre-commit
  .travis.yml
  test/bdd/features/datalayer.feature
  test/bdd/features/litigation.feature
Labels: internal process

#1145 Increase Kademlia parallel network calls
  modules/network/kademlia/kademlia.js
  package-lock.json
  package.json
Labels: enhancement

#1166 HotFix/Litigation wrong answer bugsnag notification
  config/config.json
  modules/command/dh/dh-challenge-command.js
  test/modules/utilities.test.js
Labels: internal process

#1162 Fix sample files to have full sgtin as the epc of the event
  importers/use_cases/OBE/ORDER100678.xml
  importers/use_cases/OBE/ORDER100679.xml
  test/bdd/features/importer.feature
Labels: internal process

#1176 Add purchase commands
  migrations/202002191400123-create-data-trades.js
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/marketplace-storage.json
  modules/Blockchain/Ethereum/abi/marketplace.json
  modules/Blockchain/Ethereum/contracts/Marketplace.sol
  modules/Blockchain/Ethereum/contracts/MarketplaceStorage.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/test/marketplace.test.js
  modules/ImportUtilities.js
  modules/Merkle.js
  modules/RemoteControl.js
  modules/command/dh/dh-purchase-initiated-command.js
  modules/command/dh/dh-purchase-requested-command.js
  modules/command/dh/dh-purchase-take-payment-command.js
  modules/command/dv/dv-purchase-dispute-command.js
  modules/command/dv/dv-purchase-initiate-command.js
  modules/command/dv/dv-purchase-key-deposited-command.js
  modules/command/dv/dv-purchase-request-command.js
  modules/controller/dc-controller.js
  modules/controller/dv-controller.js
  modules/service/import-service.js
  modules/service/rest-api-v2.js
  ot-node.js
  package.json
  test/modules/import-utilities.test.js
Labels: enhancement
