Repository OriginTrail/ot-node, pull requests merged in 2021-09, with the labels that each got.

#1635 Retry calling arango db status multiple times before throwing an error
  modules/Utilities.js
  modules/constants.js
Labels: bug

#1636 Added support for giai identifier in epcis to otjson transpiler
  modules/transpiler/epcis/epcis-otjson-transpiler.js
Labels: bug

#1638 Data vertices trail update
  modules/service/import-service.js
Labels: enhancement

#1637 Updated local query to return replication info for each dataset
  modules/controller/dc-controller.js
  test/bdd/steps/endpoints.js
Labels: bug

#1639 Added retries limitation for payout command
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
Labels: bug

#1644 Version bump
  package.json
Labels: chore

#1645 Resolved issue when dh node would send replication request multiple times
  modules/command/dh/dh-offer-handle-command.js
Labels: bug

#1642 Create operational db backup before starting synchronisation
  modules/service/high-availability-service.js
Labels: bug

#1643 Added operation db validation after backup is performed
  scripts/backup.js
Labels: bug

#1647 Pruning incorrectly detects the backup directory size
  modules/service/dataset-pruning-service.js
Labels: bug

#1646 OriginTrail Testnet Prerelease v5.1.2
  README.md
  config/config.json
  modules/Blockchain/Polygon/abi/token.json
  modules/Blockchain/Polygon/index.js
  modules/Blockchain/Polygon/migrations/2_total_migration.js
  modules/Blockchain/Polygon/truffle.js
  modules/Utilities.js
  modules/command/common/dataset-pruning-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/service/dataset-pruning-service.js
  modules/service/high-availability-service.js
  modules/service/import-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  origintrail_noderc.image
  package.json
  scripts/backup.js
  test/bdd/steps/endpoints.js
  test/docker/check_image.sh
  test/docker/cleanup_image.sh
Labels: release

#1649 OriginTrail Testnet Release v5.1.2
  README.md
  config/config.json
  modules/Blockchain/Polygon/abi/token.json
  modules/Blockchain/Polygon/index.js
  modules/Blockchain/Polygon/migrations/2_total_migration.js
  modules/Blockchain/Polygon/truffle.js
  modules/Utilities.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/service/dataset-pruning-service.js
  modules/service/high-availability-service.js
  modules/service/import-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  origintrail_noderc.image
  package.json
  scripts/backup.js
  test/bdd/steps/endpoints.js
  test/docker/check_image.sh
  test/docker/cleanup_image.sh
Labels: release

#1650 OriginTrail Mainnet Prerelease v5.1.2
  modules/Blockchain/Polygon/migrations/2_total_migration.js
  modules/Blockchain/Polygon/truffle.js
  modules/Utilities.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/service/dataset-pruning-service.js
  modules/service/high-availability-service.js
  modules/service/import-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  origintrail_noderc.image
  package.json
  scripts/backup.js
  test/bdd/steps/endpoints.js
  test/docker/check_image.sh
  test/docker/cleanup_image.sh
Labels: release

#1651 OriginTrail Mainnet Release v5.1.2
  modules/Blockchain/Polygon/migrations/2_total_migration.js
  modules/Blockchain/Polygon/truffle.js
  modules/Utilities.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/service/dataset-pruning-service.js
  modules/service/high-availability-service.js
  modules/service/import-service.js
  modules/transpiler/epcis/epcis-otjson-transpiler.js
  origintrail_noderc.image
  package.json
  scripts/backup.js
  test/bdd/steps/endpoints.js
  test/docker/check_image.sh
  test/docker/cleanup_image.sh
Labels: release
