Repository OriginTrail/ot-node, pull requests merged in 2021-03, with the labels that each got.

#1460 OriginTrail Mainnet Prerelease v4.1.17
  modules/command/common/autoupdater-command.js
  modules/command/common/export-data-command.js
  modules/worker/create-replication-data-worker.js
  package.json
  scripts/generate_v5_configuration.js
  scripts/migrate_to_v5.sh
  scripts/start_v5_update.js
Labels: release

#1465 OriginTrail Mainnet Release v4.1.17
  modules/command/common/autoupdater-command.js
  modules/command/common/export-data-command.js
  modules/worker/create-replication-data-worker.js
  package.json
  scripts/generate_v5_configuration.js
  scripts/migrate_to_v5.sh
  scripts/start_v5_update.js
Labels: release

#1467 Fix permissioned data read functionality
  modules/EventEmitter.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dv/dv-permissioned-data-read-request-command.js
  modules/controller/dc-controller.js
  modules/controller/dh-controller.js
  modules/controller/dv-controller.js
  modules/network/kademlia/kademlia.js
  modules/service/dc-service.js
  modules/service/permissioned-data-service.js
Labels: bug

#1472 Added masking of node private key for new configuration format
  modules/RemoteControl.js
  modules/service/error-notification-service.js
  testnet/register-node.js
Labels: enhancement

#1473 Updated backup restore script to work with dual chain node
  scripts/backup.js
  scripts/restore.sh
Labels: bug

#1474 Add instructions for OT-Node functional testing
  test/README.md
Labels: good first issue

#1475 Fix naming for data_creator during export
  modules/controller/export-controller.js
  package.json
Labels: bug

#1476 Add blockchain_id to data creator section in export result
  modules/worker/export-worker.js
Labels: enhancement

#1479 Updated bootstraps and network id in configuration
  config/config.json
Labels: minor

#1482 Override ambiguous blockchain_ids
  modules/ImportUtilities.js
  modules/worker/export-worker.js
Labels: bug

#1484 Resolved issue with bad network_id parameter name
  config/config.json
  modules/Blockchain/Web3Implementation/index.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/command/dh/dh-replication-import-command.js
  modules/command/dv/dv-data-read-response-free-command.js
  modules/worker/export-worker.js
Labels: hotfix

#1486 Match both blockchain_title and network_id for blockchain config loading
  modules/Blockchain.js
Labels: bug

#1488 [Hotfix] Check blockchain id when attaching default config
  modules/Blockchain.js
Labels: hotfix

#1490 Resolving arangodb memory issue error after migration to v5
  config/config.json
  modules/Blockchain/Web3Implementation/Transactions.js
  modules/migration/m7-arango-dataset-signature-migration.js
  modules/service/dc-service.js
  ot-node.js
  package.json
Labels: bug

#1502 Fix config reading for nodes with "mariner" node_env
  migrations/202010201032128-update-events-add-blockchain-id.js
  migrations/202011261221123-update-offers-add-blockchain-id.js
  migrations/202011261243123-update-bids-add-blockchain-id.js
  migrations/202011261416123-update-data-info-extend-data-provider-wallet.js
  migrations/202011301208123-update-data-sellers-add-blockchain-id.js
  migrations/202011301210123-update-data-trades-add-blockchain-id.js
  migrations/202012090818123-update-purchased-data-add-blockchain-id.js
  migrations/202012151048123-update-challenges-add-blockchain-id.js
  migrations/202102120853043-update-commands-add-blockchain-id.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/logger.js
  modules/worker/export-worker.js
Labels: hotfix

#1503 Level develop with release/mainnet
  migrations/202010201032128-update-events-add-blockchain-id.js
  migrations/202011261221123-update-offers-add-blockchain-id.js
  migrations/202011261243123-update-bids-add-blockchain-id.js
  migrations/202011261416123-update-data-info-extend-data-provider-wallet.js
  migrations/202011301208123-update-data-sellers-add-blockchain-id.js
  migrations/202011301210123-update-data-trades-add-blockchain-id.js
  migrations/202012090818123-update-purchased-data-add-blockchain-id.js
  migrations/202012151048123-update-challenges-add-blockchain-id.js
  migrations/202102120853043-update-commands-add-blockchain-id.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/logger.js
  modules/worker/export-worker.js
Labels: chore
