Repository OriginTrail/ot-node, pull requests merged in 2021-06, with the labels that each got.

#1566 Updated column types for psql database
  migrations/202106011054103-update-column-types.js
  models/offers.js
  models/public_keys.js
  modules/command/common/autoupdater-command.js
  modules/command/dh/dh-process-blockchain-events-command.js
  ot-node.js
  test/bdd/features/datalayer.feature
  test/bdd/features/litigation.feature
  test/bdd/steps/blockchain.js
Labels: bug

#1563 Skip import if dataset is already imported
  .github/workflows/TEST-bdd-5.yml
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/XDai/migrations/2_total_migration.js
  modules/Database/Arangojs.js
  modules/command/dc/dc-convert-to-graph-command.js
  modules/command/dc/dc-convert-to-ot-json-command.js
  modules/worker/import-worker-controller.js
  test/bdd/features/datalayer.feature
  test/bdd/features/importer.feature
  test/bdd/features/network.feature
  test/bdd/features/trail.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
  tools/local-network-setup/generate_config_files.js
Labels: internal process

#1567 Fix replication confirmation format
  modules/Blockchain.js
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/truffle.js
  modules/Blockchain/Web3Implementation/index.js
  modules/Blockchain/XDai/abi/holding.json
  modules/Blockchain/XDai/migrations/2_total_migration.js
  modules/Blockchain/XDai/truffle.js
  modules/EventEmitter.js
  modules/command/dc/dc-replication-completed-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/service/dc-service.js
  package.json
Labels: bug

#1569 Adapt truffle test to new offer confirmation format
  .github/workflows/TEST-unit.yml
  modules/Blockchain/Ethereum/contracts/TestingUtilities.sol
  modules/Blockchain/Ethereum/test/creditor.handler.test.js
  modules/Blockchain/Ethereum/test/litigation.test.js
  modules/Blockchain/Ethereum/test/metrics.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/XDai/contracts/TestingUtilities.sol
  modules/Blockchain/XDai/test/creditor.handler.test.js
  modules/Blockchain/XDai/test/litigation.test.js
  modules/Blockchain/XDai/test/metrics.test.js
  modules/Blockchain/XDai/test/offer.test.js
Labels: bug

#1570 OriginTrail Testnet Release v5.0.4
  modules/Database/Arangojs.js
  modules/migration/m9-remove-unnecessary-encryption-data.js
Labels: release

#1573 Enable staging deployment of contracts
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  modules/Blockchain/Ethereum/truffle.js
  modules/Blockchain/XDai/migrations/2_total_migration.js
  modules/Blockchain/XDai/truffle.js
  package-lock.json
  package.json
  test/docker/check_image.sh
Labels: internal process
