Repository OriginTrail/ot-node, pull requests merged in 2021-07, with the labels that each got.

#1594 Verify node identity when DC fetches offer id
  modules/command/dc/dc-offer-task-command.js
  test/modules/service/pricing-service-test.js
Labels: bug

#1593 Update get merkle proofs endpoint to support bulk requests
  modules/controller/dc-controller.js
  modules/service/rest-api-v2.js
Labels: enhancement

#1592 Add dynamic gas price for xDai blockchain
  modules/Blockchain/XDai/index.js
Labels: enhancement

#1591 Add unit bdd tests for bugs
  test/bdd/features/datalayer.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/otnode.js
  test/modules/command/dc/dc-replication-send-command.test.js
Labels: chore

#1596 Add background process for database pruning migration
  modules/migration/m9-remove-unnecessary-encryption-data-worker.js
  modules/migration/m9-remove-unnecessary-encryption-data.js
  ot-node.js
  test/modules/service/pricing-service-test.js
Labels: enhancement

#1598 Add new API route for bulk fingerprint request
  .github/workflows/TEST-docker.yml
  .travis.yml
  modules/DVService.js
  modules/controller/dv-controller.js
  modules/service/rest-api-v2.js
  test/bdd/steps/network.js
Labels: enhancement

#1599 Hotfix updates for 5.1.0 testnet release
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/XDai/index.js
  modules/constants.js
  modules/migration/m9-remove-unnecessary-encryption-data-worker.js
Labels: hotfix

#1604 Updated script for local network setup
  package.json
  tools/local-network-setup/config_template.json
  tools/local-network-setup/generate_config_files.js
  tools/local-network-setup/setup_environment.sh
Labels: bug

#1603 Update database pruning migration to be fully async
  modules/Database/Arangojs.js
  modules/migration/m9-remove-unnecessary-encryption-data-worker.js
  modules/migration/m9-remove-unnecessary-encryption-data.js
  ot-node.js
Labels: enhancement

#1605 Hotfix for Testnet Prerelease v5.1.0
  modules/Database/Arangojs.js
  modules/migration/m9-remove-unnecessary-encryption-data-worker.js
  modules/migration/m9-remove-unnecessary-encryption-data.js
  ot-node.js
  package.json
  tools/local-network-setup/config_template.json
  tools/local-network-setup/generate_config_files.js
  tools/local-network-setup/setup_environment.sh
Labels: release
