Repository OriginTrail/ot-node, pull requests merged in 2021-02, with the labels that each got.

#1440 Bug fixed when offer id is not returned correctly on export request
  modules/command/common/export-data-command.js
Labels: bug

#1447 Branch leveling
  modules/command/dh/dh-replication-import-command.js
  modules/controller/dc-controller.js
  modules/worker/validate-received-replication-worker.js
  test/bdd/features/importer.feature
Labels: internal process

#1448 Resolved issue when trying to replicate big datasets
  modules/worker/create-replication-data-worker.js
Labels: bug

#1437 Adapt transactions in ethereum/index.js
  .travis.yml
  modules/Blockchain/Ethereum/index.js
  test/bdd/steps/lib/local-blockchain.js
  test/docker/getHubAddress.js
  test/modules/transactions.test.js
Labels: chore

#1454 Skip autoupdate if next version is 5.0.0
  modules/command/common/autoupdater-command.js
Labels: minor

#1457 Version bump to 4.1.17
  package.json
Labels: minor

#1455 Adding ot-node version 5 migration scripts
  scripts/generate_v5_configuration.js
  scripts/migrate_to_v5.sh
  scripts/start_v5_update.js
Labels: enhancement

#1458 OriginTrail Testnet Prerelease v4.1.17
  modules/command/common/autoupdater-command.js
  modules/command/common/export-data-command.js
  modules/worker/create-replication-data-worker.js
  package.json
  scripts/generate_v5_configuration.js
  scripts/migrate_to_v5.sh
  scripts/start_v5_update.js
  test/bdd/features/importer.feature
Labels: release

#1459 OriginTrail Testnet Release v4.1.17
  modules/command/common/autoupdater-command.js
  modules/command/common/export-data-command.js
  modules/worker/create-replication-data-worker.js
  package.json
  scripts/generate_v5_configuration.js
  scripts/migrate_to_v5.sh
  scripts/start_v5_update.js
Labels: release

#1464 Rename eth_price to base_currency_price
  config/config.json
  migrations/202102261114123-update-offers-rename-price.js
  models/offers.js
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Web3Implementation/index.js
  modules/Blockchain/XDai/index.js
  modules/ImportUtilities.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/service/dc-service.js
  modules/service/pricing-service.js
  modules/service/rest-api-v2.js
  test/bdd/steps/network.js
  test/modules/utilities.test.js
Labels: breaking change, enhancement

#1463 Removed wallets configuration from warp network instructions
  WARP_TESTNET_SETUP_INSTRUCTIONS.md
Labels: minor
