Repository OriginTrail/ot-node, pull requests merged in 2021-05, with the labels that each got.

#1527 Fix output for the number of nodes that a query was sent to
  modules/network/kademlia/kademlia.js
Labels: internal process

#1528 Add a full permissioned data BDD test
  package.json
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
Labels: internal process

#1532 Validate DC proof in all litigation scenarios
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/contracts/TestingUtilities.sol
  modules/Blockchain/Ethereum/test/creditor.handler.test.js
  modules/Blockchain/Ethereum/test/litigation.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/XDai/contracts/Litigation.sol
  modules/Blockchain/XDai/contracts/TestingUtilities.sol
  modules/Blockchain/XDai/test/creditor.handler.test.js
  modules/Blockchain/XDai/test/litigation.test.js
  modules/Blockchain/XDai/test/offer.test.js
Labels: bug

#1537 Add profileService to payoutMigration arguments
  ot-node.js
Labels: bug

#1538 Remove arango artifacts after completing restore process
  scripts/restore.sh
Labels: bug

#1536 Added github action for tests
  .github/workflows/TEST-bdd-1.yml
  .github/workflows/TEST-bdd-2.yml
  .github/workflows/TEST-bdd-3.yml
  .github/workflows/TEST-bdd-4.yml
  .github/workflows/TEST-bdd-5.yml
  .github/workflows/TEST-docker.yml
  .github/workflows/TEST-truffle.yml
  .github/workflows/TEST-unit.yml
  test/docker/check_image.sh
Labels: internal process

#1533 Missed offer migration bugfix
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/constants.js
  modules/migration/m8-missed-offer-check-migration.js
  ot-node.js
Labels: bug

#1540 Increase version number
  package-lock.json
  package.json
Labels: minor

#1542 Add quotation marks to arango password in restore script
  scripts/restore.sh
Labels: hotfix

#1545 Updated dependency in package-lock.json for nat-pmp library
  package-lock.json
Labels: bug

#1546 Update dependency for deleted kadence library
  package-lock.json
Labels: hotfix

#1547 OriginTrail Release v5.0.3
  .github/workflows/TEST-bdd-1.yml
  .github/workflows/TEST-bdd-2.yml
  .github/workflows/TEST-bdd-3.yml
  .github/workflows/TEST-bdd-4.yml
  .github/workflows/TEST-bdd-5.yml
  .github/workflows/TEST-docker.yml
  .github/workflows/TEST-truffle.yml
  .github/workflows/TEST-unit.yml
  config/config.json
  migrations/202104201448123-update-offers-add-replication-timestamp.js
  migrations/202104201448124-create-pruning-history.js
  models/offers.js
  models/pruning_history.js
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/Litigation.sol
  modules/Blockchain/Ethereum/contracts/TestingUtilities.sol
  modules/Blockchain/Ethereum/test/creditor.handler.test.js
  modules/Blockchain/Ethereum/test/litigation.test.js
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/XDai/contracts/Holding.sol
  modules/Blockchain/XDai/contracts/Litigation.sol
  modules/Blockchain/XDai/contracts/TestingUtilities.sol
  modules/Blockchain/XDai/test/creditor.handler.test.js
  modules/Blockchain/XDai/test/litigation.test.js
  modules/Blockchain/XDai/test/offer.test.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/command/common/autoupdater-command.js
  modules/command/common/dataset-pruning-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/constants.js
  modules/migration/m8-missed-offer-check-migration.js
  modules/network/kademlia/kademlia.js
  modules/service/dataset-pruning-service.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  modules/worker/dataset-pruning-worker.js
  ot-node.js
  package-lock.json
  package.json
  scripts/backup.js
  scripts/restore.js
  scripts/restore.sh
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/network.js
  test/docker/check_image.sh
  test/modules/command/common/autoupdater-command.test.js
  test/modules/service/dataset-pruning-service-test.js
  test/modules/service/pricing-service-test.js
  test/modules/utilities.test.js
Labels: release

#1549 Update develop with v5.0.3 hotfixes
  migrations/202104201448124-create-pruning-history.js
  models/pruning_history.js
  modules/command/common/dataset-pruning-command.js
  modules/migration/m8-missed-offer-check-migration.js
  modules/service/dataset-pruning-service.js
  modules/worker/dataset-pruning-worker.js
  package-lock.json
  scripts/backup.js
  scripts/restore.sh
Labels: internal process

#1541 Setup truffle test job in actions
  .github/workflows/TEST-docker.yml
  .github/workflows/TEST-truffle.yml
  .github/workflows/TEST-unit.yml
  origintrail_noderc.image
  test/docker/check_image.sh
  test/docker/getHubAddress.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
  test/modules/graph.test.js
  test/modules/graphstorage.test.js
  test/modules/gs1-importer.test.js
  test/modules/test-utilities.js
Labels: internal process

#1551 Add Local Network Setup tool
  .gitignore
  README.md
  config/config.json
  modules/Blockchain/Ethereum/migrations/2_total_migration.js
  package.json
  test/bdd/steps/blockchain.js
  tools/local-network-setup/Readme.md
  tools/local-network-setup/config_template.json
  tools/local-network-setup/generate_config_files.js
  tools/local-network-setup/pregenerated-values/dc_network_identity.json
  tools/local-network-setup/pregenerated-values/kademlia.crt
  tools/local-network-setup/pregenerated-values/kademlia.key
  tools/local-network-setup/pregenerated-values/wallets.json
  tools/local-network-setup/setup_environment.sh
Labels: enhancement

#1560 Use proper wallet for offer confirmation signing
  modules/EventEmitter.js
  modules/command/dc/dc-replication-completed-command.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/constants.js
Labels: bug

#1559 Add and improve checks for multiple replication avoidance
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-offer-handle-command.js
  modules/command/dh/dh-replication-timeout-command.js
  modules/controller/dh-controller.js
Labels: bug

#1562 Fix appending excluded DHs to exclusion array
  modules/command/dc/dc-offer-finalize-command.js
Labels: bug

#1558 DH blockchain events processing moved to command
  migrations/202105241126105-remove-obsolete-permanent-commands.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/command/dh/dh-litigation-initiated-command.js
  modules/command/dh/dh-offer-finalized-command.js
  modules/command/dh/dh-process-blockchain-events-command.js
  modules/constants.js
  modules/migration/m9-remove-unnecessary-encryption-data.js
  modules/service/dh-service.js
  ot-node.js
Labels: bug
