Repository OriginTrail/ot-node, pull requests merged in 2021-04, with the labels that each got.

#1510 Fix duplicated blockchain event fetching
  migrations/202010201032128-update-events-add-blockchain-id.js
  migrations/202011261221123-update-offers-add-blockchain-id.js
  migrations/202011261243123-update-bids-add-blockchain-id.js
  migrations/202011261416123-update-data-info-extend-data-provider-wallet.js
  migrations/202011301208123-update-data-sellers-add-blockchain-id.js
  migrations/202011301210123-update-data-trades-add-blockchain-id.js
  migrations/202012090818123-update-purchased-data-add-blockchain-id.js
  migrations/202012151048123-update-challenges-add-blockchain-id.js
  migrations/202102120853043-update-commands-add-blockchain-id.js
  modules/Blockchain.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/logger.js
  modules/service/dh-service.js
  modules/worker/export-worker.js
  package.json
Labels: bug, hotfix

#1512 OriginTrail Release v5.0.1
  modules/Blockchain.js
  modules/service/dh-service.js
  package.json
Labels: release

#1516 Level develop with release mainnet
  modules/Blockchain.js
  modules/service/dh-service.js
  package.json
Labels: chore, minor

#1517 Fix pricing service unit test
  test/modules/service/pricing-service-test.js
Labels: bug, internal process, minor

#1515 Dataset pruning feature
  config/config.json
  migrations/202104151212123-create-pruning-history.js
  models/pruning_history.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/command/common/dataset-pruning-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/service/dataset-pruning-service.js
  modules/service/dh-service.js
  modules/worker/dataset-pruning-worker.js
  package-lock.json
  package.json
  test/modules/service/dataset-pruning-service-test.js
  test/modules/utilities.test.js
Labels: enhancement

#1513 Prevent the possibility of calculated offer price being a decimal value
  modules/service/pricing-service.js
Labels: bug

#1518 Handle offer payout if blockchain_id is not specified
  modules/command/dh/dh-pay-out-command.js
Labels: bug

#1507 Add migration files to backup and restore scripts
  scripts/backup.js
  scripts/restore.js
Labels: bug

#1520 Add a delay to replication data send command
  migrations/202104201448123-update-offers-add-replication-timestamp.js
  models/offers.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dc/dc-replication-send-command.js
  modules/constants.js
  modules/service/dc-service.js
Labels: enhancement

#1522 Fix missed temporary changes on ot-node
  config/config.json
  modules/command/dc/dc-replication-send-command.js
  modules/constants.js
Labels: minor

#1521 OriginTrail Testnet Prerelease v5.0.2
  config/config.json
  migrations/202010201032128-update-events-add-blockchain-id.js
  migrations/202011261221123-update-offers-add-blockchain-id.js
  migrations/202011261243123-update-bids-add-blockchain-id.js
  migrations/202011261416123-update-data-info-extend-data-provider-wallet.js
  migrations/202011301208123-update-data-sellers-add-blockchain-id.js
  migrations/202011301210123-update-data-trades-add-blockchain-id.js
  migrations/202012090818123-update-purchased-data-add-blockchain-id.js
  migrations/202012151048123-update-challenges-add-blockchain-id.js
  migrations/202102120853043-update-commands-add-blockchain-id.js
  migrations/202104151212123-create-pruning-history.js
  migrations/202104201448123-update-offers-add-replication-timestamp.js
  models/offers.js
  models/pruning_history.js
  modules/Blockchain.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/command/common/autoupdater-command.js
  modules/command/common/dataset-pruning-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/logger.js
  modules/service/dataset-pruning-service.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  modules/worker/dataset-pruning-worker.js
  modules/worker/export-worker.js
  package-lock.json
  package.json
  scripts/backup.js
  scripts/restore.js
  test/modules/command/common/autoupdater-command.test.js
  test/modules/service/dataset-pruning-service-test.js
  test/modules/service/pricing-service-test.js
  test/modules/utilities.test.js
Labels: release

#1526 Fix how migrations directory is read during backup
  scripts/backup.js
Labels: hotfix

#1523 OriginTrail Testnet Release v5.0.2
  config/config.json
  migrations/202010201032128-update-events-add-blockchain-id.js
  migrations/202011261221123-update-offers-add-blockchain-id.js
  migrations/202011261243123-update-bids-add-blockchain-id.js
  migrations/202011261416123-update-data-info-extend-data-provider-wallet.js
  migrations/202011301208123-update-data-sellers-add-blockchain-id.js
  migrations/202011301210123-update-data-trades-add-blockchain-id.js
  migrations/202012090818123-update-purchased-data-add-blockchain-id.js
  migrations/202012151048123-update-challenges-add-blockchain-id.js
  migrations/202102120853043-update-commands-add-blockchain-id.js
  migrations/202104201448123-update-offers-add-replication-timestamp.js
  migrations/202104201448124-create-pruning-history.js
  models/offers.js
  models/pruning_history.js
  modules/Blockchain.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/ImportUtilities.js
  modules/OtJsonUtilities.js
  modules/command/common/autoupdater-command.js
  modules/command/common/dataset-pruning-command.js
  modules/command/dc/dc-offer-finalized-command.js
  modules/command/dc/dc-offer-task-command.js
  modules/command/dc/dc-replication-send-command.js
  modules/command/dh/dh-pay-out-command.js
  modules/constants.js
  modules/logger.js
  modules/service/dataset-pruning-service.js
  modules/service/dc-service.js
  modules/service/dh-service.js
  modules/service/pricing-service.js
  modules/worker/dataset-pruning-worker.js
  modules/worker/export-worker.js
  package-lock.json
  package.json
  scripts/backup.js
  scripts/restore.js
  test/modules/command/common/autoupdater-command.test.js
  test/modules/service/dataset-pruning-service-test.js
  test/modules/service/pricing-service-test.js
  test/modules/utilities.test.js
Labels: release

#1531 Add check for offer to disable finalizing an offer twice
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/test/offer.test.js
  modules/Blockchain/XDai/contracts/Holding.sol
  modules/Blockchain/XDai/test/offer.test.js
Labels: bug
