Repository OriginTrail/ot-node, pull requests merged in 2021-01, with the labels that each got.

#1423 Dh replication command is not executed in child process
  modules/command/dh/dh-replication-import-command.js
  modules/worker/validate-received-replication-worker.js
Labels: hotfix

#1425 Hotfix: Dh replication command is not executed in child process (#1423)
  modules/command/dh/dh-replication-import-command.js
  modules/worker/validate-received-replication-worker.js
Labels: hotfix

#1426 Hotfix: Dh replication command is not executed in child process
  modules/command/dh/dh-replication-import-command.js
  modules/worker/validate-received-replication-worker.js
Labels: hotfix

#1421 OriginTrail Release v4.1.15
  importers/json_examples/local-query1.json
  importers/json_examples/local-query2.json
  modules/Blockchain/Ethereum/abi/holding.json
  modules/Blockchain/Ethereum/contracts/Holding.sol
  modules/Blockchain/Ethereum/contracts/HoldingStorage.sol
  modules/Blockchain/Ethereum/index.js
  modules/Blockchain/Ethereum/test/holding.storage.test.js
  modules/Database/Arangojs.js
  modules/Database/GraphStorage.js
  modules/EventEmitter.js
  modules/Product.js
  modules/command/dc/dc-offer-create-db-command.js
  modules/command/dc/dc-offer-prepare-command.js
  modules/command/dh/dh-replication-import-command.js
  modules/controller/dc-controller.js
  modules/service/challenge-service.js
  modules/service/import-service.js
  modules/service/permissioned-data-service.js
  modules/service/replication-service.js
  modules/service/rest-api-v2.js
  modules/service/trac-price-service.js
  modules/validator/object-validator.js
  modules/worker/create-replication-data-worker.js
  package.json
  test/bdd/features/datalayer.feature
  test/bdd/features/importer.feature
  test/bdd/features/permissioned_data.feature
  test/bdd/steps/endpoints.js
  test/bdd/steps/lib/http-api-helper.js
  test/bdd/steps/lib/otnode.js
  test/bdd/steps/network.js
  test/modules/command/dc/dc-offer-create-database-command.test.js
Labels: release

#1428 Reduce the gas limit for answerLitigation
  modules/Blockchain/Ethereum/index.js
  modules/constants.js
Labels: chore

#1431 Fix minor issues in blockchain service
  config/config.json
  modules/service/profile-service.js
Labels: bug

#1430 Resolve replication bug when node doesn't have enough tokens
  modules/command/dc/dc-offer-prepare-command.js
  modules/service/rest-api-v2.js
Labels: bug

#1432 4.1.16 version bump
  package.json
Labels: minor
