Repository OriginTrail/ot-node, pull requests merged in 2021-08, with the labels that each got.

#1609 Removing permissioned data before calculating merkle proofs
  modules/service/import-service.js
Labels: bug

#1602 Create bulk API routes for cryptographic proofs
  modules/DVService.js
  modules/command/common/trail-cleaner-command.js
  modules/command/dc/dc-merkle-proofs-command.js
  modules/command/dh/dh-bulk-fingerprint-command.js
  modules/command/dh/dh-find-trail-command.js
  modules/constants.js
  modules/controller/dc-controller.js
  modules/controller/dh-controller.js
  modules/controller/dv-controller.js
  modules/service/dh-service.js
  modules/service/rest-api-v2.js
  test/bdd/features/datalayer.feature
  test/bdd/steps/network.js
Labels: enhancement

#1621 Hotfix for dataset pruning command
  modules/service/dataset-pruning-service.js
Labels: hotfix
