Repository OriginTrail/ot-node, pull requests merged in 2022-12, with the labels that each got.

#2211 get bid suggestion data from query params
  src/controllers/http-api/bid-suggestion-http-api-controller.js
Labels: bug, v6

#2206 fix big number calculations
  dependencies.md
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/constants/constants.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/publish-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
Labels: bug, v6

#2209 move triple store files to /root/ot-node
  installer/data/blazegraph.service
  installer/data/fuseki.service
  installer/data/graphdb.service
  installer/installer.sh
Labels: v6

#2208 Added retry logic for transaction not mined error
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore

#2212 Initial stake and ask amount moved in configuration
  config/config.json
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore

#2210 validate get assertion response
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.1/v1-0-1-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/commands/protocols/publish/sender/validate-assertion-command.js
  src/service/operation-service.js
  src/service/publish-service.js
Labels: v6

#2213 drop database using sequelize
  tools/local-network-setup/generate-config-files.js
Labels: bug, v6

#2214 update blockchain module according to new contracts
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/commands/protocols/publish/sender/validate-assertion-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
  src/service/ual-service.js
Labels: v6

#2215 handle store request improvement
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/commands/protocols/publish/sender/v1.0.2/v1-0-2-publish-request-command.js
  src/controllers/rpc/publish-rpc-controller.js
  src/service/operation-service.js
Labels: v6

#2216 Added clean operational database migration
  ot-node.js
  src/migration/clean-operational-database-migration.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
Labels: chore

#2217 update contracts
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/modules/validation/implementation/merkle-validation.js
  src/modules/validation/validation-module-manager.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
  test/bdd/steps/lib/local-blockchain.mjs
  test/utilities/dkg-client-helper.mjs
Labels: bug, v6

#2219 remove sharding table migration and move operationaldb migration
  ot-node.js
Labels: bug, v6

#2220 add version to service agreement contract
  package-lock.json
  package.json
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/service-agreement-service.js
  test/bdd/steps/lib/local-blockchain.mjs
Labels: chore, v6

#2221 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2222 merge v6/develop into v6/development-network
  config/config.json
  dependencies.md
  installer/data/blazegraph.service
  installer/data/fuseki.service
  installer/data/graphdb.service
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.1/v1-0-1-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/v1.0.2/v1-0-2-publish-request-command.js
  src/commands/protocols/publish/sender/validate-assertion-command.js
  src/constants/constants.js
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/controllers/rpc/publish-rpc-controller.js
  src/migration/clean-operational-database-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/modules/validation/implementation/merkle-validation.js
  src/modules/validation/validation-module-manager.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
  src/service/ual-service.js
  test/bdd/steps/lib/local-blockchain.mjs
  test/utilities/dkg-client-helper.mjs
  tools/local-network-setup/generate-config-files.js
Labels: v6

#2223 fixes, bump version
  ot-node.js
  package.json
  src/service/sharding-table-service.js
Labels: bug, v6

#2224 update package-lock
  package-lock.json
Labels: chore, v6

#2225 merge v6/develop into v6/development-network
  ot-node.js
  package-lock.json
  package.json
  src/service/sharding-table-service.js
Labels: v6

#2230 Reworked node scripts using ethers.js
  config/config.json
  ot-node.js
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  scripts/utils.js
Labels: improvement, v6

#2234 fix migration not saved to file
  ot-node.js
  src/migration/clean-operational-database-migration.js
Labels: bug, v6

#2235 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2236 OriginTrail 6.0.0-beta.3.1.1 Testnet Release
  ot-node.js
  package-lock.json
  package.json
  src/migration/clean-operational-database-migration.js
Labels: hotfix, release, v6

#2238 increase gas price for scripts
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
Labels: bug, v6

#2241 increase gas price, bump version
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
Labels: bug, v6

#2242 OriginTrail 6.0.0-beta.3.1.2 Testnet Release
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
Labels: hotfix, release, v6

#2245 normalize nquads before proof calculation
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
Labels: bug, v6

#2247 Testnet hotfix 6.0.0-beta.3.1.3
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2249 update ual according to specification
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/ual-service.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: v6

#2251 don't restart after migration in development
  ot-node.js
Labels: bug, v6

#2253 update rpc endpoints and hub address, bump version
  config/config.json
  package-lock.json
  package.json
Labels: chore, v6

#2254 OriginTrail 6.0.0-beta.3.1.4 Testnet Release
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/ual-service.js
  test/bdd/steps/lib/local-blockchain.mjs
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release, v6

#2258 OriginTrail 6.0.0-beta.3.1.5 Testnet Release Hotfix
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: hotfix, release, v6

#2259 InstallerV2: Added mariadb support, Arch Linux support, always download latest stable fuseki, bug fix, node/triplestore/sql checks, reduced verbosity
  installer/installer.sh
Labels: feature, v6

#2263 OriginTrail 6.0.0-beta.3.1.6 Testnet Release Hotfix
  installer/installer.sh
  ot-node.js
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/constants/constants.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2269 OriginTrail 6.0.0-beta.3.1.8 Testnet Release Hotfix
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2272 fix local network setup
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: bug, v6

#2277 convert bid suggestion to wei
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/service/sharding-table-service.js
Labels: bug, v6

#2278 V6/improvement/network message logs
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/modules/network/implementation/libp2p-service.js
  src/service/get-service.js
  src/service/operation-service.js
  src/service/publish-service.js
Labels: bug, v6

#2267 Refactor of mapping script
  package-lock.json
  package.json
  tools/substrate-accounts-mapping/README.md
  tools/substrate-accounts-mapping/accounts-mapping.js
Labels: chore

#2282 revert dependencies versions
  package-lock.json
  package.json
Labels: bug, v6

#2284 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2283 OriginTrail 6.0.0-beta.3.1.10 Testnet Release Hotfix
  package-lock.json
  package.json
Labels: hotfix, release, v6

#2285 revert blockchain queue changes
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2286 V6/version bump
  package-lock.json
  package.json
Labels: chore, v6

#2287 OriginTrail 6.0.0-beta.3.1.12 Testnet Release
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release, v6

#2288 bump comunica version
  package-lock.json
  package.json
Labels: dependencies, v6

#2291 OriginTrail 6.0.0-beta.3.1.13 Testnet Release
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  test/bdd/steps/lib/local-blockchain.mjs
Labels: release, v6

#2293 suggest bid based on 75th percentile
  ot-node.js
  src/service/sharding-table-service.js
Labels: improvement, v6

#2292 Remove old store protocols and set 1.0.2. To 1.0.0
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.1/v1-0-1-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.1/v1-0-1-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/commands/protocols/publish/sender/v1.0.1/v1-0-1-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.1/v1-0-1-publish-request-command.js
  src/commands/protocols/publish/sender/v1.0.2/v1-0-2-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.2/v1-0-2-publish-request-command.js
  src/constants/constants.js
  src/controllers/rpc/publish-rpc-controller.js
Labels: breaking change, v6

#2294 OriginTrail 6.0.0-beta.3.1.14 Testnet Release
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.1/v1-0-1-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.1/v1-0-1-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/commands/protocols/publish/sender/v1.0.1/v1-0-1-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.1/v1-0-1-publish-request-command.js
  src/commands/protocols/publish/sender/v1.0.2/v1-0-2-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.2/v1-0-2-publish-request-command.js
  src/constants/constants.js
  src/controllers/rpc/publish-rpc-controller.js
  src/service/sharding-table-service.js
Labels: release, v6

#2296 remove peers length from divisors
  dependencies.md
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/constants/constants.js
  src/service/sharding-table-service.js
Labels: bug, v6

#2297 Fixes according to contracts changes
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  test/bdd/steps/lib/local-blockchain.mjs
Labels: v6

#2301 OriginTrail 6.0.0-beta.3.1.15 Testnet Release
  config/config.json
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/constants/constants.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20221214110050-update-commands-types.js
  src/modules/repository/implementation/sequelize/models/commands.js
  src/service/sharding-table-service.js
  test/bdd/steps/lib/local-blockchain.mjs
  tools/local-network-setup/generate-config-files.js
Labels: release, v6

#2302 remove migration, add new hub contract address, bump version
  config/config.json
  ot-node.js
  package-lock.json
  package.json
Labels: chore, v6

#2303 OriginTrail 6.0.0 Testnet Release
  config/config.json
  ot-node.js
  package-lock.json
  package.json
Labels: release, v6

#2307 update env and branch to mainnet
  installer/README.md
  installer/installer.sh
Labels: v6

#2306 timeout network messages
  dependencies.md
  package-lock.json
  package.json
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/constants/constants.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
Labels: improvement, v6

#2260 add arch file dependency to installerv2
  installer/data/archlinux
Labels: improvement, v6

#2311 V6/bid suggestion args validation
  scripts/set-ask.js
  scripts/set-stake.js
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/request-schema/bid-suggestion-schema.js
  src/controllers/http-api/request-schema/publish-schema.js
  src/controllers/http-api/request-schema/search-schema.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/request-validation-middleware.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/event-emitter-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
Labels: improvement, v6

#2304 better handling of invalid messages
  dependencies.md
  package-lock.json
  package.json
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/constants/constants.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/data-service.js
Labels: improvement, v6

#2305 add migration for values types in event table
  src/modules/repository/implementation/sequelize/migrations/20221215130500-update-event-types.js
  src/modules/repository/implementation/sequelize/models/event.js
Labels: bug, v6

#2315 Increase timeout, limit hashFunctionId values, bump the version
  package-lock.json
  package.json
  src/constants/constants.js
  src/controllers/http-api/request-schema/bid-suggestion-schema.js
Labels: improvement

#2317 OriginTrail 6.0.1 Devnet Releas
  dependencies.md
  installer/data/archlinux
  installer/installer.sh
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/constants/constants.js
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/request-schema/bid-suggestion-schema.js
  src/controllers/http-api/request-schema/publish-schema.js
  src/controllers/http-api/request-schema/search-schema.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/request-validation-middleware.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20221215130500-update-event-types.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/data-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/event-emitter-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
Labels: release, v6

#2314 Fix failing bdd tests
  .github/workflows/TEST-bdd.yml
  config/config.json
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/modules/network/implementation/libp2p-service.js
  test/bdd/features/get-errors.feature
  test/bdd/steps/api/resolve.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/lib/local-blockchain.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
  tools/local-network-setup/generate-config-files.js
Labels: bug

#2321 OriginTrail 6.0.1 Testnet Prerelease
  dependencies.md
  installer/data/archlinux
  installer/installer.sh
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/constants/constants.js
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/request-schema/bid-suggestion-schema.js
  src/controllers/http-api/request-schema/publish-schema.js
  src/controllers/http-api/request-schema/search-schema.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/request-validation-middleware.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20221215130500-update-event-types.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/data-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/event-emitter-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
Labels: release, v6

#2322 OriginTrail 6.0.1 Testnet Release
  dependencies.md
  installer/data/archlinux
  installer/installer.sh
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/constants/constants.js
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/request-schema/bid-suggestion-schema.js
  src/controllers/http-api/request-schema/publish-schema.js
  src/controllers/http-api/request-schema/search-schema.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/request-validation-middleware.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20221215130500-update-event-types.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/data-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/event-emitter-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
Labels: release, v6

#2323 OriginTrail 6.0.1 Mainnet Release
  dependencies.md
  installer/data/archlinux
  installer/installer.sh
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/constants/constants.js
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/request-schema/bid-suggestion-schema.js
  src/controllers/http-api/request-schema/publish-schema.js
  src/controllers/http-api/request-schema/search-schema.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/request-validation-middleware.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20221215130500-update-event-types.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/data-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/event-emitter-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
Labels: release, v6
