Repository OriginTrail/ot-node, pull requests merged in 2022-02, with the labels that each got.

#1729 add replication factor to config
  config/config.json
Labels: hotfix, v6

#1730 Remove file type from publishing keywords and set telemetry plugin version
  modules/controller/rpc-controller.js
  modules/service/publish-service.js
  package.json
Labels: hotfix, v6

#1731 OriginTrail 6.0.0-beta.1.22 Testnet Prerelease
  config/config.json
  modules/controller/rpc-controller.js
  modules/service/publish-service.js
  package.json
Labels: release, v6

#1732 OriginTrail 6.0.0-beta.1.22 Testnet Release
  config/config.json
  modules/controller/rpc-controller.js
  modules/service/publish-service.js
  package.json
Labels: release, v6

#1737 Refactor graph and API layer
  external/graphdb-service.js
  index.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/dependency-injection.js
  modules/service/publish-service.js
  modules/service/query-service.js
  modules/utilities.js
  modules/worker/l1-worker.js
  modules/worker/worker-pool.js
  package.json
  postman/DKGv6.postman_collection.json
Labels: improvement, breaking change, feature

#1740 Fix load parameter in /resolve endpoint
  modules/controller/rpc-controller.js
Labels: bug

#1741 Fix query for latest asset state
  external/graphdb-service.js
Labels: bug

#1738 Blazegraph implementation
  config/config.json
  external/blazegraph-service.js
  external/graphdb-service.js
  modules/command/command-executor.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/logger/logger.js
  modules/service/data-service.js
  modules/service/publish-service.js
  ot-node.js
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
Labels: feature, v6

#1736 V6/develop - Add system service, add Ubuntu versions that are acceptable, fix display log command
  installer/data/otnode.service
  installer/installer.sh
Labels: improvement, v6

#1744 OriginTrail 6.0.0-beta.1.23 Testnet Prerelease
  config/config.json
  external/blazegraph-service.js
  external/graphdb-service.js
  index.js
  installer/data/graphdb.service
  installer/data/otnode.service
  installer/installer.sh
  modules/command/command-executor.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/logger/logger.js
  modules/service/data-service.js
  modules/service/dependency-injection.js
  modules/service/publish-service.js
  modules/service/query-service.js
  modules/utilities.js
  modules/worker/l1-worker.js
  modules/worker/worker-pool.js
  ot-node.js
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
Labels: breaking change, v6

#1752 Blockchain integration and additional bugfixes for prerelase 1.23 version
  .gitignore
  build/contracts/DKGcontract.json
  build/contracts/Migrations.json
  build/contracts/OwnershipManager.json
  build/contracts/UAIRegistry.json
  config/config.json
  external/web3-blockchain-service.js
  frameDocuments/nft.json
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/blockchain-service.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  postman/DKGv6.postman_collection.json
Labels: improvement, feature, v6

#1753 OriginTrail 6.0.0-beta.1.23 Testnet Release
  .gitignore
  build/contracts/DKGcontract.json
  build/contracts/Migrations.json
  build/contracts/OwnershipManager.json
  build/contracts/UAIRegistry.json
  config/config.json
  external/blazegraph-service.js
  external/graphdb-service.js
  external/web3-blockchain-service.js
  frameDocuments/nft.json
  index.js
  installer/data/graphdb.service
  installer/data/otnode.service
  installer/installer.sh
  modules/command/command-executor.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/logger/logger.js
  modules/service/blockchain-service.js
  modules/service/data-service.js
  modules/service/dependency-injection.js
  modules/service/publish-service.js
  modules/service/query-service.js
  modules/utilities.js
  modules/worker/l1-worker.js
  modules/worker/worker-pool.js
  ot-node.js
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
Labels: breaking change, release, v6

#1764 add frame document
  frameDocuments/erc721.json
  frameDocuments/nft.json
  modules/constants.js
  modules/service/data-service.js
Labels: improvement

#1765 Fix frame document
  modules/service/data-service.js
Labels: bug

#1766 LibP2P streams fix and moving json processing to worker pool
  external/libp2p-service.js
  modules/service/network-service.js
  modules/service/query-service.js
  package-lock.json
Labels: improvement, v6

#1770 Update resolve endpoint to handle pending tasks
  external/blazegraph-service.js
  external/graphdb-service.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/query-service.js
Labels: bug, improvement

#1768 Simplified blazegraph install + added restart on failure
  installer/data/blazegraph.service
  installer/data/otnode.service
  installer/installer.sh
Labels: improvement, v6

#1772 Fix compatibility issues with old versions
  external/blazegraph-service.js
  external/libp2p-service.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/file-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  package.json
  tools/local-network-setup/.bootstrap_origintrail_noderc
Labels: improvement, v6

#1775 OriginTrail 6.0.0-beta.1.24 Testnet Prerelease
  external/blazegraph-service.js
  external/graphdb-service.js
  external/libp2p-service.js
  frameDocuments/erc721.json
  frameDocuments/nft.json
  installer/data/blazegraph.service
  installer/data/otnode.service
  installer/installer.sh
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/file-service.js
  modules/service/network-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  package-lock.json
  package.json
  tools/local-network-setup/.bootstrap_origintrail_noderc
Labels: v6

#1777 Fix blazegraph transforming nquads with two blank nodes
  external/blazegraph-service.js
Labels: improvement

#1778 Add queue for blockchain transactions
  modules/command/common/send-telemetry-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/logger/logger.js
  modules/service/publish-service.js
  ot-node.js
  package.json
Labels: improvement, feature

#1779 OriginTrail 6.0.0-beta.1.25 Testnet Prerelease
  external/blazegraph-service.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/logger/logger.js
  modules/service/publish-service.js
  ot-node.js
  package.json
Labels: v6

#1781 OriginTrail 6.0.0-beta.1.25 Testnet Release
  external/blazegraph-service.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/logger/logger.js
  modules/service/publish-service.js
  ot-node.js
  package.json
Labels: release, v6

#1782 Add gas price from oracle
  external/web3-blockchain-service.js
Labels: improvement

#1788 Disable oracle gas price
  external/web3-blockchain-service.js
Labels: bug
