Repository OriginTrail/ot-node, pull requests merged in 2022-08, with the labels that each got.

#1998 update schema types according to new swagger
  src/constants/constants.js
  src/controller/http-api-router.js
  src/controller/v1/get-controller.js
  src/controller/v1/publish-controller.js
  src/controller/v1/request-schema/get-schema.js
  src/controller/v1/request-schema/publish-request.js
  src/controller/v1/request-schema/publish-schema.js
  src/controller/v1/request-schema/search-schema.js
  src/service/json-schema-service.js
Labels: v6

#1999 fixes to config files and merge issues
  config/config.json
  src/controller/v1/publish-controller.js
  src/service/operation-service.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
Labels: bug, v6

#2003 avoid inserting duplicate assertions
  src/commands/protocols/get/receiver/handle-get-init-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/modules/validation/implementation/merkle-validation.js
  src/service/get-service.js
  src/service/publish-service.js
Labels: bug, v6

#2004 remove sync operations
  index.js
  ot-node.js
  src/modules/auto-updater/implementation/ot-auto-updater.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
Labels: improvement, v6

#2007 update assertion-tools and dkg-onchain-module
  ot-node.js
  package-lock.json
  package.json
  src/modules/blockchain/implementation/build/contracts/AssertionRegistry.json
  src/modules/blockchain/implementation/build/contracts/AssetRegistry.json
  src/modules/blockchain/implementation/build/contracts/ByteArr.json
  src/modules/blockchain/implementation/build/contracts/Context.json
  src/modules/blockchain/implementation/build/contracts/DKGcontract.json
  src/modules/blockchain/implementation/build/contracts/ERC20Token.json
  src/modules/blockchain/implementation/build/contracts/ERC734.json
  src/modules/blockchain/implementation/build/contracts/Hub.json
  src/modules/blockchain/implementation/build/contracts/IERC1155.json
  src/modules/blockchain/implementation/build/contracts/IERC165.json
  src/modules/blockchain/implementation/build/contracts/IERC20.json
  src/modules/blockchain/implementation/build/contracts/IERC721.json
  src/modules/blockchain/implementation/build/contracts/Identity.json
  src/modules/blockchain/implementation/build/contracts/Migrations.json
  src/modules/blockchain/implementation/build/contracts/Ownable.json
  src/modules/blockchain/implementation/build/contracts/OwnershipManager.json
  src/modules/blockchain/implementation/build/contracts/Profile.json
  src/modules/blockchain/implementation/build/contracts/ProfileStorage.json
  src/modules/blockchain/implementation/build/contracts/SafeMath.json
  src/modules/blockchain/implementation/build/contracts/UAIRegistry.json
  src/modules/blockchain/implementation/web3-service.js
  src/modules/validation/implementation/merkle-validation.js
  src/service/publish-service.js
Labels: improvement, v6

#2006 update installer according to new config
  installer/installer.sh
Labels: v6

#2015 V6/bug fix/websocket
  package.json
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2016 set version to 6.0.0-beta.2.0
  package.json
Labels: v6

#2011 Bdd publish happy path test implemented
  .eslintrc.js
  .github/workflows/TEST-release.yml
  .github/workflows/TEST-unit.yml
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/handle-store-request-command.js
  src/service/publish-service.js
  src/service/util/jwt-util.js
  test/bdd/features/publish-errors.feature
  test/bdd/features/release.feature
  test/bdd/steps/api/datasets/requests.json
  test/bdd/steps/api/publish.js
  test/bdd/steps/api/resolve.js
  test/bdd/steps/common.js
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/config/origintrail-test-node-config.json
  test/bdd/steps/hooks.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/ot-node-process.js
  test/unit/sparlql-query-service.test.js
  test/utilities/dkg-client-helper.js
  test/utilities/http-api-helper.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
  tools/ot-parachain-account-mapping/create-account-mapping-signature.js
Labels: improvement, v6

#2020 reworked installer with several changes
  installer/installer.sh
Labels: improvement, v6

#2029 add size limit to express json
  src/constants/constants.js
  src/modules/http-client/implementation/express-http-client.js
Labels: bug

#2030 properly return assertion
  src/commands/protocols/get/sender/local-get-command.js
Labels: bug, v6

#2034 limit telemetry events sent
  src/commands/common/send-telemetry-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
Labels: improvement

#2042 update wait and interactive timeout mysql
  installer/installer.sh
Labels: bug, v6

#2036 remove old constants
  src/constants/constants.js
  src/modules/triple-store/implementation/triple-store-constants.js
Labels: chore, v6

#2035 update number of protocol messages in batch
  config/config.json
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/constants/constants.js
  src/service/get-service.js
  src/service/operation-service.js
  src/service/publish-service.js
  test/bdd/steps/api/publish.js
Labels: bug, v6

#2044 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2047 fix send telemetry events
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/sequelize-repository.js
Labels: bug, v6

#2043 fix local network setup
  config/config.json
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/keys.json
Labels: bug, v6

#2050 fix set interactive timeout
  installer/installer.sh
Labels: bug, v6

#2051 OriginTrail 6.0.0-beta.2.2.1 Testnet Prerelease - bug fix
  config/config.json
  installer/installer.sh
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/keys.json
Labels: bug, v6

#2053 OriginTrail 6.0.0-beta.2.2.1 Testnet Release
  .eslintrc.js
  .github/workflows/TEST-release.yml
  .github/workflows/TEST-unit.yml
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/receiver/handle-store-request-command.js
  src/constants/constants.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/triple-store/implementation/triple-store-constants.js
  src/service/get-service.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/util/jwt-util.js
  test/bdd/features/publish-errors.feature
  test/bdd/features/release.feature
  test/bdd/steps/api/datasets/requests.json
  test/bdd/steps/api/publish.js
  test/bdd/steps/api/resolve.js
  test/bdd/steps/common.js
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/config/origintrail-test-node-config.json
  test/bdd/steps/hooks.js
  test/bdd/steps/lib/local-blockchain.js
  test/bdd/steps/lib/ot-node-process.js
  test/unit/sparlql-query-service.test.js
  test/utilities/dkg-client-helper.js
  test/utilities/http-api-helper.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/keys.json
  tools/ot-parachain-account-mapping/create-account-mapping-signature.js
Labels: release, v6

#2059 update node data
  src/commands/common/send-telemetry-command.js
Labels: internal process, v6

#2062 version bump
  package-lock.json
  package.json
Labels: chore, v6

#2061 OriginTrail 6.0.0-beta.2.2.2 Testnet Prerelease
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
Labels: release, v6

#2068 Test/bdd publish errors
  test/bdd/features/publish-errors.feature
  test/bdd/steps/api/publish.js
  test/bdd/steps/common.js
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/config/origintrail-test-node-config.json
Labels: v6

#1996 add publish index and publish assertion
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/publish/receiver/handle-publish-init-command.js
  src/commands/protocols/publish/receiver/handle-publish-request-command.js
  src/commands/protocols/publish/sender/insert-assertion-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/publish-init-command.js
  src/commands/protocols/publish/sender/publish-request-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/publish/sender/validate-assertion-command.js
  src/constants/constants.js
  src/controller/v1/base-controller.js
  src/controller/v1/get-controller.js
  src/controller/v1/publish-controller.js
  src/logger/logger.js
  src/logger/pino-pretty-transport.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/modules/validation/bytes-utilities.js
  src/service/get-service.js
  src/service/publish-service.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
Labels: feature, v6
