Repository OriginTrail/ot-node, pull requests merged in 2022-03, with the labels that each got.

#1794 Signaling server
  external/blazegraph-service.js
  modules/command/common/keep-alive-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/publish-service.js
  package.json
  tools/local-network-setup/.bootstrap_origintrail_noderc
Labels: feature

#1801 OriginTrail 6.0.0-beta.1.28 Testnet Release
  config/config.json
  external/blazegraph-service.js
  external/libp2p-service.js
  modules/command/common/keep-alive-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/publish-service.js
  modules/service/query-service.js
  package.json
  tools/local-network-setup/.bootstrap_origintrail_noderc
Labels: release, v6

#1807 Queue for triple store requests implemented
  modules/constants.js
  modules/service/data-service.js
  ot-node.js
Labels: feature, v6

#1809 OriginTrail 6.0.0-beta.1.29 Testnet Prerelease
  external/blazegraph-service.js
  external/graphdb-service.js
  external/libp2p-service.js
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  ot-node.js
  package.json
Labels: v6

#1810 Fix measurement and error handling for publish operation
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/service/publish-service.js
Labels: hotfix, v6

#1812 OriginTrail 6.0.0-beta.1.29 Testnet Release
  external/blazegraph-service.js
  external/graphdb-service.js
  external/libp2p-service.js
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  ot-node.js
  package.json
Labels: release, v6

#1822 Add select query support
  modules/controller/rpc-controller.js
  modules/service/data-service.js
Labels: feature, v6

#1827 Service api rate limit
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  package.json
Labels: improvement, v6

#1830 add package-lock and bump version
  .gitignore
  package-lock.json
  package.json
Labels: v6

#1831 Include additional KPIs into publish and resolve
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/controller/rpc-controller.js
  modules/service/publish-service.js
  modules/service/query-service.js
Labels: improvement, v6

#1832 OriginTrail 6.0.0-beta.1.30 Testnet Prerelease
  .gitignore
  installer/data/blazegraph.service
  installer/data/graphdb.service
  installer/installer.sh
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  package-lock.json
  package.json
Labels: v6

#1834 OriginTrail 6.0.0-beta.1.30 Testnet Prerelease Hotfix
  modules/constants.js
Labels: v6

#1835 OriginTrail 6.0.0-beta.1.30 Testnet Release #1832
  .gitignore
  installer/data/blazegraph.service
  installer/data/graphdb.service
  installer/installer.sh
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  package-lock.json
  package.json
Labels: release, v6

#1839 remove rate limit from /info, /:operation/result/:handler_id routes
  modules/controller/rpc-controller.js
Labels: improvement, v6

#1841 Fix lint errors
  external/BytesUtilities.js
  external/graphdb-service.js
  external/kad-identity-ranking-service.js
  external/merkle-validation-service.js
  external/web3-blockchain-service.js
  index.js
  migrations/20211117005505-update-handler_ids.js
  models/index.js
  modules/command/command-executor.js
  modules/command/common/keep-alive-command.js
  modules/command/common/otnode-update-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/controller/rpc-controller.js
  modules/logger/logger.js
  modules/service/blockchain-service.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  modules/utilities.js
  modules/worker/l1-worker.js
  modules/worker/worker-pool.js
  ot-node.js
  test/bdd/steps/hooks.js
Labels: improvement, v6

#1842 Implement Network API (libp2p) rate limiting
  external/libp2p-service.js
  modules/constants.js
  package.json
Labels: feature, v6

#1843 add handling of publish responses
  external/libp2p-service.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
Labels: improvement, v6

#1844 add busyness check for all operations and send search requests in parallel
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
Labels: improvement, v6

#1846 fix select query and busyness check
  external/libp2p-service.js
  modules/constants.js
  modules/service/data-service.js
  package-lock.json
  package.json
Labels: bug, v6

#1848 OriginTrail (6.0.0-beta.1.31)
  external/BytesUtilities.js
  external/graphdb-service.js
  external/kad-identity-ranking-service.js
  external/libp2p-service.js
  external/merkle-validation-service.js
  external/web3-blockchain-service.js
  index.js
  migrations/20211117005505-update-handler_ids.js
  models/index.js
  modules/command/command-executor.js
  modules/command/common/keep-alive-command.js
  modules/command/common/otnode-update-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/logger/logger.js
  modules/service/blockchain-service.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  modules/utilities.js
  modules/worker/l1-worker.js
  modules/worker/worker-pool.js
  ot-node.js
  package-lock.json
  package.json
  test/bdd/steps/hooks.js
Labels: release, v6

#1849 properly return after rejecting libp2p message
  external/libp2p-service.js
  modules/service/data-service.js
Labels: bug, v6

#1850 OriginTrail 6.0.0-beta.1.31 Testnet Prerelease Hotfix
  external/libp2p-service.js
  modules/service/data-service.js
Labels: hotfix, release, v6

#1851 OriginTrail 6.0.0-beta.1.31 Testnet Release
  external/BytesUtilities.js
  external/graphdb-service.js
  external/kad-identity-ranking-service.js
  external/libp2p-service.js
  external/merkle-validation-service.js
  external/web3-blockchain-service.js
  index.js
  migrations/20211117005505-update-handler_ids.js
  models/index.js
  modules/command/command-executor.js
  modules/command/common/keep-alive-command.js
  modules/command/common/otnode-update-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/logger/logger.js
  modules/service/blockchain-service.js
  modules/service/data-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  modules/utilities.js
  modules/worker/l1-worker.js
  modules/worker/worker-pool.js
  ot-node.js
  package-lock.json
  package.json
  test/bdd/steps/hooks.js
Labels: release, v6

#1856 add libp2p protocol versioning
  external/libp2p-service.js
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/network-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
Labels: improvement, v6

#1857 fix handling of busy messages
  modules/controller/rpc-controller.js
  modules/service/query-service.js
Labels: bug, v6

#1858 add blacklist and spam detection to libp2p service
  external/libp2p-service.js
  modules/constants.js
  modules/controller/rpc-controller.js
Labels: feature, v6

#1861 OriginTrail 6.0.0-beta.1.32 Testnet Prerelease
  external/libp2p-service.js
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/network-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  package-lock.json
  package.json
Labels: v6

#1865 OriginTrail 6.0.0-beta.1.32 Testnet Release
  external/libp2p-service.js
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/network-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  package-lock.json
  package.json
Labels: release, v6

#1866 update telemetry patch to latest version
  external/libp2p-service.js
  modules/command/publish/send-assertion-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/network-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
Labels: improvement, v6

#1867 fix network and service api routes
  external/libp2p-service.js
  modules/controller/rpc-controller.js
  package-lock.json
  package.json
Labels: bug, hotfix, v6

#1868 OriginTrail 6.0.0-beta.1.32 Testnet Release Hotfix
  external/libp2p-service.js
  modules/controller/rpc-controller.js
  package-lock.json
  package.json
Labels: hotfix, release, v6

#1869 OriginTrail 6.0.0-beta.1.32 Testnet Release Hotfix
  external/libp2p-service.js
  modules/controller/rpc-controller.js
  package-lock.json
  package.json
Labels: hotfix, release, v6
