Repository OriginTrail/ot-node, pull requests merged in 2022-01, with the labels that each got.

#1679 format json for readability when writing libp2p pk to config
  external/libp2p-service.js
Labels: improvement

#1684 Automated tests setup
  .origintrail_noderc_example
  config/config.json
  index.js
  modules/controller/rpc-controller.js
  modules/service/blockchain-service.js
  modules/service/data-service.js
  modules/service/network-service.js
  modules/service/ranking-service.js
  modules/service/validation-service.js
  ot-node.js
  package-lock.json
  package.json
  test/bdd/features/common.feature
  test/bdd/steps/common.js
  test/bdd/steps/hooks.js
  test/utilities/http-api-helper.js
Labels: feature

#1681 Feature/telemetry collection
  config/config.json
  external/graphdb-service.js
  index.js
  modules/command/common/send-telemetry-command.js
  modules/controller/rpc-controller.js
  modules/manager/base-module-manager.js
  modules/manager/telemetry-hub-module-manager.js
  modules/service/dependency-injection.js
  modules/service/publish-service.js
  modules/service/query-service.js
  ot-node.js
  package.json
Labels: feature, v6

#1682 Improve error handling
  external/graphdb-service.js
  external/libp2p-service.js
  external/web3-blockchain-service.js
  modules/command/command-executor.js
  modules/command/command.js
  modules/command/common/otnode-update-command.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/data-service.js
  ot-node.js
  package-lock.json
Labels: improvement, v6

#1686 Resolve issue with initialization
  index.js
  ot-node.js
Labels: bug

#1687 Automatic installation script
  installer/README.md
  installer/data/graphdb.service
  installer/installer.sh
Labels: improvement, v6

#1689 V6/develop - apt upgrade hung on input
  installer/installer.sh
Labels: bug, v6

#1692 Update key message in installer script
  installer/installer.sh
Labels: v6

#1698 Local network setup tool and config fixes
  .gitignore
  config/config.json
  external/libp2p-service.js
  index.js
  modules/service/data-service.js
  modules/service/network-service.js
  modules/service/ranking-service.js
  modules/service/validation-service.js
  ot-node.js
  package-lock.json
  package.json
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/README.md
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: feature, v6

#1697 Optimize operational db usage
  .gitignore
  config/config.json
  modules/command/common/cleaner-command.js
  modules/command/common/handler_ids_cleaner_command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/service/file-service.js
  modules/service/publish-service.js
Labels: feature, v6

#1696 Alpine docker file and small docker fixes
  Alpine.Dockerfile
  Debian.Dockerfile
  Ubuntu.Dockerfile
  docker/docker-compose-alpine.yaml
  docker/docker-compose-debian.yaml
  docker/docker-compose-ubuntu.yaml
  external/graphdb-service.js
Labels: improvement, v6

#1699 Triple store reinitialization
  external/graphdb-service.js
  modules/constants.js
  modules/logger/logger.js
  modules/service/data-service.js
  modules/service/node-service.js
  ot-node.js
Labels: feature, v6

#1700 Bugfixes for handling search results, duplicates verifications and publishing telemetry data
  modules/command/common/send-telemetry-command.js
  modules/command/publish/submit-proofs-command.js
  modules/service/data-service.js
  modules/service/file-service.js
  modules/service/query-service.js
  ot-node.js
Labels: bug, v6

#1701 Fix graphdb health check to handle unexisting repo
  external/graphdb-service.js
  package.json
Labels: bug, v6

#1702 OriginTrail 6.0.0-beta.1.20 Testnet Prerelease
  .gitignore
  .origintrail_noderc_example
  Alpine.Dockerfile
  Debian.Dockerfile
  Ubuntu.Dockerfile
  config/config.json
  config/papertrail.yml
  docker/docker-compose-alpine.yaml
  docker/docker-compose-debian.yaml
  docker/docker-compose-ubuntu.yaml
  external/graphdb-service.js
  external/libp2p-service.js
  external/web3-blockchain-service.js
  index.js
  installer/README.md
  installer/data/graphdb.service
  installer/installer.sh
  modules/command/command-executor.js
  modules/command/command.js
  modules/command/common/cleaner-command.js
  modules/command/common/handler_ids_cleaner_command.js
  modules/command/common/otnode-update-command.js
  modules/command/common/send-telemetry-command.js
  modules/command/publish/insert-assertion-command.js
  modules/command/publish/send-assertion-command.js
  modules/command/publish/submit-proofs-command.js
  modules/constants.js
  modules/controller/rpc-controller.js
  modules/logger/logger.js
  modules/manager/base-module-manager.js
  modules/manager/telemetry-hub-module-manager.js
  modules/service/blockchain-service.js
  modules/service/data-service.js
  modules/service/dependency-injection.js
  modules/service/file-service.js
  modules/service/network-service.js
  modules/service/node-service.js
  modules/service/publish-service.js
  modules/service/query-service.js
  modules/service/ranking-service.js
  modules/service/validation-service.js
  ot-node.js
  package-lock.json
  package.json
  test/bdd/features/common.feature
  test/bdd/steps/common.js
  test/bdd/steps/hooks.js
  test/utilities/http-api-helper.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/README.md
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release, v6
