Repository OriginTrail/ot-node, pull requests merged in 2022-11, with the labels that each got.

#2163 fix retries for invalid assertion
  src/commands/protocols/publish/sender/validate-assertion-command.js
Labels: bug, v6

#2167 increase stake amount
  package-lock.json
  package.json
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: v6

#2168 OriginTrail 6.0.0-beta.3.0.0 Testnet Prerelease
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/dial-peers-command.js
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/find-nodes-local-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/get/sender/network-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/validate-assertion-command.js
  src/constants/constants.js
  src/migration/blockchain-identity-migration.js
  src/modules/base-module-manager.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/eth/eth-service.js
  src/modules/blockchain/implementation/ganache/ganache-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20221025120253-create-blockchain-event.js
  src/modules/repository/implementation/sequelize/migrations/20221025212800-create-shard.js
  src/modules/repository/implementation/sequelize/migrations/20221028125900-create-blockchain.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/models/blockchain.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/get-service.js
  src/service/json-schema-service.js
  src/service/sharding-table-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/release.feature
  test/bdd/steps/common.mjs
  test/bdd/steps/lib/local-blockchain.mjs
Labels: breaking change, release, v6

#2169 OriginTrail 6.0.0-beta.3.0.0 Testnet Release
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/dial-peers-command.js
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/find-nodes-local-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/get/sender/network-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/validate-assertion-command.js
  src/constants/constants.js
  src/migration/blockchain-identity-migration.js
  src/modules/base-module-manager.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/eth/eth-service.js
  src/modules/blockchain/implementation/ganache/ganache-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20221025120253-create-blockchain-event.js
  src/modules/repository/implementation/sequelize/migrations/20221025212800-create-shard.js
  src/modules/repository/implementation/sequelize/migrations/20221028125900-create-blockchain.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/models/blockchain.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/get-service.js
  src/service/json-schema-service.js
  src/service/sharding-table-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/release.feature
  test/bdd/steps/common.mjs
  test/bdd/steps/lib/local-blockchain.mjs
Labels: breaking change, release, v6

#2162 improve dialer
  package-lock.json
  package.json
  src/commands/common/dial-peers-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
Labels: improvement, v6

#2173 improve dialer (#2162)
  package-lock.json
  package.json
  src/commands/common/dial-peers-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
Labels: bug, improvement, v6

#2177 Commit/Proof phases preparation
  config/config.json
  ot-node.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/constants/constants.js
  src/modules/base-module-manager.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/eth/eth-service.js
  src/modules/blockchain/implementation/ganache/ganache-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, help wanted, v6

#2182 Fixes for profile creation and rpc providers
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
Labels: bug

#2183 add logs for commit proofs phase
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
Labels: v6

#2186 commit proof error handling
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: v6

#2187 fix batch size calculation
  config/config.json
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/get/sender/network-get-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/get-service.js
  src/service/operation-service.js
  src/service/publish-service.js
Labels: bug, v6

#2188 fix neighbourhood calculation
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/network-get-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/get-service.js
  src/service/publish-service.js
  src/service/service-agreement-service.js
  src/service/ual-service.js
Labels: bug, v6

#2175 reduce blockchain rpc connections
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
Labels: improvement

#2193 merge v6/develop into v6/development-network
  ot-node.js
  package.json
  src/constants/constants.js
  src/migration/clean-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
Labels: v6

#2195 Added removing of blockchain events during the migration
  src/migration/clean-sharding-table-migration.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
Labels: v6

#2197 Removing blockchain last check entry in migration (#2196)
  src/migration/clean-sharding-table-migration.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
Labels: v6

#2198 add custom filtering to neighbourhood calculation
  package-lock.json
  package.json
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
Labels: bug, v6

#2199 add custom filtering to neighbourhood calculation (#2198)
  package-lock.json
  package.json
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
Labels: bug, v6

#2200 fix bug in neighbourhood calculation
  src/modules/repository/implementation/sequelize/sequelize-repository.js
Labels: bug, v6

#2201 fix bug in neighbourhood calculation (#2200)
  src/modules/repository/implementation/sequelize/sequelize-repository.js
Labels: bug, v6

#2202 Added queue for processing blockchain transactions
  package-lock.json
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: feature

#2203 bug fixes, bid suggestion and validation
  config/config.json
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.1/v1-0-1-handle-store-request-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.2/v1-0-2-handle-store-request-command.js
  src/commands/protocols/publish/sender/local-store-command.js
  src/commands/protocols/publish/sender/validate-assertion-command.js
  src/constants/constants.js
  src/controllers/http-api/bid-suggestion-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/request-schema/bid-suggestion-schema.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/service/json-schema-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/generate-config-files.js
Labels: bug, v6

#2205 Using fixed gas limit for certain methods
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement

#2207 Updated cors middleware
  src/modules/http-client/implementation/express-http-client.js
Labels: chore
