Repository OriginTrail/ot-node, pull requests merged in 2023-12, with the labels that each got.

#2819 Feature/add blockchains to nodeinfo
  src/commands/common/send-telemetry-command.js
Labels: feature, v6

#2824 Added check if there was a new finalized state before sending commits/proofs
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
Labels: improvement

#2825 Local setup readme update
  README.md
  tools/local-network-setup/README.md
Labels: chore, v6

#2822 Added missing awaits to 'retryFinished' and 'handleError' functions
  README.md
  package-lock.json
  package.json
  src/commands/cleaners/cleaner-command.js
  src/commands/cleaners/operation-id-cleaner-command.js
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/common/dial-peers-command.js
  src/commands/common/otnode-update-command.js
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-init-command.js
  tools/local-network-setup/README.md
Labels: bug, hotfix

#2826 OriginTrail Devnet Release v6.1.0.hotfix5
  README.md
  package-lock.json
  package.json
  src/commands/cleaners/cleaner-command.js
  src/commands/cleaners/operation-id-cleaner-command.js
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/common/dial-peers-command.js
  src/commands/common/otnode-update-command.js
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-init-command.js
  tools/local-network-setup/README.md
Labels: release

#2828 OriginTrail Devnet Prerelease v6.1.0.hotfix6
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20233011121700-remove-blockchain-info.js
  src/service/blockchain-event-listener-service.js
Labels: hotfix

#2829 OriginTrail Devnet Release v6.1.0hotfix-6
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20233011121700-remove-blockchain-info.js
  src/service/blockchain-event-listener-service.js
Labels: hotfix

#2830 Version update
  package-lock.json
  package.json
Labels: chore

#2839 Added Gnosis hub contract
  config/config.json
Labels: feature, v6

#2844 Branches leveling
  README.md
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/cleaners/cleaner-command.js
  src/commands/cleaners/operation-id-cleaner-command.js
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/common/dial-peers-command.js
  src/commands/common/otnode-update-command.js
  src/commands/common/send-telemetry-command.js
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-init-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/commands/query/query-command.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/migration/migration-executor.js
  src/migration/ual-extension-triple-store-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20231201140100-event-add-blockchain-id.js
  src/modules/repository/implementation/sequelize/migrations/20233011121700-remove-blockchain-info.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
  src/service/operation-id-service.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  src/service/update-service.js
  test/unit/mock/operation-id-service-mock.js
  test/unit/service/get-service.test.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
  tools/local-network-setup/README.md
Labels: chore, internal process

#2847 Added error handling when bid suggestion call fails
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
Labels: bug

#2848 Handle Blazegraph corruption of special characters
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/service/triple-store-service.js
Labels: bug

#2849 Bump version to 6.1.1
  package-lock.json
  package.json
Labels: chore

#2850 Updated error handling for empty sharding table
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
Labels: bug

#2851 OriginTrail Devnet Prerelease v6.1.1
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/migration/ual-extension-triple-store-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
Labels: release

#2852 OriginTrail Devnet Release v6.1.1
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/migration/ual-extension-triple-store-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
Labels: release

#2853 OriginTrail Mainnet Prerelease v6.1.1
  ot-node.js
  package-lock.json
  package.json
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
Labels: release

#2854 OriginTrail Mainnet Release v6.1.1
  ot-node.js
  package-lock.json
  package.json
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
Labels: release

#2832 Fix getGas price in set-ask, set-stake and specify which blockchain is used when getting gasPrice in submit commands
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
Labels: bug, v6

#2855 Migration for events synchronization & events chunking for events insertion
  ot-node.js
  package-lock.json
  package.json
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
Labels: bug

#2856 OriginTrail Devnet Prerelease v6.1.2
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
Labels: release

#2857 OriginTrail Devnet Release v6.1.2
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
Labels: release

#2858 OriginTrail Testnet Prerelease v6.1.2
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/migration/ual-extension-triple-store-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
Labels: release

#2859 OriginTrail Testnet Release v6.1.2
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
Labels: release

#2860 Resolved issue with cache as class variable + version bump
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
Labels: bug

#2861 OriginTrail Devnet Prerelease v6.1.2 Hotfix 1
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2862 OriginTrail Devnet Release v6.1.2 Hotfix 1
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2863 OriginTrail Testnet Prerelease v6.1.2 Hotfix 1
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2864 OriginTrail Testnet Release v6.1.2 Hotfix 1
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2870 OriginTrail Mainnet Prerelease v6.1.2
  installer/installer.sh
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
Labels: release

#2871 OriginTrail Mainnet Release v6.1.2
  installer/installer.sh
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
Labels: release
