Repository OriginTrail/ot-node, pull requests merged in 2023-03, with the labels that each got.

#2367 Split update feature to use local-store and update routes
  src/commands/local-store/local-store-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-init-command.js
  src/constants/constants.js
  src/controllers/http-api/local-store-http-api-controller.js
  src/controllers/http-api/request-schema/local-store-schema.js
  src/controllers/http-api/request-schema/update-schema.js
  src/controllers/http-api/update-http-api-controller.js
Labels: feature

#2365 fix bid suggestion for datasets < 1kb
  src/commands/common/operation-id-cleaner-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/constants/constants.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/network/implementation/libp2p-service.js
  src/service/sharding-table-service.js
  test/unit/service/sharding-table-service.test.js
Labels: bug, v6

#2360 add auth tables migrations for new routes
  src/modules/repository/implementation/sequelize/migrations/20230216112400-add-abilities.js
Labels: bug, v6

#2358 fix bid suggestion auth
  src/modules/http-client/implementation/middleware/authentication-middleware.js
  src/modules/http-client/implementation/middleware/authorization-middleware.js
Labels: bug, v6

#2375 Updated handling of failed transactions
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: bug

#2380 add logs, speed up private asset metadata migration
  src/migration/private-assets-metadata-migration.js
Labels: improvement, v6

#2382 fix submit update commit, update contract initialisation
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2379 minor improvements
  ot-node.js
  src/commands/command-executor.js
  src/controllers/http-api/http-api-router.js
  src/controllers/rpc/rpc-router.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/network/implementation/libp2p-service.js
Labels: bug, v6

#2383 fix bid validation
  src/commands/protocols/common/handle-protocol-message-command.js
Labels: bug, v6

#2384 fix ServiceAgreementStorageProxyContract call
  package-lock.json
  package.json
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2385 Devnet 6.0.4+hotfix.1 Release
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/controllers/http-api/http-api-router.js
  src/controllers/rpc/rpc-router.js
  src/migration/private-assets-metadata-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/migrations/20230303131200-update-publish-remove-agreement-data.js
  src/modules/repository/implementation/sequelize/sequelize-migrator.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: chore, release, v6

#2386 Updated dkg-evm-module and script for contracts compilation
  package-lock.json
  package.json
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  test/bdd/steps/lib/local-blockchain.mjs
Labels: bug, v6

#2387 Devnet 6.0.4+hotfix.2 Release
  package-lock.json
  package.json
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  test/bdd/steps/lib/local-blockchain.mjs
Labels: chore, hotfix, release, v6

#2388 Devnet 6.0.4+hotfix.2 Release
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/controllers/http-api/http-api-router.js
  src/controllers/rpc/rpc-router.js
  src/migration/private-assets-metadata-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/migrations/20230303131200-update-publish-remove-agreement-data.js
  src/modules/repository/implementation/sequelize/sequelize-migrator.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  test/bdd/steps/lib/local-blockchain.mjs
  tools/local-network-setup/setup-macos-environment.sh
Labels: chore, hotfix, release, v6

#2389 filter neighborhood by last seen on validation
  src/commands/protocols/common/handle-protocol-message-command.js
Labels: bug, v6

#2393 Devnet 6.0.4+hotfix.3 Release
  package-lock.json
  package.json
  src/commands/protocols/common/handle-protocol-message-command.js
  src/migration/private-assets-metadata-migration.js
  test/modules/triple-store/triple-store.js
Labels: chore, hotfix, release, v6

#2395 add repository to query request schema
  src/controllers/http-api/query-http-api-controller.js
  src/controllers/http-api/request-schema/query-schema.js
Labels: improvement, v6

#2394 fix local get from pending storage
  src/commands/protocols/get/sender/local-get-command.js
Labels: bug, v6, in progress (do not merge)

#2396 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2397 Devnet 6.0.4+hotfix.4 Release
  package-lock.json
  package.json
  src/commands/protocols/get/sender/local-get-command.js
  src/controllers/http-api/query-http-api-controller.js
  src/controllers/http-api/request-schema/query-schema.js
Labels: chore, hotfix, release, v6

#2399 Additional log for get init - Prerelease devnet hotfix
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
Labels: chore, hotfix

#2398 Devnet 6.0.4+hotfix.4 Release
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/controllers/http-api/query-http-api-controller.js
  src/controllers/http-api/request-schema/query-schema.js
Labels: chore, hotfix, release, v6

#2400 Updated filename for pending storage, added logs
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  tools/local-network-setup/generate-config-files.js
Labels: bug

#2401 Devnet 6.0.4+hotfix.5 Release
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  tools/local-network-setup/generate-config-files.js
Labels: chore, hotfix, release, v6

#2402 Devnet 6.0.4+hotfix.5 Release
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  tools/local-network-setup/generate-config-files.js
Labels: chore, hotfix, release, v6

#2404 Set version to back 6.0.4 and bump dkg-evm-module version
  package-lock.json
  package.json
Labels: chore

#2405 Devnet 6.0.4 Prerelease - setting versions
  package-lock.json
  package.json
Labels: chore, release

#2406 Devnet 6.0.4 Release - setting versions
  package-lock.json
  package.json
Labels: chore, release

#2410 Added end event for commit update command, updated DKG.js version
  .github/workflows/TEST-bdd.yml
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/sharding-table-service.js
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
Labels: bug

#2411 Added end event for commit update command, updated DKG.js version (#2…
  .github/workflows/TEST-bdd.yml
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/sharding-table-service.js
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
Labels: release

#2412 Fix the version name to hotfix.6
  package-lock.json
  package.json
Labels: bug, chore

#2413 Devnet Prerelease Hotfix 6
  package-lock.json
  package.json
Labels: chore, release

#2414 Devnet Release 6.0.4 hotfix 6
  .github/workflows/TEST-bdd.yml
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/sharding-table-service.js
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
Labels: chore, release

#2415 Testnet Prerelease 6.0.4 hotfix 6
  .github/workflows/TEST-bdd.yml
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/sharding-table-service.js
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
Labels: release

#2416 Testnet Release 6.0.4 hotfix 6
  .github/workflows/TEST-bdd.yml
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/sharding-table-service.js
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
Labels: release
