Repository OriginTrail/ot-node, pull requests merged in 2023-09, with the labels that each got.

#2700 Updated check for root hash
  src/service/validation-service.js
  test/unit/service/validation-service.test.js
Labels: bug

#2676 Removed fixed gas limit for blockchain functions
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, v6

#2710 OriginTrail Mainnet Release v6.0.15
  installer/installer.sh
  package-lock.json
  package.json
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/sharding-table-service.js
  src/service/validation-service.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2714 Asset sync v6.0.26
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/sharding-table-service.js
Labels: bug, release, v6

#2712 Added delay for update finalization in the BDD tests
  test/bdd/features/get.feature
Labels: bug, chore, internal process

#2715 Added decoding for EVM errors, reworked erro handling for estimateGas
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement

#2717 Removed WebSocket Blockchain RPCs from the default configuration
  config/config.json
  package-lock.json
  package.json
Labels: improvement

#2718 OriginTrail Devnet Prerelease v6.0.16
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  test/bdd/features/get.feature
Labels: release, v6

#2723 Authorization/Authentication middleware logic fixed
  src/modules/http-client/implementation/middleware/authentication-middleware.js
  src/modules/http-client/implementation/middleware/authorization-middleware.js
  src/service/auth-service.js
  test/unit/middleware/authentication-middleware.test.js
  test/unit/middleware/authorization-middleware.test.js
Labels: bug

#2722 OriginTrail Devnet Prerelease v6.0.16
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/authentication-middleware.js
  src/modules/http-client/implementation/middleware/authorization-middleware.js
  src/service/auth-service.js
  test/bdd/features/get.feature
  test/unit/middleware/authentication-middleware.test.js
  test/unit/middleware/authorization-middleware.test.js
Labels: release

#2724 OriginTrail Devnet Release v6.0.16
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/authentication-middleware.js
  src/modules/http-client/implementation/middleware/authorization-middleware.js
  src/service/auth-service.js
  test/bdd/features/get.feature
  test/unit/middleware/authentication-middleware.test.js
  test/unit/middleware/authorization-middleware.test.js
Labels: release, v6

#2725 Made public API enpoints check case-insensitive
  package-lock.json
  package.json
  src/service/auth-service.js
Labels: improvement

#2727 OriginTrail Devnet Prerelease v6.0.16 Hotfix
  package-lock.json
  package.json
  src/service/auth-service.js
Labels: release, v6

#2728 OriginTrail Devnet Release v6.0.16 Hotfix
  package-lock.json
  package.json
  src/service/auth-service.js
Labels: release, v6

#2731 OriginTrail v6.0.16 Hotfix suffix removal
  package-lock.json
  package.json
Labels: chore

#2732 OriginTrail v6.0.16 Hotfix suffix removal
  package-lock.json
  package.json
Labels: chore

#2733 OriginTrail Testnet Prerelease v6.0.16
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/authentication-middleware.js
  src/modules/http-client/implementation/middleware/authorization-middleware.js
  src/service/auth-service.js
  test/bdd/features/get.feature
  test/unit/middleware/authentication-middleware.test.js
  test/unit/middleware/authorization-middleware.test.js
Labels: release, v6

#2734 OriginTrail Testnet Release v6.0.16
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/http-client/implementation/middleware/authentication-middleware.js
  src/modules/http-client/implementation/middleware/authorization-middleware.js
  src/service/auth-service.js
  test/bdd/features/get.feature
  test/unit/middleware/authentication-middleware.test.js
  test/unit/middleware/authorization-middleware.test.js
Labels: release
