Repository OriginTrail/ot-node, pull requests merged in 2023-08, with the labels that each got.

#2661 Add check for assertion size limit
  config/config.json
  src/commands/protocols/common/handle-protocol-message-command.js
  src/service/validation-service.js
  test/bdd/steps/api/publish.mjs
  test/unit/service/validation-service.test.js
Labels: chore

#2662 Added check for bids for the neighbourhood during publish start
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
Labels: chore

#2634 fix handling of failed transactions
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2654 only start libp2p after network protocols are defined
  ot-node.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
Labels: bug, v6

#2655 fix update peer last seen and dialed
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/sharding-table-service.js
Labels: bug, v6

#2668 Added updates for bid suggestion and assertion size handling
  src/commands/protocols/common/handle-protocol-message-command.js
  src/service/sharding-table-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
Labels: chore

#2671 OriginTrail Devnet Prerelease v6.0.13
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/sharding-table-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
  test/unit/service/validation-service.test.js
Labels: release

#2672 OriginTrail Devnet Release v6.0.13
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/sharding-table-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2675 [P1] GET operation and update finalization bug fix
  .github/workflows/checks.yml
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
Labels: bug, hotfix, release, v6, P1

#2683 OriginTrail Testnet Prerelease 6.0.13
  .github/workflows/checks.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  src/service/sharding-table-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2684 OriginTrail Testnet Release 6.0.13
  .github/workflows/checks.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  src/service/sharding-table-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2673 Added new Postman/OpenAPI API collection
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  postman/DKGv6.postman_collection.json
Labels: improvement, chore, v6

#2686 OriginTrail Release v6.0.13 for Sync Nodes
  .github/workflows/checks.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  src/service/sharding-table-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2687 OriginTrail Mainnet Prerelease v6.0.13
  .github/workflows/checks.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  src/service/sharding-table-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/network-module-manager-mock.js
  test/unit/service/sharding-table-service.test.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2689 OriginTrail v6.0.13
  .github/workflows/checks.yml
  package-lock.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  test/bdd/steps/lib/local-blockchain.mjs
Labels: v6

#2660 HTTP API versioning
  .eslintrc.cjs
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
  src/constants/constants.js
  src/controllers/http-api/base-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/info-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/controllers/http-api/v0/request-schema/update-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/controllers/http-api/v1/.gitkeep
  src/controllers/http-api/v1/request-schema/.gitkeep
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/service/json-schema-service.js
  src/service/util/string-util.js
  test/unit/api/http-api-router.test.js
  test/unit/mock/http-client-module-manager-mock.js
  test/unit/mock/json-schema-service-mock.js
Labels: improvement, feature, v6

#2690 OriginTrail Devnet Prerelease v6.0.14
  .eslintrc.cjs
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
  src/constants/constants.js
  src/controllers/http-api/base-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/info-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/controllers/http-api/v0/request-schema/update-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/controllers/http-api/v1/.gitkeep
  src/controllers/http-api/v1/request-schema/.gitkeep
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/service/json-schema-service.js
  src/service/util/string-util.js
  test/unit/api/http-api-router.test.js
  test/unit/mock/http-client-module-manager-mock.js
  test/unit/mock/json-schema-service-mock.js
Labels: release, v6

#2692 OriginTrail Testnet Prerelease v6.0.14
  .eslintrc.cjs
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
  src/constants/constants.js
  src/controllers/http-api/base-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/info-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/controllers/http-api/v0/request-schema/update-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/controllers/http-api/v1/.gitkeep
  src/controllers/http-api/v1/request-schema/.gitkeep
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/service/json-schema-service.js
  src/service/util/string-util.js
  test/unit/api/http-api-router.test.js
  test/unit/mock/http-client-module-manager-mock.js
  test/unit/mock/json-schema-service-mock.js
Labels: release, feature, v6

#2693 OriginTrail Testnet Release v6.0.14
  .eslintrc.cjs
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
  src/constants/constants.js
  src/controllers/http-api/base-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/info-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/controllers/http-api/v0/request-schema/update-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/controllers/http-api/v1/.gitkeep
  src/controllers/http-api/v1/request-schema/.gitkeep
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/service/json-schema-service.js
  src/service/util/string-util.js
  test/unit/api/http-api-router.test.js
  test/unit/mock/http-client-module-manager-mock.js
  test/unit/mock/json-schema-service-mock.js
Labels: release, feature, v6

#2694 Update CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#2695 OriginTrail Mainnet Prerelease v6.0.14
  .eslintrc.cjs
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
  src/constants/constants.js
  src/controllers/http-api/base-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/info-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/controllers/http-api/v0/request-schema/update-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/controllers/http-api/v1/.gitkeep
  src/controllers/http-api/v1/request-schema/.gitkeep
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/service/json-schema-service.js
  src/service/util/string-util.js
  test/unit/api/http-api-router.test.js
  test/unit/mock/http-client-module-manager-mock.js
  test/unit/mock/json-schema-service-mock.js
Labels: release, feature, v6

#2696 OriginTrail Mainnet Release v6.0.14
  .eslintrc.cjs
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
  src/constants/constants.js
  src/controllers/http-api/base-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/info-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/controllers/http-api/v0/request-schema/update-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/controllers/http-api/v1/.gitkeep
  src/controllers/http-api/v1/request-schema/.gitkeep
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/service/json-schema-service.js
  src/service/util/string-util.js
  test/unit/api/http-api-router.test.js
  test/unit/mock/http-client-module-manager-mock.js
  test/unit/mock/json-schema-service-mock.js
Labels: release, feature, v6

#2699 OriginTrail Release v6.0.24 for Sync Nodes
  .eslintrc.cjs
  docs/openapi/DKGv6.yaml
  docs/postman/DKGv6.postman_collection.json
  package-lock.json
  package.json
  postman/DKGv6.postman_collection.json
  src/constants/constants.js
  src/controllers/http-api/base-http-api-controller.js
  src/controllers/http-api/http-api-router.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/info-http-api-controller-v0.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/query-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/controllers/http-api/v0/request-schema/update-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v0/update-http-api-controller-v0.js
  src/controllers/http-api/v1/.gitkeep
  src/controllers/http-api/v1/request-schema/.gitkeep
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/service/json-schema-service.js
  src/service/util/string-util.js
  test/unit/api/http-api-router.test.js
  test/unit/mock/http-client-module-manager-mock.js
  test/unit/mock/json-schema-service-mock.js
Labels: release, feature, v6
