Repository OriginTrail/ot-node, pull requests merged in 2023-06, with the labels that each got.

#2569 Mainnet 6.0.10 Prerelease
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: hotfix, v6

#2570 Mainnet 6.0.10 Release
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: release, v6

#2572 level branches
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: chore, v6

#2578 fix: do not skip protocol messages
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
Labels: bug, v6

#2564 add epoch check telemetry event
  src/commands/protocols/common/epoch-check-command.js
  src/service/operation-id-service.js
Labels: bug, v6

#2566 only fetch necessary events
  src/constants/constants.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/blockchain-event-listener-service.js
Labels: improvement, v6

#2579 Operational db data archive
  src/commands/cleaners/blockchain-event-cleaner-command.js
  src/commands/cleaners/cleaner-command.js
  src/commands/cleaners/commands-cleaner-command.js
  src/commands/cleaners/get-response-cleaner-command.js
  src/commands/cleaners/operation-id-cleaner-command.js
  src/commands/cleaners/publish-response-cleaner-command.js
  src/commands/cleaners/update-response-cleaner-command.js
  src/commands/common/commands-cleaner-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/repository-module-manager.js
  src/service/archive-service.js
  src/service/file-service.js
Labels: feature

#2582 delete operation id files in batches
  src/commands/cleaners/operation-id-cleaner-command.js
  src/constants/constants.js
  src/service/operation-id-service.js
Labels: improvement, v6

#2587 Added state hash validation for GET operation, additional BDD tests
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/constants/constants.js
  src/service/file-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/steps/api/datasets/assertions.json
  test/bdd/steps/api/datasets/requests.json
  test/bdd/steps/api/get.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/state.mjs
  test/utilities/http-api-helper.mjs
Labels: improvement

#2573 Get historical
  .github/actions/setup/action.yml
  .github/workflows/CHECK-lint.yml
  .github/workflows/TEST-bdd.yml
  .github/workflows/TEST-unit.yml
  .github/workflows/checks.yml
  .github/workflows/release-drafter-config.yml
  .github/workflows/update-cache.yml
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/controllers/http-api/get-http-api-controller.js
  src/controllers/http-api/request-schema/get-schema.js
  src/controllers/rpc/publish-rpc-controller.js
  src/controllers/rpc/update-rpc-controller.js
  src/migration/base-migration.js
  src/migration/blockchain-identity-migration.js
  src/migration/pending-storage-migration.js
  src/migration/service-agreements-metadata-migration.js
  src/migration/triple-store-metadata-migration.js
  src/migration/triple-store-user-configuration-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/file-service.js
  src/service/operation-id-service.js
  src/service/pending-storage-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/datasets/assertions.json
  test/bdd/steps/api/datasets/requests.json
  test/bdd/steps/api/get.mjs
  test/bdd/steps/api/info.mjs
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/api/resolve.mjs
  test/bdd/steps/api/update.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/bdd/steps/lib/state.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/http-api-helper.mjs
  test/utilities/steps-utils.mjs
Labels: improvement, feature, v6

#2589 fix remove cached folder from pending storage
  src/service/pending-storage-service.js
Labels: bug, v6

#2591 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2592 Devnet 6.0.11 Prerelease Hotfix
  .github/workflows/release-drafter-config.yml
  package-lock.json
  package.json
  src/service/pending-storage-service.js
Labels: hotfix, release, v6

#2593 Devnet 6.0.11 Release Hotfix
  .github/workflows/release-drafter-config.yml
  package-lock.json
  package.json
  src/service/pending-storage-service.js
Labels: hotfix, release, v6

#2594 fix undefined public assertion on operation completed
  src/commands/protocols/update/sender/v1.0.0/v1-0-0-update-request-command.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/update-service.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
Labels: bug, v6

#2595 bump version
  package-lock.json
  package.json
Labels: release, v6

#2596 Devnet 6.0.11 Prerelease
  package-lock.json
  package.json
  src/commands/protocols/update/sender/v1.0.0/v1-0-0-update-request-command.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/update-service.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
Labels: release, v6

#2597 Devnet 6.0.11 Release
  package-lock.json
  package.json
  src/commands/protocols/update/sender/v1.0.0/v1-0-0-update-request-command.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/update-service.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
Labels: release, v6

#2601 Devnet 6.0.11 Release Hotfix 2
  package-lock.json
  package.json
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: hotfix, release, v6

#2602 Fixed state hash validation in GetAssertionId command
  package-lock.json
  package.json
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: bug, hotfix

#2603 Devnet 6.0.11 Prerelease Hotfix 3
  package-lock.json
  package.json
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: hotfix, release, v6

#2604 Devnet 6.0.11 Release Hotfix 3
  package-lock.json
  package.json
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: hotfix, release, v6

#2605 Improvement for state hash validation in GetAssertionIdCommand
  package-lock.json
  package.json
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: bug, hotfix

#2606 Moved getting assertionIds array to the condition to avoid unnecessary blockchain calls
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: improvement

#2607 Devnet 6.0.11 Prerelease
  package-lock.json
  package.json
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: release, v6

#2608 Devnet 6.0.11 Release
  package-lock.json
  package.json
  src/commands/protocols/get/sender/get-assertion-id-command.js
Labels: release, v6

#2613 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2614 Devnet 6.0.11 Prerelease Hotfix 4
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
Labels: hotfix, release, v6

#2615 Devnet 6.0.11 Release Hotfix 4
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
Labels: hotfix, release, v6

#2616 Testnet 6.0.11 Prerelease Hotfix 1
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
Labels: hotfix, release, v6

#2617 Testnet 6.0.11 Release Hotfix 1
  package-lock.json
  package.json
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
Labels: hotfix, release, v6

#2618 bump version to 6.0.11
  package-lock.json
  package.json
Labels: chore, v6

#2619 bump version to 6.0.11 (#2618)
  package-lock.json
  package.json
Labels: chore, v6

#2620 bump version to 6.0.11 (#2618)
  package-lock.json
  package.json
Labels: chore, v6

#2621 bump version to 6.0.11 (#2618)
  package-lock.json
  package.json
Labels: chore, v6

#2622 bump version to 6.0.11 (#2618)
  package-lock.json
  package.json
Labels: chore, v6
