Repository OriginTrail/ot-node, pull requests merged in 2023-01, with the labels that each got.

#2325 add sharding table migration
  ot-node.js
  src/migration/pull-sharding-table-migration.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
Labels: bug, hotfix, v6

#2324 Added listening to Staking contract events, fixed DB updates on events
  ot-node.js
  package-lock.json
  package.json
  src/constants/constants.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/sharding-table-service.js
Labels: bug, hotfix, v6

#2326 OriginTrail 6.0.2 Devnet Release
  .github/workflows/TEST-bdd.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
  test/bdd/features/get-errors.feature
  test/bdd/steps/api/resolve.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/lib/local-blockchain.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
  tools/local-network-setup/generate-config-files.js
Labels: release, v6

#2328 add validationModuleManager to sharding table migration
  ot-node.js
  src/migration/pull-sharding-table-migration.js
Labels: bug, v6

#2329 OriginTrail 6.0.2 Devnet Release Hotfix
  ot-node.js
  src/migration/pull-sharding-table-migration.js
Labels: bug, hotfix, v6

#2332 OriginTrail 6.0.2 Testnet Prerelease
  .github/workflows/TEST-bdd.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
  test/bdd/features/get-errors.feature
  test/bdd/steps/api/resolve.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/lib/local-blockchain.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
  tools/local-network-setup/generate-config-files.js
Labels: release, v6

#2331 OriginTrail 6.0.2 Testnet Release
  .github/workflows/TEST-bdd.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
  test/bdd/features/get-errors.feature
  test/bdd/steps/api/resolve.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/lib/local-blockchain.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
  tools/local-network-setup/generate-config-files.js
Labels: release, v6

#2334 OriginTrail 6.0.2 Mainnet Release
  .github/workflows/TEST-bdd.yml
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
  test/bdd/features/get-errors.feature
  test/bdd/steps/api/resolve.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/config/origintrail-test-bootstrap-config.json
  test/bdd/steps/lib/local-blockchain.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
  tools/local-network-setup/generate-config-files.js
Labels: release, v6

#2330 Node will send node info even if there are no events in db
  src/commands/common/send-telemetry-command.js
Labels: bug

#2338 triple store config migrations and local network setup updates
  .gitignore
  .origintrail_noderc.tests
  config/config.json
  frameDocuments/erc721.json
  installer/data/fuseki.service
  installer/installer.sh
  ot-node.js
  src/migration/triple-store-user-configuration-migration.js
  src/modules/base-module-manager.js
  src/modules/module-config-validation.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-fuseki/ot-fuseki.js
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  tools/local-network-setup/.bootstrap_origintrail_noderc
  tools/local-network-setup/.dh_origintrail_noderc
  tools/local-network-setup/.origintrail_noderc_template.json
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: feature, v6, in progress (do not merge)

#2340 remove repository from local get function
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
Labels: bug, v6

#2342 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2341 OriginTrail 6.0.3 Devnet Release Hotfix
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
Labels: bug, hotfix, v6

#2343 bump version to 6.0.3
  package-lock.json
  package.json
Labels: chore, v6

#2344 bump version to 6.0.3 (#2343)
  package-lock.json
  package.json
Labels: chore, v6

#2350 OriginTrail 6.0.3 Devnet Release Hotfix
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/controllers/http-api/publish-http-api-controller.js
Labels: hotfix, release, v6

#2351 add copy assertions migration
  scripts/copy-assertions.js
Labels: feature, v6

#2352 add copy assertions migration (#2351)
  scripts/copy-assertions.js
Labels: feature, v6

#2353 OriginTrail 6.0.3 Testnet Release Hotfix
  package-lock.json
  package.json
  scripts/copy-assertions.js
  src/commands/local-store/local-store-command.js
  src/controllers/http-api/publish-http-api-controller.js
Labels: hotfix, release, v6

#2355 OriginTrail 6.0.3 Testnet Release Hotfix
  package-lock.json
  package.json
  scripts/copy-assertions.js
  src/commands/local-store/local-store-command.js
  src/controllers/http-api/publish-http-api-controller.js
Labels: hotfix, release, v6
