Repository OriginTrail/ot-node, pull requests merged in 2023-11, with the labels that each got.

#2741 Fix/transactions timeout
  package-lock.json
  package.json
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/constants/constants.js
Labels: bug, release, v6

#2745 OriginTrail Devnet Prerelease v6.0.17
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/constants/constants.js
  src/migration/telemetry-module-user-configuration-migration.js
  src/modules/base-module-manager.js
  src/modules/module-config-validation.js
  src/modules/telemetry/implementation/ot-telemetry.js
  src/modules/telemetry/telemetry-module-manager.js
  src/service/telemetry-injection-service.js
  test/modules/telemetry/config.json
  test/modules/telemetry/telemetry.js
Labels: bug, release, v6

#2746 OriginTrail Devnet Release v6.0.17
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/constants/constants.js
  src/migration/telemetry-module-user-configuration-migration.js
  src/modules/base-module-manager.js
  src/modules/module-config-validation.js
  src/modules/telemetry/implementation/ot-telemetry.js
  src/modules/telemetry/telemetry-module-manager.js
  src/service/telemetry-injection-service.js
  test/modules/telemetry/config.json
  test/modules/telemetry/telemetry.js
Labels: bug, release, v6

#2747 OriginTrail Testnet Prerelease v6.0.17
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/constants/constants.js
  src/migration/telemetry-module-user-configuration-migration.js
  src/modules/base-module-manager.js
  src/modules/module-config-validation.js
  src/modules/telemetry/implementation/ot-telemetry.js
  src/modules/telemetry/telemetry-module-manager.js
  src/service/telemetry-injection-service.js
  test/modules/telemetry/config.json
  test/modules/telemetry/telemetry.js
Labels: bug, release, v6

#2748 OriginTrail Testnet Release v6.0.17
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/constants/constants.js
  src/migration/telemetry-module-user-configuration-migration.js
  src/modules/base-module-manager.js
  src/modules/module-config-validation.js
  src/modules/telemetry/implementation/ot-telemetry.js
  src/modules/telemetry/telemetry-module-manager.js
  src/service/telemetry-injection-service.js
  test/modules/telemetry/config.json
  test/modules/telemetry/telemetry.js
Labels: bug, improvement, release, v6

#2749 Implemented Fallback RPC Provider
  config/config.json
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, v6

#2751 OriginTrail Devnet Prerelease v6.0.18
  config/config.json
  package-lock.json
  package.json
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, release, v6

#2754 OriginTrail Devnet Release v6.0.18
  config/config.json
  package-lock.json
  package.json
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, release, v6

#2757 OriginTrail Devnet Release v6.0.18 - Hotfix 1
  package-lock.json
  package.json
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
Labels: hotfix, release, v6

#2763 OriginTrail Devnet Prerelease v6.0.18 - Hotfix 3
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2764 OriginTrail Devnet Release v6.0.18 - Hotfix 3
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2765 OriginTrail Testnet Prerelease v6.0.18 - Hotfix 2
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2766 OriginTrail Testnet Release v6.0.18 - Hotfix 2
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2767 OriginTrail Mainnet Release v6.0.18
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/common/validate-asset-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/constants/constants.js
  src/migration/telemetry-module-user-configuration-migration.js
  src/modules/base-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/module-config-validation.js
  src/modules/telemetry/implementation/ot-telemetry.js
  src/modules/telemetry/telemetry-module-manager.js
  src/service/telemetry-injection-service.js
  test/modules/telemetry/config.json
  test/modules/telemetry/telemetry.js
Labels: release

#2768 OriginTrail Mainnet Release v6.0.18
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/common/validate-asset-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/constants/constants.js
  src/migration/telemetry-module-user-configuration-migration.js
  src/modules/base-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/module-config-validation.js
  src/modules/telemetry/implementation/ot-telemetry.js
  src/modules/telemetry/telemetry-module-manager.js
  src/service/telemetry-injection-service.js
  test/modules/telemetry/config.json
  test/modules/telemetry/telemetry.js
Labels: release

#2771 Remove empty proof check
  package.json
  src/commands/protocols/common/submit-proofs-command.js
Labels: hotfix, v6

#2772 Added try-catch for commits/proofs scheduling
  src/commands/protocols/common/epoch-check-command.js
Labels: bug, hotfix, v6

#2770 Fix provider logger
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2773 OriginTrail Devnet Prerelease v6.0.19
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, hotfix, release, v6

#2774 OriginTrail Devnet Release v6.0.19
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, hotfix, release, v6

#2775 OriginTrail Testnet Prerelease v6.0.19
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, hotfix, release, v6

#2776 OriginTrail Testnet Release v6.0.19
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, hotfix, release, v6

#2778 OriginTrail Mainnet Release v6.0.19
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, hotfix, release, v6

#2780 Added service agreements operational db migration
  index.js
  ot-node.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/service-agreements-op-database-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/file-service.js
Labels: bug

#2783 Fixed non-breaking dependency vulnerabilities
  package-lock.json
Labels: improvement, chore, v6

#2782 Commit/Proofs Command Retry Mechanism Rework
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement, v6

#2784 Bumped version to 6.0.20
  package-lock.json
  package.json
  src/constants/constants.js
Labels: v6

#2785 OriginTrail Devnet Prerelease v6.0.20
  index.js
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/service-agreements-op-database-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/validation/validation-module-manager.js
  src/service/file-service.js
  test/unit/modules/repository/config.json
  test/unit/modules/repository/repository.test.js
  test/unit/modules/triple-store/config.json
  test/unit/modules/triple-store/triple-store.test.js
  test/unit/modules/validation/config.json
  test/unit/modules/validation/validation-module-manager.test.js
Labels: bug, improvement, release, dependencies, v6

#2787 Fixed migration for SAs, reduced number of blockchain calls 2 times
  package-lock.json
  package.json
  src/migration/service-agreements-op-database-migration.js
  src/service/ual-service.js
Labels: hotfix, v6

#2788 OriginTrail Devnet Prerelease v6.0.20 Hotfix 1
  package-lock.json
  package.json
  src/migration/service-agreements-op-database-migration.js
  src/service/ual-service.js
Labels: improvement, release, v6

#2790 Added migration for missing/redundant KA historical assertion links
  src/migration/migration-executor.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
Labels: bug, improvement, v6

#2789 Invalid SAs migration rework
  ot-node.js
  package-lock.json
  package.json
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/private-assets-metadata-migration.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
  src/migration/service-agreements-op-database-migration.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/triple-store-service.js
Labels: bug, improvement, v6

#2792 OriginTrail Devnet Prerelease v6.0.20 [Final]
  ot-node.js
  package-lock.json
  package.json
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/private-assets-metadata-migration.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
  src/migration/service-agreements-op-database-migration.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/triple-store-service.js
Labels: release, v6

#2793 OriginTrail Devnet Release v6.0.20 [Final]
  ot-node.js
  package-lock.json
  package.json
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/private-assets-metadata-migration.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
  src/migration/service-agreements-op-database-migration.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/triple-store-service.js
Labels: release, v6

#2794 OriginTrail Testnet Prerelease v6.0.20
  index.js
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/private-assets-metadata-migration.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/modules/validation/validation-module-manager.js
  src/service/file-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  test/unit/modules/repository/config.json
  test/unit/modules/repository/repository.test.js
  test/unit/modules/triple-store/config.json
  test/unit/modules/triple-store/triple-store.test.js
  test/unit/modules/validation/config.json
  test/unit/modules/validation/validation-module-manager.test.js
Labels: bug, improvement, release, dependencies, v6

#2797 OriginTrail Mainnet Prerelease v6.0.20
  index.js
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/private-assets-metadata-migration.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/modules/validation/validation-module-manager.js
  src/service/file-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  test/unit/modules/repository/config.json
  test/unit/modules/repository/repository.test.js
  test/unit/modules/triple-store/config.json
  test/unit/modules/triple-store/triple-store.test.js
  test/unit/modules/validation/config.json
  test/unit/modules/validation/validation-module-manager.test.js
Labels: bug, improvement, release, dependencies, v6

#2799 OriginTrail Mainnet Release v6.0.20
  index.js
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/migration/base-migration.js
  src/migration/migration-executor.js
  src/migration/private-assets-metadata-migration.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/modules/validation/validation-module-manager.js
  src/service/file-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  test/unit/modules/repository/config.json
  test/unit/modules/repository/repository.test.js
  test/unit/modules/triple-store/config.json
  test/unit/modules/triple-store/triple-store.test.js
  test/unit/modules/validation/config.json
  test/unit/modules/validation/validation-module-manager.test.js
Labels: bug, improvement, release, dependencies, v6

#2801 Added Bdd tests for multichain
  package.json
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/datasets/requests.json
  test/bdd/steps/api/get.mjs
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/api/update.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/bdd/steps/lib/state.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
Labels: feature, v6

#2800 Added Gnosis service
  config/config.json
  src/constants/constants.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
Labels: feature, v6

#2809 OriginTrail Devnet Prerelease v6.1.0
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/protocol-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/constants/constants.js
  src/controllers/http-api/http-api-router.js
  src/controllers/rpc/rpc-router.js
  src/migration/migration-executor.js
  src/migration/ual-extension-triple-store-migration.js
  src/migration/ual-extension-user-configuration-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/http-client/implementation/middleware/blockchain-id-midleware.js
  src/modules/repository/implementation/sequelize/migrations/20233010122500-update-blockchain-id.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/datasets/requests.json
  test/bdd/steps/api/get.mjs
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/api/update.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/bdd/steps/lib/state.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
  tools/local-network-setup/.origintrail_noderc_template.json
  tools/local-network-setup/README.md
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/run-local-blockchain.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release, feature, v6

#2810 OriginTrail Devnet Release v6.1.0
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-stake.js
  src/commands/protocols/common/protocol-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/constants/constants.js
  src/controllers/http-api/http-api-router.js
  src/controllers/rpc/rpc-router.js
  src/migration/migration-executor.js
  src/migration/ual-extension-triple-store-migration.js
  src/migration/ual-extension-user-configuration-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/http-client/http-client-module-manager.js
  src/modules/http-client/implementation/express-http-client.js
  src/modules/http-client/implementation/middleware/blockchain-id-midleware.js
  src/modules/repository/implementation/sequelize/migrations/20233010122500-update-blockchain-id.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  src/service/validation-service.js
  test/bdd/features/get-errors.feature
  test/bdd/features/get.feature
  test/bdd/features/publish-errors.feature
  test/bdd/features/publish.feature
  test/bdd/features/update-errors.feature
  test/bdd/features/update.feature
  test/bdd/steps/api/datasets/requests.json
  test/bdd/steps/api/get.mjs
  test/bdd/steps/api/publish.mjs
  test/bdd/steps/api/update.mjs
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/common.mjs
  test/bdd/steps/hooks.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/bdd/steps/lib/state.mjs
  test/utilities/dkg-client-helper.mjs
  test/utilities/steps-utils.mjs
  tools/local-network-setup/.origintrail_noderc_template.json
  tools/local-network-setup/README.md
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/run-local-blockchain.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release, feature, v6

#2811 OriginTrail Devnet Prerelease v6.1.0.hotfix1
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/migration/migration-executor.js
  src/migration/network-private-key-migration.js
  src/migration/ual-extension-user-configuration-migration.js
  src/modules/network/implementation/libp2p-service.js
  src/service/file-service.js
Labels: hotfix

#2812 OriginTrail Devnet Release v6.1.0.hotfix1
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/migration/migration-executor.js
  src/migration/network-private-key-migration.js
  src/migration/ual-extension-user-configuration-migration.js
  src/modules/network/implementation/libp2p-service.js
  src/service/file-service.js
Labels: hotfix

#2813 Execute triple store migration in chunks
  package-lock.json
  package.json
  src/migration/ual-extension-triple-store-migration.js
Labels: bug, v6
