Repository OriginTrail/ot-node, pull requests merged in 2023-04, with the labels that each got.

#2420 Version update, added template for one click installer
  installer/data/template/.origintrail_noderc_one_click_testnet.json
  package-lock.json
  package.json
Labels: chore

#2421 Devnet Prerelease 6.0.4 - Version update
  installer/data/template/.origintrail_noderc_one_click_testnet.json
  package-lock.json
  package.json
Labels: chore

#2423 Testnet Prerelease 6.0.4 - Version update
  installer/data/template/.origintrail_noderc_one_click_testnet.json
  package-lock.json
  package.json
Labels: chore

#2431 Hotfix for epoch start time calculation
  src/commands/common/commands-cleaner-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/private-assets-metadata-migration.js
Labels: bug

#2432 add migration for period column type
  src/modules/repository/implementation/sequelize/migrations/20230413194400-update-command-period-type.js
Labels: bug, v6

#2433 Bump the version to 6.0.5
  package-lock.json
  package.json
Labels: chore

#2435 Devnet 6.0.5 Prerelease
  package-lock.json
  package.json
  src/commands/common/commands-cleaner-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/private-assets-metadata-migration.js
  src/modules/repository/implementation/sequelize/migrations/20230413194400-update-command-period-type.js
Labels: chore

#2436 Devnet 6.0.5 Release
  package-lock.json
  package.json
  src/commands/common/commands-cleaner-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/private-assets-metadata-migration.js
  src/modules/repository/implementation/sequelize/migrations/20230413194400-update-command-period-type.js
Labels: chore

#2439 Mainnet 6.0.5 Prerelease
  package-lock.json
  package.json
  src/commands/common/commands-cleaner-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/private-assets-metadata-migration.js
  src/modules/repository/implementation/sequelize/migrations/20230413194400-update-command-period-type.js
Labels: release

#2440 Mainnet 6.0.5 Release
  package-lock.json
  package.json
  src/commands/common/commands-cleaner-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/private-assets-metadata-migration.js
  src/modules/repository/implementation/sequelize/migrations/20230413194400-update-command-period-type.js
Labels: release

#2442 select commit and proof manager contract according to latest state index
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2443 Devnet 6.0.6 Prerelease
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore, release, v6

#2445 Testnet 6.0.6 Prerelease
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore, release, v6

#2446 Testnet 6.0.6 Release
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore, release, v6

#2447 Mainnet 6.0.6 Prerelease
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore, release, v6

#2448 Mainnet 6.0.6 Release
  package-lock.json
  package.json
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore, release, v6

#2419 Unit tests for publish, get and update services
  .eslintrc.cjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/command-executor-mock.js
  test/unit/mock/operation-id-service-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/get-service.test.js
  test/unit/service/operation-service.test.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
Labels: improvement

#2417 remove unused dependencies
  dependencies.md
  package-lock.json
  package.json
  src/service/sharding-table-service.js
  src/worker/l1-worker.js
  src/worker/worker-pool.js
  test/bdd/steps/blockchain.mjs
Labels: chore, v6

#2409 bulk handle blockchain events
  ot-node.js
  src/constants/constants.js
  src/migration/mark-old-blockchain-events-as-processed-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/sharding-table-service.js
Labels: improvement, v6

#2426 fix mark operation status
  src/commands/common/validate-asset-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/constants/constants.js
  src/controllers/http-api/get-http-api-controller.js
  src/controllers/http-api/publish-http-api-controller.js
  src/controllers/http-api/update-http-api-controller.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/ual-service.js
  src/service/update-service.js
  src/service/validation-service.js
  test/unit/service/operation-service.test.js
  test/unit/service/validation-service.test.js
Labels: bug, v6

#2454 fix abi imports for commit and proof managers
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2452 remove agreement start and end time from triple store
  ot-node.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/migration/private-assets-metadata-migration.js
  src/migration/remove-agreement-start-end-time-migration.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
Labels: improvement, v6

#2456 fix handling of state finalized event
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/triple-store-service.js
Labels: bug, v6

#2462 Devnet 6.0.7 Prerelease
  .eslintrc.cjs
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/constants/constants.js
  src/controllers/http-api/get-http-api-controller.js
  src/controllers/http-api/publish-http-api-controller.js
  src/controllers/http-api/update-http-api-controller.js
  src/migration/mark-old-blockchain-events-as-processed-migration.js
  src/migration/private-assets-metadata-migration.js
  src/migration/remove-agreement-start-end-time-migration.js
  src/migration/triple-store-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  src/service/update-service.js
  src/service/validation-service.js
  src/worker/l1-worker.js
  src/worker/worker-pool.js
  test/bdd/steps/blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/command-executor-mock.js
  test/unit/mock/operation-id-service-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/get-service.test.js
  test/unit/service/operation-service.test.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
  test/unit/service/validation-service.test.js
Labels: chore, release, v6

#2464 fix triple store metadata migration
  package-lock.json
  package.json
  src/migration/triple-store-metadata-migration.js
Labels: bug, v6

#2465 Devnet 6.0.7 Prerelease Hotfix
  package-lock.json
  package.json
  src/migration/triple-store-metadata-migration.js
Labels: hotfix, release, v6

#2466 Devnet 6.0.7 Release Hotfix
  package-lock.json
  package.json
  src/migration/triple-store-metadata-migration.js
Labels: hotfix, release, v6

#2467 bump version to 6.0.7
  package-lock.json
  package.json
Labels: chore, v6

#2469 bump version to 6.0.7
  package-lock.json
  package.json
Labels: chore, v6

#2455 [TBD] Local blockchain params setting update
  package-lock.json
  package.json
  test/bdd/steps/lib/local-blockchain.mjs
Labels: improvement, internal process

#2457 ethers wait for transaction receipt
  .github/workflows/TEST-bdd.yml
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/constants/constants.js
  src/modules/blockchain/implementation/web3-service.js
  test/bdd/steps/blockchain.mjs
Labels: bug, v6

#2470 Devnet 6.0.7 Prerelease Hotfix
  package-lock.json
  package.json
  src/migration/triple-store-metadata-migration.js
  test/bdd/steps/lib/local-blockchain.mjs
Labels: hotfix, release, v6

#2472 Testnet 6.0.7 Prerelease
  .eslintrc.cjs
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/constants/constants.js
  src/controllers/http-api/get-http-api-controller.js
  src/controllers/http-api/publish-http-api-controller.js
  src/controllers/http-api/update-http-api-controller.js
  src/migration/mark-old-blockchain-events-as-processed-migration.js
  src/migration/private-assets-metadata-migration.js
  src/migration/remove-agreement-start-end-time-migration.js
  src/migration/triple-store-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  src/service/update-service.js
  src/service/validation-service.js
  src/worker/l1-worker.js
  src/worker/worker-pool.js
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/command-executor-mock.js
  test/unit/mock/operation-id-service-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/get-service.test.js
  test/unit/service/operation-service.test.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
  test/unit/service/validation-service.test.js
Labels: chore, release, v6

#2473 fix resolve UAL in triple store metadata migration
  src/migration/triple-store-metadata-migration.js
  src/service/ual-service.js
Labels: hotfix, release, v6

#2474 fix resolve UAL in triple store metadata migration (#2473)
  src/migration/triple-store-metadata-migration.js
  src/service/ual-service.js
Labels: hotfix, release, v6

#2475 Testnet 6.0.7 Prerelease Hotfix
  src/migration/triple-store-metadata-migration.js
  src/service/ual-service.js
Labels: hotfix, release, v6
