Repository OriginTrail/ot-node, pull requests merged in 2023-05, with the labels that each got.

#2478 add blockchain event processed index
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20230502110300-add-blockchain-event-index.js
Labels: improvement, v6

#2480 add blockchain event processed index (#2478)
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20230502110300-add-blockchain-event-index.js
Labels: improvement, v6

#2481 add blockchain event processed index (#2478)
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20230502110300-add-blockchain-event-index.js
Labels: improvement, v6

#2482 revert version to 6.0.7
  package-lock.json
  package.json
Labels: chore, v6

#2483 bump version to 6.0.7 (#2482)
  package-lock.json
  package.json
Labels: chore, v6

#2484 bump version to 6.0.7 (#2482)
  package-lock.json
  package.json
Labels: chore, v6

#2485 bump version to 6.0.7 (#2482)
  package-lock.json
  package.json
Labels: chore, v6

#2486 fix epoch check command queries
  src/commands/protocols/common/epoch-check-command.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  test/modules/repository/config.json
  test/modules/repository/repository.js
  test/modules/triple-store/triple-store.js
Labels: bug, v6

#2487 Mainnet 6.0.7 Release
  .eslintrc.cjs
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/constants/constants.js
  src/controllers/http-api/get-http-api-controller.js
  src/controllers/http-api/publish-http-api-controller.js
  src/controllers/http-api/update-http-api-controller.js
  src/migration/mark-old-blockchain-events-as-processed-migration.js
  src/migration/private-assets-metadata-migration.js
  src/migration/remove-agreement-start-end-time-migration.js
  src/migration/triple-store-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230502110300-add-blockchain-event-index.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  src/service/update-service.js
  src/service/validation-service.js
  src/worker/l1-worker.js
  src/worker/worker-pool.js
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/command-executor-mock.js
  test/unit/mock/operation-id-service-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/get-service.test.js
  test/unit/service/operation-service.test.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2488 Mainnet 6.0.7 Release
  .eslintrc.cjs
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/get/sender/get-latest-assertion-id-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/constants/constants.js
  src/controllers/http-api/get-http-api-controller.js
  src/controllers/http-api/publish-http-api-controller.js
  src/controllers/http-api/update-http-api-controller.js
  src/migration/mark-old-blockchain-events-as-processed-migration.js
  src/migration/private-assets-metadata-migration.js
  src/migration/remove-agreement-start-end-time-migration.js
  src/migration/triple-store-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230502110300-add-blockchain-event-index.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
  src/service/update-service.js
  src/service/validation-service.js
  src/worker/l1-worker.js
  src/worker/worker-pool.js
  test/bdd/steps/blockchain.mjs
  test/bdd/steps/lib/local-blockchain.mjs
  test/unit/mock/blockchain-module-manager-mock.js
  test/unit/mock/command-executor-mock.js
  test/unit/mock/operation-id-service-mock.js
  test/unit/mock/repository-module-manager-mock.js
  test/unit/mock/validation-module-manager-mock.js
  test/unit/service/get-service.test.js
  test/unit/service/operation-service.test.js
  test/unit/service/publish-service.test.js
  test/unit/service/update-service.test.js
  test/unit/service/validation-service.test.js
Labels: release, v6

#2490 level V6/release/mainnet and v6/develop
  src/migration/triple-store-metadata-migration.js
  src/modules/repository/implementation/sequelize/migrations/20230502110300-add-blockchain-event-index.js
  src/service/ual-service.js
Labels: chore

#2494 Devnet 6.0.8 Prerelease
  .github/workflows/TEST-bdd.yml
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  test/bdd/steps/blockchain.mjs
Labels: release, v6

#2495 Devnet 6.0.8 Release
  .github/workflows/TEST-bdd.yml
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  test/bdd/steps/blockchain.mjs
Labels: release, v6

#2496 add better error handling to service agreement migration
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2498 bump version
  package-lock.json
  package.json
Labels: chore, v6

#2497 add better error handling to service agreement migration (#2496)
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2499 add better error handling to service agreement migration (#2496)
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2500 fix service agreement migration
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2501 fix service agreement migration (#2500)
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2502 fix service agreement migration (#2500)
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2503 reduce sleep time in service agreement migration
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2504 reduce sleep time in service agreement migration (#2503)
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2505 reduce sleep time in service agreement migration (#2503)
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2508 Fix switch rpc on error
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
Labels: bug, v6

#2507 handle errors when getting commits in service agreement migration
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
Labels: bug, v6

#2510 Devnet 6.0.8 Prerelease Hotfix
  dependencies.md
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
Labels: hotfix, release, v6

#2511 Devnet 6.0.8 Release Hotfix
  dependencies.md
  package-lock.json
  package.json
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
Labels: hotfix, release, v6

#2512 Testnet 6.0.8 Prerelease
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  test/bdd/steps/blockchain.mjs
Labels: release, v6

#2513 Testnet 6.0.8 Release
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  test/bdd/steps/blockchain.mjs
Labels: release, v6

#2514 refactor repository module
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/modules/repository/implementation/sequelize/repositories/user-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
Labels: chore, v6

#2519 Mainnet 6.0.8 Prerelease
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  test/bdd/steps/blockchain.mjs
Labels: release, v6

#2515 fix logic for getting past blockchain events
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2520 Mainnet 6.0.9 Release
  .github/workflows/TEST-bdd.yml
  dependencies.md
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  test/bdd/steps/blockchain.mjs
Labels: release, v6

#2492 add new epoch check commands
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  test/modules/repository/config.json
  test/modules/repository/repository.js
  test/modules/triple-store/triple-store.js
Labels: improvement, v6

#2506 add remove old epoch commands migration
  ot-node.js
  src/migration/remove-old-epoch-commands-migration.js
Labels: feature, v6

#2523 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2522 Devnet 6.0.9 Prerelease
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/remove-old-epoch-commands-migration.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/modules/repository/implementation/sequelize/repositories/user-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  test/modules/repository/config.json
  test/modules/repository/repository.js
  test/modules/triple-store/triple-store.js
Labels: release, v6

#2524 fix import statement for constants
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
Labels: bug, v6

#2525 fix import statement for constants (#2524)
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
Labels: bug, v6

#2527 lower transaction confirmations to 1
  src/constants/constants.js
Labels: bug, v6

#2528 lower transaction confirmations to 1 (#2527)
  src/constants/constants.js
Labels: bug, v6

#2526 Devnet 6.0.9 Release
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/remove-old-epoch-commands-migration.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/modules/repository/implementation/sequelize/repositories/user-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  test/modules/repository/config.json
  test/modules/repository/repository.js
  test/modules/triple-store/triple-store.js
Labels: release, v6

#2529 fix rank calculation when node not in r2
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2531 Devnet 6.0.9 Prerelease Hotfix
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: hotfix, release, v6

#2532 Devnet 6.0.9 Release Hotfix
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: hotfix, release, v6

#2533 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2534 bump version to 6.0.9 (#2533)
  package-lock.json
  package.json
Labels: chore, v6

#2535 bump version to 6.0.9 (#2533)
  package-lock.json
  package.json
Labels: chore, v6

#2536 Testnet 6.0.9 Prerelease
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  scripts/set-operator-fee.js
  scripts/set-stake.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/epoch-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/publish/receiver/calculate-proofs-command.js
  src/commands/protocols/publish/receiver/epoch-check-command.js
  src/commands/protocols/publish/receiver/submit-commit-command.js
  src/commands/protocols/publish/receiver/submit-proofs-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/remove-old-epoch-commands-migration.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/modules/repository/implementation/sequelize/repositories/user-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  test/modules/repository/config.json
  test/modules/repository/repository.js
  test/modules/triple-store/triple-store.js
Labels: release, v6

#2537 limit number of txs based on current queue length
  src/commands/protocols/common/epoch-check-command.js
Labels: bug, v6

#2538 wait for txs to complete in submit commit and proof commands
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
Labels: bug, v6

#2540 Devnet 6.0.9 Prerelease Hotfix
  .eslintrc.cjs
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/common/dial-peers-command.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/models/ability.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/models/blockchain.js
  src/modules/repository/implementation/sequelize/models/commands.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/models/get-response.js
  src/modules/repository/implementation/sequelize/models/get.js
  src/modules/repository/implementation/sequelize/models/operation_ids.js
  src/modules/repository/implementation/sequelize/models/publish-response.js
  src/modules/repository/implementation/sequelize/models/publish.js
  src/modules/repository/implementation/sequelize/models/role-ability.js
  src/modules/repository/implementation/sequelize/models/role.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/models/token.js
  src/modules/repository/implementation/sequelize/models/update-response.js
  src/modules/repository/implementation/sequelize/models/update.js
  src/modules/repository/implementation/sequelize/models/user.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/operation-id-service.js
  src/service/sharding-table-service.js
  test/modules/repository/repository.js
  test/unit/mock/repository-module-manager-mock.js
Labels: hotfix, release, v6

#2541 Devnet 6.0.9 Release Hotfix
  .eslintrc.cjs
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/common/dial-peers-command.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/models/ability.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/models/blockchain.js
  src/modules/repository/implementation/sequelize/models/commands.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/models/get-response.js
  src/modules/repository/implementation/sequelize/models/get.js
  src/modules/repository/implementation/sequelize/models/operation_ids.js
  src/modules/repository/implementation/sequelize/models/publish-response.js
  src/modules/repository/implementation/sequelize/models/publish.js
  src/modules/repository/implementation/sequelize/models/role-ability.js
  src/modules/repository/implementation/sequelize/models/role.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/models/token.js
  src/modules/repository/implementation/sequelize/models/update-response.js
  src/modules/repository/implementation/sequelize/models/update.js
  src/modules/repository/implementation/sequelize/models/user.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/operation-id-service.js
  src/service/sharding-table-service.js
  test/modules/repository/repository.js
  test/unit/mock/repository-module-manager-mock.js
Labels: hotfix, release, v6

#2542 Testnet 6.0.9 Prerelease Hotfix
  .eslintrc.cjs
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/common/dial-peers-command.js
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/models/ability.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/models/blockchain.js
  src/modules/repository/implementation/sequelize/models/commands.js
  src/modules/repository/implementation/sequelize/models/event.js
  src/modules/repository/implementation/sequelize/models/get-response.js
  src/modules/repository/implementation/sequelize/models/get.js
  src/modules/repository/implementation/sequelize/models/operation_ids.js
  src/modules/repository/implementation/sequelize/models/publish-response.js
  src/modules/repository/implementation/sequelize/models/publish.js
  src/modules/repository/implementation/sequelize/models/role-ability.js
  src/modules/repository/implementation/sequelize/models/role.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/models/token.js
  src/modules/repository/implementation/sequelize/models/update-response.js
  src/modules/repository/implementation/sequelize/models/update.js
  src/modules/repository/implementation/sequelize/models/user.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/operation-id-service.js
  src/service/sharding-table-service.js
  test/modules/repository/repository.js
  test/unit/mock/repository-module-manager-mock.js
Labels: hotfix, release, v6

#2543 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2544 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2546 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2548 dont overwrite last commit, proof checks on update
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: bug, v6

#2549 bump version to 6.0.9+hotfix.3
  package-lock.json
  package.json
Labels: chore, v6

#2550 Devnet 6.0.9 Prerelease Hotfix 3
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: hotfix, release, v6

#2551 Devnet 6.0.9 Release Hotfix 3
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: hotfix, release, v6

#2552 Testnet 6.0.9 Prerelease Hotfix 3
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: hotfix, release, v6

#2553 Testnet 6.0.9 Release Hotfix 3
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
Labels: hotfix, release, v6

#2554 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2556 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2557 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2558 bump version to 6.0.9
  package-lock.json
  package.json
Labels: chore, v6

#2561 reduce blockchain calls
  src/commands/protocols/common/epoch-check-command.js
Labels: improvement, v6

#2539 fix filtering of pending commands during replay
  src/commands/command-executor.js
Labels: bug, v6

#2565 Fixed bug when command is not repeated during recovery
  src/commands/command-executor.js
Labels: bug
