Repository OriginTrail/ot-node, pull requests merged in 2024-03, with the labels that each got.

#3077 OriginTrail Devnet Release v6.2.2 Hotfix 2
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
Labels: hotfix, release

#3078 OriginTrail Tevnet Prerelease v6.2.2 Hotfix 2
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
Labels: hotfix, release

#3079 OriginTrail Tesnet Release v6.2.2 Hotfix 2
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
Labels: hotfix, release

#3072 OriginTrail Mainnet Release v6.2.2
  ot-node.js
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: release

#3093 V6/insufficient fund handling
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
Labels: chore

#3091 Implement round robin for selecting transaction queue
  src/modules/blockchain/implementation/web3-service.js
Labels: improvement

#3090 Add blockchain call validation
  package-lock.json
  package.json
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/service/blockchain-event-listener-service.js
Labels: improvement

#3094 OriginTrail Devnet Prerelease v6.2.3
  package-lock.json
  package.json
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/sharding-table-service.js
Labels: release

#3096 OriginTrail Devnet Release v6.2.3
  package-lock.json
  package.json
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/sharding-table-service.js
Labels: release

#3097 OriginTrail Testnet Prerelease v6.2.3
  package-lock.json
  package.json
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/sharding-table-service.js
Labels: release

#3100 OriginTrail Testnet Release v6.2.3
  package-lock.json
  package.json
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/sharding-table-service.js
Labels: release

#3101 OriginTrail Mainnet Prerelease v6.2.3
  package-lock.json
  package.json
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/sharding-table-service.js
Labels: release

#3103 OriginTrail Mainnet Release v6.2.3
  package-lock.json
  package.json
  src/commands/common/send-transaction-command.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/sharding-table-service.js
Labels: release
