Repository OriginTrail/ot-node, pull requests merged in 2024-12, with the labels that each got.

#3447 Blockchain event listener improvements
  config/config.json
  installer/installer.sh
  ot-node.js
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/blockchain-event-listener/event-listener-command.js
  src/commands/command-executor.js
  src/constants/constants.js
  src/modules/blockchain-events/implementation/blockchain-events-service.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/blockchain-events/implementation/ot-ethers/web3-service-validator.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/module-config-validation.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-events-service.js
  src/service/sharding-table-service.js
  tools/local-network-setup/.origintrail_noderc_template.json
  tools/local-network-setup/generate-config-files.js
Labels: improvement, V8

#3448 [V8] [IMPROVEMENT] Added operational db transactions for event listener
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/modules/repository/implementation/sequelize/migrations/20230419140000-create-service-agreements.js
  src/modules/repository/implementation/sequelize/migrations/20233010122500-update-blockchain-id.js
  src/modules/repository/implementation/sequelize/migrations/20240221162000-add-service-agreement-data-source.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements-for-gnosis.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
Labels: improvement, V8

#3450 Feature/get metadata flag
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/triple-store-service.js
Labels: feature, V8

#3453 Reworked logic for blockchain events handling and sharding table pulling
  ot-node.js
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/blockchain-event-listener/event-listener-command.js
  src/commands/command-executor.js
  src/commands/common/sharding-table-check-command.js
  src/constants/constants.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
Labels: improvement, V8

#3456 Implemented logic for Event Listener to be aware of contract changes and invalidate events for changed contracts
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/constants/constants.js
  src/modules/blockchain-events/blockchain-events-module-manager.js
  src/modules/blockchain-events/implementation/blockchain-events-service.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/modules/repository/implementation/sequelize/repositories/user-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-events-service.js
Labels: bug, V8

#3454 Improved logic for events fetching, reworked provider init, fixed logic for storing blockchain events in operational db
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/constants/constants.js
  src/modules/blockchain-events/blockchain-events-module-manager.js
  src/modules/blockchain-events/implementation/blockchain-events-service.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/migrations/20241202214500-update-blockchain-table.js
  src/modules/repository/implementation/sequelize/models/blockchain-event.js
  src/modules/repository/implementation/sequelize/models/blockchain.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-repository.js
  src/modules/repository/implementation/sequelize/repositories/command-repository.js
  src/modules/repository/implementation/sequelize/repositories/event-repository.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/repositories/token-repository.js
  src/modules/repository/implementation/sequelize/repositories/user-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-events-service.js
Labels: improvement, V8

#3451 Get supports both KA and KC UALs
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/rpc/get-rpc-controller.js
  src/service/get-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
Labels: feature, V8

#3457 [V8] [FEATURE] Finality API
  package-lock.json
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/finality/receiver/v1.0.0/v1-0-0-handle-finality-request-command.js
  src/commands/protocols/finality/sender/finality-find-shard-command.js
  src/commands/protocols/finality/sender/finality-schedule-messages-command.js
  src/commands/protocols/finality/sender/network-finality-command.js
  src/commands/protocols/finality/sender/v1.0.0/v1-0-0-finality-request-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/finality-http-api-controller-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/controllers/http-api/v1/finality-http-api-controller-v1.js
  src/controllers/rpc/finality-rpc-controller.js
  src/controllers/rpc/rpc-router.js
  src/modules/repository/implementation/sequelize/migrations/20241203125000-create-finality.js
  src/modules/repository/implementation/sequelize/migrations/20241203125001-create-finality-response.js
  src/modules/repository/implementation/sequelize/models/finality-response.js
  src/modules/repository/implementation/sequelize/models/finality.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/finality-service.js
  src/service/triple-store-service.js
Labels: feature, V8

#3459 Commented out RDF-star triples generation
  src/service/triple-store-service.js
Labels: chore, V8

#3455 [V8] [FEATURE] Added initial queries for public quads extraction
  src/constants/constants.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/data-service.js
Labels: feature, V8

#3460 V8/improvement/updated assertion tools
  package-lock.json
  package.json
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/modules/validation/implementation/merkle-validation.js
  src/modules/validation/validation-module-manager.js
  src/service/data-service.js
  src/service/triple-store-service.js
  src/service/validation-service.js
  src/workers/data-service-toNQuads-worker.js
Labels: improvement, V8

#3463 Bumped the version to 8.0.0-beta
  package-lock.json
  package.json
Labels: V8

#3468 OriginTrail v8.0.0-beta.4 Devnet Hotfix Release
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20241202214500-update-blockchain-table.js
Labels: release, V8

#3469 OriginTrail v8.0.0-beta.5 Devnet Release
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20241202214500-update-blockchain-table.js
Labels: release, V8

#3470 OriginTrail v8.0.0-beta.6 Devnet Release
  package-lock.json
  package.json
  src/service/bls-service.js
Labels: release, V8

#3475 Add support for private and public data for v8
  package-lock.json
  package.json
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/commands/protocols/publish/store-assertion-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/triple-store-service.js
Labels: feature, V8

#3486 Fix local store add signature on local store
  src/commands/local-store/local-store-command.js
Labels: chore, V8

#3485 Add mising await
  src/commands/protocols/common/protocol-request-command.js
Labels: chore, V8

#3495 [V8] [IMPROVEMENT] minAcks rework
  src/controllers/http-api/v1/result-http-api-controller-v1.js
  src/modules/repository/implementation/sequelize/migrations/20241212122200-add-min-acks-reached-column.js
  src/modules/repository/implementation/sequelize/models/operation_ids.js
  src/modules/repository/implementation/sequelize/repositories/operation-id-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/operation-service.js
  src/service/publish-service.js
  src/service/update-service.js
Labels: improvement, V8

#3492 Fix some of the events that are missing end, remove some unneeded events
  src/commands/protocols/ask/sender/network-ask-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/finality/sender/network-finality-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/network-get-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/network-update-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
Labels: chore, V8

#3494 Addd publish finality event connection to publish command
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/service/operation-id-service.js
Labels: chore

#3500 [V8] [IMPROVEMENT] Publisher Node Signature
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/commands/protocols/update/sender/v1.0.0/v1-0-0-update-request-command.js
  src/constants/constants.js
  src/controllers/http-api/v1/result-http-api-controller-v1.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  src/service/signature-service.js
Labels: improvement, V8

#3480 Emit status as error type PROTOCOL-NAME_ERROR
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/service/operation-id-service.js
Labels: chore

#3476 remove unneeded awaits for telemetry events
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
Labels: chore, V8

#3507 [V8] [IMPROVEMENT] Byte size validation
  package-lock.json
  package.json
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/protocols/publish/publish-validate-assertion-metadata-command.js
  src/constants/constants.js
  src/service/data-service.js
Labels: improvement, V8

#3514 Blockchain event listener fixes
  package-lock.json
  package.json
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
Labels: V8

#3516 Change hub for event listner
  config/config.json
  package-lock.json
  package.json
Labels: V8

#3517 Add on chain validation for publish and get
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-blockchain-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/triple-store-service.js
  src/service/validation-service.js
Labels: chore, V8

#3519 Implement retry if cached dataset doesnt exist on blockchain event catch
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/constants/constants.js
Labels: chore, V8

#3628 Add commands table pruning migration
  src/modules/repository/implementation/sequelize/migrations/20241226151800-prune-commands.js
Labels: bug, V8

#3627 Set correct hub for NeuroWeb blockchain events module
  config/config.json
Labels: bug, V8

#3629 Devnet Release v8.0.0+hotfix.1
  config/config.json
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20241226151800-prune-commands.js
Labels: release

#3630 Testent Prerelease V8.0.0+hotifx.1
  config/config.json
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20241226151800-prune-commands.js
Labels: release

#3626 Align Mainnet and develop branches
  installer/data/template/.origintrail_noderc_one_click_mainnet.json
  installer/data/template/.origintrail_noderc_one_click_testnet.json
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements- for-gnosis.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
Labels: chore, V8

#3631 Testent Release V8.0.0+hotifx.1
  config/config.json
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20241226151800-prune-commands.js
Labels: release

#3632 Mainnet Prerelease V8.0.0+hotifx.1
  config/config.json
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20241226151800-prune-commands.js
Labels: release

#3633 Mainnet Release V8.0.0+hotifx.1
  config/config.json
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/migrations/20241226151800-prune-commands.js
Labels: release

#3637 V8 Testnet Prerelease v8.0.0+hotifx.2
  package-lock.json
  package.json
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/modules/base-module-manager.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20240301095400-remove-corrupted-service-agreements- for-gnosis.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
Labels: release, V8

#3643 V8.0.0+hotfix.3 Mainnet Release
  package-lock.json
  package.json
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/modules/blockchain/blockchain-module-manager.js
Labels: release, V8

#3656 Increase default number of retries for insertKnowledgeCollection in tripleStoreService
  src/service/triple-store-service.js
Labels: chore

#3651 Fix/sql migrations
  src/modules/repository/implementation/sequelize/migrations/20240924161700-create-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/repository/implementation/sequelize/migrations/20241125151200-rename-keyword-column-to-datasetroot-in-responses.js
  src/modules/repository/implementation/sequelize/migrations/20241126114400-add-commands-priority.js
  src/modules/repository/implementation/sequelize/migrations/20241129120000-add-commands-is_blocking.js
  src/modules/repository/implementation/sequelize/migrations/20241129125800-remove-datasetroot-response-table.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/migrations/20241211204400-rename-ask.js
Labels: bug

#3653 Fix/gateway node can publish
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-find-shard-command.js
Labels: bug

#3654 Send finalization ACK after insert is complted
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/store-assertion-command.js
Labels: chore

#3655 Chore/change number of retries for read cached publish data command
  src/constants/constants.js
Labels: chore

#3659 V8 Hotfix 4 Devnet Release
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-find-shard-command.js
  src/commands/protocols/publish/store-assertion-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v1/get-http-api-controller-v1.js
  src/controllers/rpc/get-rpc-controller.js
  src/modules/repository/implementation/sequelize/migrations/20240924161700-create-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/repository/implementation/sequelize/migrations/20241125151200-rename-keyword-column-to-datasetroot-in-responses.js
  src/modules/repository/implementation/sequelize/migrations/20241126114400-add-commands-priority.js
  src/modules/repository/implementation/sequelize/migrations/20241129120000-add-commands-is_blocking.js
  src/modules/repository/implementation/sequelize/migrations/20241129125800-remove-datasetroot-response-table.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/migrations/20241211204400-rename-ask.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/triple-store-service.js
  v8-data-migration/constants.js
  v8-data-migration/run-data-migration.sh
  v8-data-migration/sqlite-utils.js
  v8-data-migration/v8-data-migration-utils.js
  v8-data-migration/v8-data-migration.js
Labels: release, V8

#3660 V8 Hotifx 4 Testnet Prerelease
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-find-shard-command.js
  src/commands/protocols/publish/store-assertion-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v1/get-http-api-controller-v1.js
  src/controllers/rpc/get-rpc-controller.js
  src/modules/repository/implementation/sequelize/migrations/20240924161700-create-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/repository/implementation/sequelize/migrations/20241125151200-rename-keyword-column-to-datasetroot-in-responses.js
  src/modules/repository/implementation/sequelize/migrations/20241126114400-add-commands-priority.js
  src/modules/repository/implementation/sequelize/migrations/20241129120000-add-commands-is_blocking.js
  src/modules/repository/implementation/sequelize/migrations/20241129125800-remove-datasetroot-response-table.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/migrations/20241211204400-rename-ask.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/triple-store-service.js
  v8-data-migration/constants.js
  v8-data-migration/run-data-migration.sh
  v8-data-migration/sqlite-utils.js
  v8-data-migration/v8-data-migration-utils.js
  v8-data-migration/v8-data-migration.js
Labels: release, V8

#3661 V8 Hotfix 4 Testnet Release
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-find-shard-command.js
  src/commands/protocols/publish/store-assertion-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v1/get-http-api-controller-v1.js
  src/controllers/rpc/get-rpc-controller.js
  src/modules/repository/implementation/sequelize/migrations/20240924161700-create-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/repository/implementation/sequelize/migrations/20241125151200-rename-keyword-column-to-datasetroot-in-responses.js
  src/modules/repository/implementation/sequelize/migrations/20241126114400-add-commands-priority.js
  src/modules/repository/implementation/sequelize/migrations/20241129120000-add-commands-is_blocking.js
  src/modules/repository/implementation/sequelize/migrations/20241129125800-remove-datasetroot-response-table.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/migrations/20241211204400-rename-ask.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/triple-store-service.js
  v8-data-migration/constants.js
  v8-data-migration/run-data-migration.sh
  v8-data-migration/sqlite-utils.js
  v8-data-migration/v8-data-migration-utils.js
  v8-data-migration/v8-data-migration.js
Labels: release, V8

#3663 V8 Hotfix 4 Mainnet Prerlease
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-find-shard-command.js
  src/commands/protocols/publish/store-assertion-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v1/get-http-api-controller-v1.js
  src/controllers/rpc/get-rpc-controller.js
  src/modules/repository/implementation/sequelize/migrations/20240924161700-create-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/repository/implementation/sequelize/migrations/20241125151200-rename-keyword-column-to-datasetroot-in-responses.js
  src/modules/repository/implementation/sequelize/migrations/20241126114400-add-commands-priority.js
  src/modules/repository/implementation/sequelize/migrations/20241129120000-add-commands-is_blocking.js
  src/modules/repository/implementation/sequelize/migrations/20241129125800-remove-datasetroot-response-table.js
  src/modules/repository/implementation/sequelize/migrations/20241201152000-update-blockchain-events.js
  src/modules/repository/implementation/sequelize/migrations/20241211204400-rename-ask.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/triple-store-service.js
  v8-data-migration/constants.js
  v8-data-migration/run-data-migration.sh
  v8-data-migration/sqlite-utils.js
  v8-data-migration/v8-data-migration-utils.js
  v8-data-migration/v8-data-migration.js
Labels: release, V8
