Repository OriginTrail/ot-node, pull requests merged in 2024-06, with the labels that each got.

#3178 Hotfix for federated query support
  package-lock.json
  package.json
  src/commands/query/query-command.js
Labels: bug

#3179 OriginTrail Devnet Prerelease v6.4.0 Hotfix 3
  package-lock.json
  package.json
  src/commands/query/query-command.js
Labels: release

#3180 OriginTrail Devnet Release v6.4.0 Hotfix 3
  package-lock.json
  package.json
  src/commands/query/query-command.js
Labels: release

#3181 OriginTrail Testnet Prerelease v6.4.0
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/protocol-init-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-init-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/controllers/rpc/publish-rpc-controller.js
  src/controllers/rpc/update-rpc-controller.js
Labels: release

#3182 OriginTrail Testnet Prerelease v6.4.0
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240429083058-create-paranet.js
  src/modules/repository/implementation/sequelize/migrations/20240529070000-create-missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
  src/service/paranet-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  tools/local-network-setup/setup-linux-environment.sh
Labels: release

#3183 OriginTrail Testnet Release v6.4.0
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240429083058-create-paranet.js
  src/modules/repository/implementation/sequelize/migrations/20240529070000-create-missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
  src/service/paranet-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  tools/local-network-setup/setup-linux-environment.sh
Labels: release

#3192 Fix missed paranet ka check
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
Labels: bug

#3213 OriginTrail Mainnet prerelease v6.4.0
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240429083058-create-paranet.js
  src/modules/repository/implementation/sequelize/migrations/20240529070000-create-missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
  src/service/paranet-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  tools/local-network-setup/setup-linux-environment.sh
Labels: release

#3214 OriginTrail Mainnet Release v6.4.0
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/request-schema/query-schema-v0.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240429083058-create-paranet.js
  src/modules/repository/implementation/sequelize/migrations/20240529070000-create-missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
  src/service/paranet-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  tools/local-network-setup/setup-linux-environment.sh
Labels: release

#3215 Updated Simulation script for LinearSum, updated dkg-evm-module package
  package-lock.json
  package.json
  tools/knowledge-assets-distribution-simulation/mocks/blockchain-module-manager-mock.js
  tools/knowledge-assets-distribution-simulation/simulation.js
Labels: internal process, v6

#3216 Add support for BASE blockchain
  config/config.json
  package-lock.json
  package.json
  src/constants/constants.js
  src/modules/blockchain/implementation/base/base-service.js
Labels: feature, v6

#3218 OriginTrail Devnet Release v6.5.0
  config/config.json
  package-lock.json
  package.json
  src/constants/constants.js
  src/modules/blockchain/implementation/base/base-service.js
  tools/knowledge-assets-distribution-simulation/mocks/blockchain-module-manager-mock.js
  tools/knowledge-assets-distribution-simulation/simulation.js
Labels: release
