Repository OriginTrail/ot-node, pull requests merged in 2024-11, with the labels that each got.

#3386 Fixed paranet repositories creation for Fuseki and GraphDB
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/modules/triple-store/implementation/ot-fuseki/ot-fuseki.js
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
Labels: bug, V8

#3406 Improvement/paranet sync
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/common/find-curated-paranet-nodes-command.js
  src/constants/constants.js
  src/service/get-service.js
  src/service/publish-service.js
  src/service/update-service.js
Labels: improvement, V8

#3407 OriginTrail Release v8.1.2-beta
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/common/find-curated-paranet-nodes-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/migrations/20241105150000-change-data-source-col-type-in-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/triple-store/implementation/ot-fuseki/ot-fuseki.js
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
  src/service/get-service.js
  src/service/publish-service.js
  src/service/update-service.js
Labels: improvement, feature, V8

#3410 OriginTrail Testnet Release v8.1.2-beta
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/common/find-curated-paranet-nodes-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/migrations/20241105150000-change-data-source-col-type-in-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20241105160000-add-indexes-to-tables.js
  src/modules/triple-store/implementation/ot-fuseki/ot-fuseki.js
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
  src/service/get-service.js
  src/service/publish-service.js
  src/service/update-service.js
Labels: release, V8

#3426 Feature/remove publish init command
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/common/protocol-schedule-messages-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-init-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-init-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-init-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/network-update-command.js
  src/commands/protocols/update/sender/update-schedule-messages-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/commands/protocols/update/sender/v1.0.0/v1-0-0-update-init-command.js
  src/commands/protocols/update/sender/v1.0.0/v1-0-0-update-request-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/publish-schema-v0.js
  src/controllers/rpc/get-rpc-controller.js
  src/controllers/rpc/publish-rpc-controller.js
  src/controllers/rpc/update-rpc-controller.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/network/network-module-manager.js
  src/modules/repository/implementation/sequelize/migrations/20241125151200-rename-keyword-column-to-datasetroot-in-responses.js
  src/modules/repository/implementation/sequelize/models/get-response.js
  src/modules/repository/implementation/sequelize/models/publish-response.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/file-service.js
  src/service/operation-service.js
  src/service/pending-storage-service.js
  src/service/protocol-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
  src/service/signature-storage-service.js
  src/service/validation-service.js
Labels: feature, V8

#3427 [V8, FEATURE] TripleStoreModule and TripleStoreService for new V8 Graph Structure
  config/config.json
  installer/installer.sh
  scripts/copy-assertions.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/commands/protocols/common/submit-commit-command.js
  src/commands/protocols/common/submit-proofs-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/constants/constants.js
  src/migration/blockchain-identity-migration.js
  src/migration/clean-operational-database-migration.js
  src/migration/clean-sharding-table-migration.js
  src/migration/devnet-neuro-pruning-migration.js
  src/migration/devnet-pruning-migration.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/mark-old-blockchain-events-as-processed-migration.js
  src/migration/mark-staking-events-as-processed-migration.js
  src/migration/migration-executor.js
  src/migration/multiple-op-wallets-user-configuration-migration.js
  src/migration/network-private-key-migration.js
  src/migration/pending-storage-migration.js
  src/migration/private-assets-metadata-migration.js
  src/migration/pull-sharding-table-migration.js
  src/migration/remove-agreement-start-end-time-migration.js
  src/migration/remove-duplicate-service-agreement-migration.js
  src/migration/remove-old-epoch-commands-migration.js
  src/migration/remove-service-agreements-for-chiado-migration.js
  src/migration/service-agreement-pruning-migration.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-invalid-data-migration.js
  src/migration/service-agreements-metadata-migration.js
  src/migration/set-paranet-synced-asset-type-migration.js
  src/migration/telemetry-module-user-configuration-migration.js
  src/migration/triple-store-metadata-migration.js
  src/migration/triple-store-user-configuration-migration.js
  src/migration/ual-extension-triple-store-migration.js
  src/migration/ual-extension-user-configuration-migration.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/data-service.js
  src/service/triple-store-service.js
  test/unit/modules/triple-store/triple-store.test.js
  tools/local-network-setup/.origintrail_noderc_template.json
Labels: feature, V8

#3430 Feature/add paranet local store post validate command
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/local-store/post-local-store-paranet-validate-command.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/repository-module-manager.js
Labels: improvement

#3433 get big suggestion fix
  src/service/sharding-table-service.js
Labels: hotfix

#3439 [V8] [FEATURE] BLS Signatures with Rust binaries
  bin/darwin/arm64/bls-tools
  bin/darwin/x64/bls-tools
  bin/linux/arm64/bls-tools
  bin/linux/x64/bls-tools
  bin/win32/x64/bls-tools.exe
  ot-node.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/constants/constants.js
  src/service/blockchain-event-listener-service.js
  src/service/bls-service.js
  src/service/file-service.js
  src/service/pending-storage-service.js
  src/service/publish-service.js
  src/service/signature-storage-service.js
Labels: feature, V8

#3441 [V8] [IMPROVEMENT] Separated publish finalization into commands
  src/commands/protocols/publish/store-assertion-command.js
  src/commands/protocols/publish/validate-assertion-metadata-command.js
  src/constants/constants.js
  src/service/blockchain-event-listener-service.js
Labels: improvement, V8

#3443 BlockchainEventsService improvements
  config/config.json
  ot-node.js
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/command-executor.js
  src/constants/constants.js
  src/modules/blockchain-events/blockchain-events-module-manager.js
  src/modules/blockchain-events/implementation/blockchain-events-service.js
  src/modules/blockchain-events/implementation/ot-blockchain-events.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/base/base-service.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/blockchain-events-service.js
Labels: improvement, V8

#3440 Feature/move find shard and make node self aware
  src/commands/local-store/local-store-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/publish-find-shard-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
  src/service/operation-service.js
  src/service/publish-service.js
Labels: feature, V8
