Repository OriginTrail/ot-node, pull requests merged in 2024-10, with the labels that each got.

#3297 Added operationId / commandName / commandId to all command logs
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/logger/logger.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
Labels: improvement, V8

#3298 V8/prerelease/testnet
  package-lock.json
  package.json
  src/commands/command-executor.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/logger/logger.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
Labels: improvement, V8

#3300 Add migration that executes set ask script on profice creation
  config/config.json
  ot-node.js
  scripts/set-ask.js
Labels: feature, V8

#3296 Refactored paranet sync, added filtering for missing asset records
  src/commands/paranet/paranet-sync-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/migrations/20240930113000-add-error-message.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/repository-module-manager.js
Labels: improvement, V8

#3308 Check on startup if peerId is same as onchain nodeId
  config/config.json
  ot-node.js
  scripts/set-ask.js
  src/commands/command-executor.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/logger/logger.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/blockchain-event-listener-service.js
  src/service/get-service.js
Labels: feature, V8

#3315 Added Paranet Sync operation statuses, refactored paranet sync
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/curated-paranet-network-get-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/migrations/20241011112100-remove-knowledge-asset-id.js
  src/modules/repository/implementation/sequelize/migrations/20241014164500-paranet-synced-asset-optional-fileds.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/service/get-service.js
Labels: feature, V8

#3320 Curated paranet fixes
  src/commands/local-store/local-store-paranet-command.js
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1-0-0-handle-store-paranet-request-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/paranet-service.js
Labels: V8

#3319 DKG v8.1.0+beta.2 Stable Devnet Release
  package-lock.json
  package.json
  src/service/publish-paranet-service.js
Labels: bug, V8

#3321 V8/curated paranet replication lock
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1-0-0-handle-store-paranet-request-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1_0_0-handle-store-paranet-init-command.js
  src/service/file-service.js
Labels: bug, V8

#3325 Added smarter mechanism for local store retries
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/paranet/paranet-sync-command.js
  src/constants/constants.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/get-service.js
  src/service/triple-store-service.js
Labels: feature, V8

#3322 Remove locks and paranet publish logic
  ot-node.js
  src/commands/local-store/local-store-paranet-command.js
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1-0-0-handle-store-paranet-request-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1_0_0-handle-store-paranet-init-command.js
  src/commands/protocols/publish-paranet/sender/network-publish-paranet-command.js
  src/commands/protocols/publish-paranet/sender/publish-paranet-schedule-messages-command.js
  src/commands/protocols/publish-paranet/sender/publish-paranet-validate-asset.command.js
  src/commands/protocols/publish-paranet/sender/v1.0.0/v1-0-0-publish-paranet-init-command.js
  src/commands/protocols/publish-paranet/sender/v1.0.0/v1-0-0-publish-paranet-request-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/publish-paranet-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/publish-paranet-schema-v0.js
  src/controllers/http-api/v0/result-http-api-controller-v0.js
  src/service/file-service.js
  src/service/protocol-service.js
Labels: chore

#3317 Added localStore with TRIPLE_PARANET store type
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/paranet/paranet-sync-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/get-service.js
  src/service/triple-store-service.js
Labels: feature, V8

#3330 Update incrementParanetKaCount & addToParanetKaCount
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
Labels: bug, V8

#3329 Added check if missed KA for new KAs sync in Paranet Sync
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/repository-module-manager.js
Labels: hotfix, V8

#3332 Updated operation service in the findCuratedParanetNodesCommand
  src/commands/protocols/common/find-curated-paranet-nodes-command.js
  src/constants/constants.js
Labels: hotfix, V8

#3350 Reworked conditions for paranet syncing
  ot-node.js
  src/commands/local-store/local-store-command.js
  src/commands/paranet/paranet-sync-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/migrations/20241023170300-add-synced-data-source.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/get-service.js
Labels: improvement, V8

#3356 Migration to add sync type to already synced asset
  ot-node.js
  src/migration/migration-executor.js
  src/migration/set-paranet-synced-asset-type-migration.js
Labels: feature, V8

#3347 OriginTrail Devnet v8.1.1-beta Release
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/paranet/paranet-sync-command.js
  src/constants/constants.js
  src/migration/migration-executor.js
  src/migration/set-paranet-synced-asset-type-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/module-config-validation.js
  src/modules/repository/implementation/sequelize/migrations/20241023170300-add-synced-data-source.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/get-service.js
Labels: improvement, V8

#3359 Improved batch processing logic for new Paranet KAs syncing
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/paranet/paranet-sync-command.js
Labels: improvement, V8

#3371 OriginTrail Testnet Release v8.1.1-beta
  config/config.json
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  src/commands/command-executor.js
  src/commands/common/validate-asset-command.js
  src/commands/local-store/local-store-command.js
  src/commands/local-store/local-store-paranet-command.js
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/common/find-curated-paranet-nodes-command.js
  src/commands/protocols/common/find-nodes-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/curated-paranet-network-get-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1-0-0-handle-store-paranet-request-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1_0_0-handle-store-paranet-init-command.js
  src/commands/protocols/publish-paranet/sender/network-publish-paranet-command.js
  src/commands/protocols/publish-paranet/sender/publish-paranet-schedule-messages-command.js
  src/commands/protocols/publish-paranet/sender/publish-paranet-validate-asset.command.js
  src/commands/protocols/publish-paranet/sender/v1.0.0/v1-0-0-publish-paranet-init-command.js
  src/commands/protocols/publish-paranet/sender/v1.0.0/v1-0-0-publish-paranet-request-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/local-store-http-api-controller-v0.js
  src/controllers/http-api/v0/publish-paranet-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/local-store-schema-v0.js
  src/controllers/http-api/v0/request-schema/publish-paranet-schema-v0.js
  src/controllers/rpc/publish-paranet-rpc-controller.js
  src/controllers/rpc/rpc-router.js
  src/logger/logger.js
  src/migration/migration-executor.js
  src/migration/set-paranet-synced-asset-type-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/module-config-validation.js
  src/modules/repository/implementation/sequelize/migrations/20240930113000-add-error-message.js
  src/modules/repository/implementation/sequelize/migrations/20241011112100-remove-knowledge-asset-id.js
  src/modules/repository/implementation/sequelize/migrations/20241014164500-paranet-synced-asset-optional-fileds.js
  src/modules/repository/implementation/sequelize/migrations/20241023170300-add-synced-data-source.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/missed-paranet-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/get-service.js
  src/service/paranet-service.js
  src/service/protocol-service.js
  src/service/publish-paranet-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
Labels: improvement, V8

#3375 Updated installer, removed V6 mentions, Node.js 20 as requirement, updated CODEOWNERS
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report_v8.md
  .github/actions/setup/action.yml
  .github/workflows/update-cache.yml
  README.md
  docs/openapi/DKGv8.yaml
  docs/postman/DKGv8.postman_collection.json
  installer/README.md
  installer/data/blazegraph.service
  installer/data/fuseki.service
  installer/data/graphdb.service
  installer/data/otnode.service
  installer/data/template/.origintrail_noderc_one_click_mainnet.json
  installer/data/template/.origintrail_noderc_one_click_testnet.json
  installer/data/template/.v8_origintrail_noderc_testnet.json
  installer/installer.sh
  installer/v8_installer.sh
  tools/local-network-setup/README.md
Labels: chore, V8

#3376 OriginTrail Testnet Release v8.1.1-beta
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report_v8.md
  .github/actions/setup/action.yml
  .github/workflows/update-cache.yml
  README.md
  docs/openapi/DKGv8.yaml
  docs/postman/DKGv8.postman_collection.json
  installer/README.md
  installer/data/blazegraph.service
  installer/data/fuseki.service
  installer/data/graphdb.service
  installer/data/otnode.service
  installer/data/template/.origintrail_noderc_one_click_mainnet.json
  installer/data/template/.origintrail_noderc_one_click_testnet.json
  installer/installer.sh
  installer/v8_installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-command.js
  src/commands/paranet/paranet-sync-command.js
  src/constants/constants.js
  src/migration/migration-executor.js
  src/migration/set-paranet-synced-asset-type-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/module-config-validation.js
  src/modules/repository/implementation/sequelize/migrations/20241023170300-add-synced-data-source.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/get-service.js
  tools/local-network-setup/README.md
Labels: improvement, V8

#3379 OriginTrail Testnet Release v8.1.1-beta.2 Hotfix
  ot-node.js
  package-lock.json
  package.json
Labels: V8

#3381 Updated dkg-evm-module dependency
  package-lock.json
  package.json
Labels: V8

#3382 OriginTrail Testnet Release v8.1.1-beta Hotfix 2
  package-lock.json
  package.json
Labels: V8
