Repository OriginTrail/ot-node, pull requests merged in 2024-02, with the labels that each got.

#2910 Fixed LinearSum score calculation
  src/constants/constants.js
  src/service/proximity-scoring-service.js
Labels: bug

#2912 OriginTrail Devnet Release v6.2.0 Hotfix 4
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/constants/constants.js
  src/migration/migration-executor.js
  src/migration/pull-sharding-table-migration.js
  src/migration/remove-service-agreements-for-chiado-migration.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240126120000-shard-add-sha256blobl.js
  src/modules/repository/implementation/sequelize/migrations/20240201100000-remove-sha256Blob.js
  src/modules/repository/implementation/sequelize/models/shard.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/service/blockchain-event-listener-service.js
  src/service/proximity-scoring-service.js
  src/service/sharding-table-service.js
Labels: release

#2918 Increase gas limit for set stake
  scripts/set-stake.js
Labels: bug

#2924 Gnosis Testnet installer extension
  installer/installer.sh
  ot-node.js
Labels: chore

#2956 OriginTrail v6.2.0 Devnet Release
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/constants/constants.js
  src/migration/migration-executor.js
  src/migration/multiple-op-wallets-user-configuration-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  test/bdd/steps/api/datasets/privateKeys-management-wallets.json
  test/bdd/steps/api/datasets/privateKeys.json
  test/bdd/steps/api/datasets/publicKeys-management-wallets.json
  test/bdd/steps/api/datasets/publicKeys.json
  tools/local-network-setup/.origintrail_noderc_template.json
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release, v6

#2957 Fixed parachain wallets verification on web3-service init
  package-lock.json
  package.json
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
Labels: bug

#2958 OriginTrail v.6.2.0 Devnet Prerelease Hotfix 8
  package-lock.json
  package.json
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
Labels: release, v6

#2959 OriginTrail v6.2.0 Devnet Release Hotfix 8
  package-lock.json
  package.json
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
Labels: release, v6

#2967 OriginTrail Devnet Release v6.2.0 Hotfix 10
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  test/bdd/steps/api/datasets/requests.json
  test/utilities/steps-utils.mjs
Labels: release

#2969 OriginTrail Testnet Release v6.2.0 Hotfix 10
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/protocols/common/epoch-check-command.js
  src/constants/constants.js
  src/migration/migration-executor.js
  src/migration/multiple-op-wallets-user-configuration-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  test/bdd/steps/api/datasets/privateKeys-management-wallets.json
  test/bdd/steps/api/datasets/privateKeys.json
  test/bdd/steps/api/datasets/publicKeys-management-wallets.json
  test/bdd/steps/api/datasets/publicKeys.json
  test/bdd/steps/api/datasets/requests.json
  test/utilities/steps-utils.mjs
  tools/local-network-setup/.origintrail_noderc_template.json
  tools/local-network-setup/generate-config-files.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release

#2970 Preparation for Hotfix 11
  package-lock.json
  package.json
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/web3-service.js
Labels: chore

#2971 OriginTrail Devnet Prerelease v6.2.0 Hotfix 11
  package-lock.json
  package.json
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/web3-service.js
Labels: release

#2977 OriginTrail Devnet Release v6.2.0 RC
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/common/sharding-table-check-command.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
Labels: release

#2978 OriginTrail Testnet Prerelease v6.2.0 RC
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/common/sharding-table-check-command.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
Labels: release

#2979 OriginTrail Testnet Release v6.2.0 RC
  package-lock.json
  package.json
  src/commands/common/send-telemetry-command.js
  src/commands/common/sharding-table-check-command.js
  src/constants/constants.js
  src/migration/pull-sharding-table-migration.js
Labels: release

#2982 OriginTrail Devnet Prerelease v6.2.0 Hotfix 12
  config/config.json
  package-lock.json
  package.json
  src/service/proximity-scoring-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
Labels: release

#2989 Devnet release - remove hotfix
  package-lock.json
  package.json
Labels: chore

#3002 Added UalExtensionTripleStoreMigration on startup
  src/commands/protocols/common/epoch-check-command.js
Labels: bug

#3003 Added prioritization for transactions
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
Labels: feature

#3001 Fix gnosis getGasPrice functio and add suport for different oracles
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
Labels: bug

#3009 [IMPROVEMENT] Get optimizations
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/service/file-service.js
  src/service/pending-storage-service.js
Labels: bug, improvement, v6

#3010 Added missing localStore for get inside SimpleAssetSync
  src/commands/protocols/common/simple-asset-sync-command.js
  src/service/get-service.js
Labels: bug, v6

#3013 OriginTrail Devnet Release v6.2.1
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240221162000-add-service-agreement-data-source.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/get-service.js
  src/service/hashing-service.js
  src/service/pending-storage-service.js
  src/service/proximity-scoring-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  tools/knowledge-assets-distribution-simulation/mocks/blockchain-module-manager-mock.js
Labels: release

#3021 OriginTrail Testnet Prerelease v6.2.1
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240221162000-add-service-agreement-data-source.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/get-service.js
  src/service/hashing-service.js
  src/service/pending-storage-service.js
  src/service/proximity-scoring-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  tools/knowledge-assets-distribution-simulation/mocks/blockchain-module-manager-mock.js
Labels: release

#3026 Handle network get failed in simple asset sync command
  package-lock.json
  package.json
  src/commands/protocols/common/simple-asset-sync-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/service-agreement-service.js
Labels: bug

#3029 OriginTrail Devnet Prerelease v6.2.1 Hotfix 2
  installer/installer.sh
  package-lock.json
  package.json
  src/commands/protocols/common/simple-asset-sync-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/service-agreement-service.js
Labels: hotfix

#3030 OriginTrail Devnet Release v6.2.1 Hotfix 2
  installer/installer.sh
  package-lock.json
  package.json
  src/commands/protocols/common/simple-asset-sync-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/service-agreement-service.js
Labels: hotfix

#3033 OriginTrail Testnet Prerelease v6.2.1 Hotfix 2
  installer/installer.sh
  package-lock.json
  package.json
  src/commands/protocols/common/simple-asset-sync-command.js
  src/modules/blockchain/implementation/web3-service.js
  src/service/service-agreement-service.js
Labels: hotfix

#3034 Updated max file size supported on ot-node
  src/constants/constants.js
Labels: chore

#3025 OriginTrail Testnet Release v6.2.1
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240221162000-add-service-agreement-data-source.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/get-service.js
  src/service/hashing-service.js
  src/service/pending-storage-service.js
  src/service/proximity-scoring-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  tools/knowledge-assets-distribution-simulation/mocks/blockchain-module-manager-mock.js
Labels: release

#3042 Updated version - removed hotfix
  config/config.json
  package-lock.json
  package.json
Labels: chore

#3044 Updated version - removed hotfix
  config/config.json
  installer/installer.sh
  package-lock.json
  package.json
Labels: chore

#3045 Updated version - removed hotfix
  config/config.json
  installer/installer.sh
  package-lock.json
  package.json
Labels: chore

#3046 Updated version - removed hotfix
  config/config.json
  installer/installer.sh
  package-lock.json
  package.json
Labels: chore

#3039 OriginTrail Mainnet Prerelease v6.2.1
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240221162000-add-service-agreement-data-source.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/get-service.js
  src/service/hashing-service.js
  src/service/pending-storage-service.js
  src/service/proximity-scoring-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  tools/knowledge-assets-distribution-simulation/mocks/blockchain-module-manager-mock.js
Labels: release

#3048 OriginTrail Mainnet Release v6.2.1
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/commands/protocols/get/sender/get-assertion-id-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/publish-schedule-messages-command.js
  src/commands/protocols/update/receiver/delete-pending-state-command.js
  src/commands/protocols/update/receiver/submit-update-commit-command.js
  src/constants/constants.js
  src/migration/service-agreements-data-inspector.js
  src/migration/service-agreements-metadata-migration.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/gnosis/gnosis-service.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240221162000-add-service-agreement-data-source.js
  src/modules/repository/implementation/sequelize/models/service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/blockchain-event-repository.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  src/service/file-service.js
  src/service/get-service.js
  src/service/hashing-service.js
  src/service/pending-storage-service.js
  src/service/proximity-scoring-service.js
  src/service/service-agreement-service.js
  src/service/sharding-table-service.js
  test/unit/mock/blockchain-module-manager-mock.js
  tools/knowledge-assets-distribution-simulation/mocks/blockchain-module-manager-mock.js
Labels: release

#3050 Split epoch check for each blockchain
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/constants/constants.js
Labels: improvement

#3053 OriginTrail Devnet Prerelease v6.2.2
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: release

#3055 OriginTrail Devnet Release v6.2.2
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: release

#3058 OriginTrail Testnet Prerelease v6.2.2
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: release

#3059 OriginTrail Testnet Release v6.2.2
  ot-node.js
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
  src/commands/protocols/common/simple-asset-sync-command.js
  src/constants/constants.js
  src/migration/get-old-service-agreements-migration.js
  src/migration/migration-executor.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: release

#3062 Updated default period for blockchain epoch check command
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
Labels: hotfix

#3063 OriginTrail Devnet Prerelease v6.2.2 Hotfix 1
  package-lock.json
  package.json
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/commands/protocols/common/epoch-check/epoch-check-command.js
Labels: release
