Repository OriginTrail/ot-node, pull requests merged in 2024-04, with the labels that each got.

#3110 Improvment/use both ip and token auth
  config/config.json
  src/service/auth-service.js
Labels: improvement

#3124 Support staking for Neuro
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/commands/common/get-latest-service-agreement/get-latest-service-agreement.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: feature

#3125 Optimized function for fetching latest service agreements.
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
Labels: chore

#3126 OriginTrail Devnet Prerelease v6.3.0
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/commands/common/get-latest-service-agreement/get-latest-service-agreement.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/bid-suggestion-schema-v0.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release

#3130 OriginTrail Devnet Release v6.3.0
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/commands/common/get-latest-service-agreement/get-latest-service-agreement.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release

#3133 OriginTrail Testnet Prerelease v6.3.0
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/commands/common/get-latest-service-agreement/get-latest-service-agreement.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release

#3136 Devnet 4.3.0 hotfix 1
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/constants/constants.js
Labels: hotfix

#3138 OriginTrail Devnet Release v6.3.0.Hotfix 1
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
Labels: hotfix

#3143 OriginTrail Testnet Prerelease v6.3.0.Hotfix 1
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
Labels: hotfix

#3144 OriginTrail Testnet Release v6.3.0.Hotfix 1
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
Labels: hotfix

#3146 V6/6.3.0.hotfix2
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: hotfix

#3148 OriginTrail Devnet Release v6.3.0.Hotfix 2
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: hotfix

#3149 OriginTrail Testnet Prerelease v6.3.0.Hotfix 2
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: hotfix

#3150 OriginTrail Testnet Release v6.3.0.Hotfix 2
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
Labels: hotfix

#3152 Version updated - removed hotfix from version
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
Labels: hotfix

#3155 Version updated - removed hotfix from version
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
Labels: hotfix

#3156 Version updated - removed hotfix from version
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
Labels: hotfix

#3135 OriginTrail Mainnet Prerelease v6.3.0
  package-lock.json
  package.json
  src/commands/common/get-latest-service-agreement/blockchain-get-latest-service-agreement.js
  src/commands/common/get-latest-service-agreement/get-latest-service-agreement.js
  src/commands/protocols/common/epoch-check/blockchain-epoch-check-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/bid-suggestion-http-api-controller-v0.js
  src/modules/blockchain/implementation/hardhat/hardhat-service.js
  src/modules/blockchain/implementation/ot-parachain/ot-parachain-service.js
  src/modules/repository/implementation/sequelize/repositories/service-agreement-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/blockchain-event-listener-service.js
  tools/local-network-setup/setup-macos-environment.sh
Labels: release
