Repository OriginTrail/ot-node, pull requests merged in 2024-09, with the labels that each got.

#3272 Increased gasLimit for commits/proofs
  package-lock.json
  package.json
  src/constants/constants.js
Labels: bug, P1

#3282 Update version and logs when node starts
  ot-node.js
  package-lock.json
  package.json
Labels: feature

#3286 Add devnet operational db pruning migration
  ot-node.js
  src/migration/devnet-pruning-migration.js
  src/migration/migration-executor.js
Labels: chore

#3288 Feature/paranet update
  src/commands/protocols/update-paranet/receiver/v1.0.0/v1-0-0-handle-update-paranet-init-command.js
  src/commands/protocols/update-paranet/receiver/v1.0.0/v1-0-0-handle-update-paranet-request-command.js
  src/commands/protocols/update-paranet/sender/network-update-paranet-command.js
  src/commands/protocols/update-paranet/sender/update-paranet-schedule-messages-command.js
  src/commands/protocols/update-paranet/sender/update-paranet-validate-asset-command.js
  src/commands/protocols/update-paranet/sender/v1.0.0/v1-0-0-update-paranet-init-command.js
  src/commands/protocols/update-paranet/sender/v1.0.0/v1-0-0-update-paranet-request-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/request-schema/update-paranet-schema-v0.js
  src/controllers/http-api/v0/update-paranet-http-api-controller-v0.js
  src/controllers/rpc/rpc-router.js
  src/controllers/rpc/update-paranet-rpc-controller.js
  src/modules/repository/implementation/sequelize/migrations/20240924120000-create-update-paranet.js
  src/modules/repository/implementation/sequelize/models/update-paranet.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/service/update-paranet-service.js
Labels: feature

#3287 Feature/paranet publish
  ot-node.js
  package-lock.json
  package.json
  src/commands/local-store/local-store-paranet-command.js
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/common/find-curated-paranet-nodes-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1-0-0-handle-store-paranet-request-command.js
  src/commands/protocols/publish-paranet/receiver/v1.0.0/v1_0_0-handle-store-paranet-init-command.js
  src/commands/protocols/publish-paranet/sender/network-publish-paranet-command.js
  src/commands/protocols/publish-paranet/sender/publish-paranet-schedule-messages-command.js
  src/commands/protocols/publish-paranet/sender/publish-paranet-validate-asset.command.js
  src/commands/protocols/publish-paranet/sender/v1.0.0/v1-0-0-publish-paranet-init-command.js
  src/commands/protocols/publish-paranet/sender/v1.0.0/v1-0-0-publish-paranet-request-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/publish-paranet-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/publish-paranet-schema-v0.js
  src/controllers/rpc/publish-paranet-rpc-controller.js
  src/controllers/rpc/rpc-router.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20240923195000-create-publish-paranet.js
  src/modules/repository/implementation/sequelize/migrations/20240924161700-create-paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/migrations/20240924205500-create-publish-paranet-response.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/models/publish-paranet-response.js
  src/modules/repository/implementation/sequelize/models/publish-paranet.js
  src/modules/repository/implementation/sequelize/repositories/operation-repository.js
  src/modules/repository/implementation/sequelize/repositories/operation-response.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/get-service.js
  src/service/protocol-service.js
  src/service/publish-paranet-service.js
Labels: feature

#3290 Curated paranet sync
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/common/find-curated-paranet-nodes-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/curated-paranet-network-get-command.js
  src/commands/protocols/get/sender/get-schedule-messages-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-init-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/constants/constants.js
  src/modules/repository/implementation/sequelize/migrations/20240927110000-change-paranet-synced-asset-nullable-assertions.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/get-service.js
Labels: feature, V8

#3291 Fixed logic for getting public/private nQuads from curated paranet node
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/service/get-service.js
Labels: bug, V8

#3292 Fix/curated paranet network get
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/get/sender/curated-paranet-network-get-command.js
Labels: bug, V8

#3293 Fixed metadata handling for curated paranet sync
  package-lock.json
  package.json
  src/commands/paranet/paranet-sync-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-init-command.js
  src/service/get-service.js
Labels: bug, V8

#3294 V8/feature/local get queries paranet repo
  package-lock.json
  package.json
  src/commands/protocols/get/sender/local-get-command.js
  src/controllers/http-api/v0/get-http-api-controller-v0.js
  src/controllers/http-api/v0/request-schema/get-schema-v0.js
  src/service/paranet-service.js
Labels: feature, V8
