Repository OriginTrail/ot-node, pull requests merged in 2025-01, with the labels that each got.

#3670 Use correct testnet branch in installer
  installer/installer.sh
Labels: chore

#3671 Increase frequency and max number files deleted
  package-lock.json
  package.json
  src/constants/constants.js
Labels: chore

#3673 V8.0.0+hotfix.5 Testnet Prerelease
  installer/installer.sh
  package-lock.json
  package.json
  src/constants/constants.js
Labels: release, V8

#3676 V8.0.0+hotfix.5 Testnet Release
  installer/installer.sh
  package-lock.json
  package.json
  src/constants/constants.js
Labels: release, V8

#3677 V8.0.0+hotfix.5 Mainnet Prerelease
  installer/installer.sh
  package-lock.json
  package.json
  src/constants/constants.js
Labels: release, V8

#3678 V8.0.0+hotfix.5 Mainnet Release
  installer/installer.sh
  package-lock.json
  package.json
  src/constants/constants.js
Labels: release, V8

#3691 V8.0.1 Testnet Release
  package-lock.json
  package.json
  scripts/set-ask.js
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v1/get-http-api-controller-v1.js
  src/controllers/http-api/v1/query-http-api-controller-v1.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/repository/implementation/sequelize/migrations/20241215122200-create-paranet-kc.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet-kc.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/paranet-kc-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/paranet-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
Labels: release, V8

#3692 fixed JSON bag
  src/modules/network/implementation/libp2p-service.js
Labels: bug, V8

#3699 Move all logic in try catch inside findPeerAddressAndProtocols
  src/service/sharding-table-service.js
Labels: improvement, V8

#3698 Rework KC insert to insert in KA chunks
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/triple-store-service.js
Labels: improvement, V8

#3700 8.0.1+hotfix.1 Testnet Prerelease
  package.json
  src/modules/network/implementation/libp2p-service.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
Labels: release, V8

#3701 8.0.1+hotfix.1 Testnet Release
  package.json
  src/modules/network/implementation/libp2p-service.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
Labels: release, V8
