Repository OriginTrail/ot-node, pull requests merged in 2025-03, with the labels that each got.

#3755 Remove telemetry events
  src/commands/local-store/local-store-command.js
  src/commands/protocols/ask/receiver/v1.0.0/v1-0-0-handle-ask-request-command.js
  src/commands/protocols/ask/sender/ask-find-shard-command.js
  src/commands/protocols/ask/sender/network-ask-command.js
  src/commands/protocols/ask/sender/v1.0.0/v1-0-0-ask-request-command.js
  src/commands/protocols/common/find-shard-command.js
  src/commands/protocols/common/handle-protocol-message-command.js
  src/commands/protocols/common/network-protocol-command.js
  src/commands/protocols/common/protocol-message-command.js
  src/commands/protocols/common/protocol-request-command.js
  src/commands/protocols/finality/receiver/v1.0.0/v1-0-0-handle-finality-request-command.js
  src/commands/protocols/finality/sender/network-finality-command.js
  src/commands/protocols/finality/sender/v1.0.0/v1-0-0-finality-request-command.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/get/sender/network-get-command.js
  src/commands/protocols/get/sender/v1.0.0/v1-0-0-get-request-command.js
  src/commands/protocols/publish/receiver/v1.0.0/v1-0-0-handle-store-request-command.js
  src/commands/protocols/publish/sender/network-publish-command.js
  src/commands/protocols/publish/sender/publish-find-shard-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/publish/sender/v1.0.0/v1-0-0-publish-request-command.js
  src/commands/protocols/update/receiver/v1.0.0/v1-0-0-handle-update-request-command.js
  src/commands/protocols/update/sender/network-update-command.js
  src/commands/protocols/update/sender/update-find-shard-command.js
  src/commands/protocols/update/sender/update-validate-asset-command.js
  src/commands/protocols/update/sender/v1.0.0/v1-0-0-update-request-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v0/publish-http-api-controller-v0.js
Labels: chore

#3776 Add filterInactive arg to getAllPeerRecords to filter out peers we couldn't dial
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/service/sharding-table-service.js
Labels: improvement

#3777 Fix scheduling of commmands in FinalityController
  src/commands/protocols/finality/receiver/v1.0.0/v1-0-0-handle-finality-request-command.js
  src/controllers/rpc/finality-rpc-controller.js
Labels: bug

#3779 v8.0.3 Testnet Prerelease
  package-lock.json
  package.json
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/finality/receiver/publish-finality-save-ack-command.js
  src/commands/protocols/finality/receiver/v1.0.0/v1-0-0-handle-finality-request-command.js
  src/commands/protocols/publish/publish-finalization-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-replication-command.js
  src/constants/constants.js
  src/controllers/http-api/v1/publish-http-api-controller-v1.js
  src/controllers/rpc/finality-rpc-controller.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/finality-service.js
  src/service/messaging-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
Labels: release

#3783 V8.0.3 Mainnet Prerelease
  package-lock.json
  package.json
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/finality/receiver/publish-finality-save-ack-command.js
  src/commands/protocols/finality/receiver/v1.0.0/v1-0-0-handle-finality-request-command.js
  src/commands/protocols/publish/publish-finalization-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-replication-command.js
  src/constants/constants.js
  src/controllers/http-api/v1/publish-http-api-controller-v1.js
  src/controllers/rpc/finality-rpc-controller.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/finality-service.js
  src/service/messaging-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
Labels: release

#3784 V8.0.3 Mainnet Release
  package-lock.json
  package.json
  src/commands/blockchain-event-listener/blockchain-event-listener-command.js
  src/commands/local-store/local-store-command.js
  src/commands/protocols/finality/receiver/publish-finality-save-ack-command.js
  src/commands/protocols/finality/receiver/v1.0.0/v1-0-0-handle-finality-request-command.js
  src/commands/protocols/publish/publish-finalization-command.js
  src/commands/protocols/publish/read-cached-publish-data-command.js
  src/commands/protocols/publish/sender/publish-replication-command.js
  src/constants/constants.js
  src/controllers/http-api/v1/publish-http-api-controller-v1.js
  src/controllers/rpc/finality-rpc-controller.js
  src/modules/blockchain-events/implementation/ot-ethers/ot-ethers.js
  src/modules/repository/implementation/sequelize/repositories/shard-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/service/finality-service.js
  src/service/messaging-service.js
  src/service/publish-service.js
  src/service/sharding-table-service.js
Labels: release
