Repository OriginTrail/ot-node, pull requests merged in 2025-02, with the labels that each got.

#3708 Add local store
  package-lock.json
  package.json
  src/constants/constants.js
  src/controllers/http-api/v1/local-store-http-api-controller-v1.js
  src/controllers/http-api/v1/request-schema/local-store-schema-v1.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/triple-store-service.js
Labels: feature, V8

#3711 Add support for graphdb
  package-lock.json
  package.json
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
Labels: chore, V8

#3712 v8.0.1+hotfix.5
  package-lock.json
  package.json
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
Labels: release, V8

#3713 v8.0.1+hotfix.5 Testnet Release
  package-lock.json
  package.json
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
Labels: release, V8

#3719 Update comunica/query-sparql version
  package-lock.json
  package.json
Labels: chore, V8

#3720 8.0.1+hotfix.6 Testnet Prerelease
  package-lock.json
  package.json
Labels: release, V8

#3722 8.0.0+hotfix.7 Mainnet Prerelease
  package-lock.json
  package.json
Labels: release, V8

#3723 8.0.0+hotfix.7 Mainnet Release
  package-lock.json
  package.json
Labels: release, V8

#3727 Fix private merkle root validation
  package.json
  src/service/validation-service.js
Labels: bug

#3737 8.1.3+beta.11 Development Network Released
  package-lock.json
  package.json
  src/modules/http-client/implementation/middleware/authentication-middleware.js
Labels: release

#3738 Stable Development release
  package-lock.json
  package.json
  src/modules/http-client/implementation/middleware/authentication-middleware.js
Labels: release

#3739 Fix incrementRetries to update errorMessage
  src/modules/repository/implementation/sequelize/repositories/paranet-kc-repository.js
Labels: bug

#3742 v8.0.0 Testnet Prerelease
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/paranet-kc-repository.js
Labels: release

#3743 v8.0.1 Testnet Release
  package-lock.json
  package.json
  src/modules/repository/implementation/sequelize/repositories/paranet-kc-repository.js
Labels: release, V8

#3744 v8.0.1 Mainnet Prerelease
  README.md
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  src/commands/common/validate-asset-command.js
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/publish/store-assertion-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v1/get-http-api-controller-v1.js
  src/controllers/http-api/v1/local-store-http-api-controller-v1.js
  src/controllers/http-api/v1/query-http-api-controller-v1.js
  src/controllers/http-api/v1/request-schema/local-store-schema-v1.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/migrations/20241215122200-create-paranet-kc.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet-kc.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/paranet-kc-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/paranet-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
Labels: release, V8

#3745 v8.0.1 Mainnet Release
  README.md
  config/config.json
  installer/installer.sh
  ot-node.js
  package-lock.json
  package.json
  scripts/set-ask.js
  src/commands/common/validate-asset-command.js
  src/commands/paranet/paranet-sync-command.js
  src/commands/paranet/start-paranet-sync-commands.js
  src/commands/protocols/get/receiver/v1.0.0/v1-0-0-handle-get-request-command.js
  src/commands/protocols/get/sender/get-find-shard-command.js
  src/commands/protocols/get/sender/get-validate-asset-command.js
  src/commands/protocols/get/sender/local-get-command.js
  src/commands/protocols/publish/sender/publish-validate-asset-command.js
  src/commands/protocols/publish/store-assertion-command.js
  src/commands/query/query-command.js
  src/constants/constants.js
  src/controllers/http-api/v1/get-http-api-controller-v1.js
  src/controllers/http-api/v1/local-store-http-api-controller-v1.js
  src/controllers/http-api/v1/query-http-api-controller-v1.js
  src/controllers/http-api/v1/request-schema/local-store-schema-v1.js
  src/modules/blockchain/blockchain-module-manager.js
  src/modules/blockchain/implementation/web3-service.js
  src/modules/network/implementation/libp2p-service.js
  src/modules/repository/implementation/sequelize/migrations/20241215122200-create-paranet-kc.js
  src/modules/repository/implementation/sequelize/models/missed-paranet-asset.js
  src/modules/repository/implementation/sequelize/models/paranet-kc.js
  src/modules/repository/implementation/sequelize/models/paranet-synced-asset.js
  src/modules/repository/implementation/sequelize/repositories/paranet-kc-repository.js
  src/modules/repository/implementation/sequelize/repositories/paranet-synced-asset-repository.js
  src/modules/repository/implementation/sequelize/sequelize-repository.js
  src/modules/repository/repository-module-manager.js
  src/modules/triple-store/implementation/ot-blazegraph/ot-blazegraph.js
  src/modules/triple-store/implementation/ot-graphdb/ot-graphdb.js
  src/modules/triple-store/implementation/ot-triple-store.js
  src/modules/triple-store/triple-store-module-manager.js
  src/service/paranet-service.js
  src/service/sharding-table-service.js
  src/service/triple-store-service.js
  src/service/ual-service.js
Labels: release, V8
